---
sidebar: sidebar 
permalink: concept_lic_platforms.html 
keywords: license, licensing, platform license offerings, license offerings, standard, premium, premium xl 
summary: ONTAP Select 용량 계층 또는 용량 풀 라이센스는 세 가지 플랫폼 용량 수준 중 하나로 구입할 수 있습니다. 이러한 라이센스 오퍼링은 ONTAP Select를 구축하는 호스트의 기능을 결정합니다. 
---
= ONTAP Select용 플랫폼 라이센스 오퍼링에 대해 알아보십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
표준, 프리미엄 또는 프리미엄 XL 레벨로 ONTAP Select 용량 계층 또는 용량 풀 라이센스를 구매할 수 있습니다. 이러한 라이센스 오퍼링은 ONTAP Select를 구축하는 호스트의 기능을 결정합니다.



== 플랫폼 라이센스 제공 내용

특정 라이선스 제공은 하이퍼바이저 호스트의 기능을 두 가지 영역에서 결정합니다.

* 인스턴스 유형(CPU, 메모리)
* 추가 기능


라이센스 서비스는 표준 XL에서 프리미엄 XL로 상향 조정되어 있습니다. 일반적으로 선택하는 라이센스 옵션은 해당 수준의 기능 및 모든 하위 수준을 부여합니다. 예를 들어, 프리미엄 레벨은 프리미엄 및 표준의 기능을 모두 제공합니다.

다음 표에서는 표준, 프리미엄, 프리미엄 XL 라이선스 제공의 기능을 비교합니다.

[cols="25,25,25,25,25"]
|===
2+| 라이센스 지원 ... | 표준 | 프리미엄 | Premium XL 


2+| 인스턴스 유형 | 작은 것만 | 작거나 중간 | 소형, 중형 또는 대형 


.2+| ...의 하드 디스크 드라이브(HDD) | 하드웨어 RAID 구성 | 예 | 예 | 예 


| vNAS 구성 | 예 | 예 | 예 


.3+| ...의 솔리드 스테이트 드라이브(SSD) | 하드웨어 RAID 구성 | 아니요 | 예 | 예 


| 소프트웨어 RAID 구성 | 아니요 | 예 | 예 


| vNAS 구성 | 예 | 예 | 예 


.3+| NVMe 드라이브는 ... | 하드웨어 RAID 구성 | 아니요 | 아니요 | 예 


| 소프트웨어 RAID 구성 | 아니요 | 아니요 | 예 


| vNAS 구성 | 예 | 예 | 예 


2+| MetroCluster SDS | 아니요 | 예 | 예 
|===

NOTE: 커널 기반 가상 머신(KVM)은 대형 인스턴스 유형을 지원하지 않습니다.



== 플랫폼 라이센스 제품에 대한 하드웨어 지원을 비교합니다

표준, 프리미엄 및 프리미엄 XL 라이센스 제품은 다양한 하드웨어 및 소프트웨어를 지원합니다. 하드웨어 및 소프트웨어 버전에 대한 최신 정보는 link:https://mysupport.netapp.com/matrix/["상호 운용성 매트릭스 툴"^]을 참조하십시오.

[role="tabbed-block"]
====
.핵심 항목
--
[cols="5"30"]
|===


2+| 핵심 항목 유형 3+| 설명 


2+| 호스트 프로토콜 3+| NFS, SMB/CIFS, iSCSI 및 NVMe over TCP 


2+| 구축 옵션 3+| 단일 노드 2노드 클러스터(HA 쌍) 4, 6, 8, 10 또는 12노드 클러스터 


2+| 지원되는 용량(노드당) 3+| 최대 400TB의 원시 데이터(ESXi 및 KVM) 
|===
--
.하드웨어
--
[cols="5"30"]
|===


2+| 하드웨어 유형입니다 3+| 설명 


2+| 인스턴스 크기 | 작은 크기 | 중간 | 대형 


2+| CPU 제품군 | Intel Xeon E5-26xx v3(Haswell) 이상 | Intel Xeon E5-26xx v3(Haswell) 이상 | Intel Xeon E5-26xx v3(Haswell) 이상 


2+| ONTAP Select CPU/메모리 | vCPU(가상 CPU) 4개/16GB RAM | vCPU 8개/64GB RAM | 16개의 vCPU/128GB RAM 


2+| 호스트 CPU/메모리 최소 요구 사항 | 6코어/24GB RAM | 10코어/72GB RAM | 18코어/136GB RAM 


2+| 네트워크(노드당) 3+| 단일 노드 클러스터의 경우 최소 2개의 1GbE 포트 2노드 클러스터(HA 쌍)의 경우 최소 4개의 1GbE 포트 4, 6, 8, 10 또는 12노드 클러스터의 경우 최소 2개의 10GbE 포트 
|===
^1^ 하이퍼바이저에 대해 두 개의 코어와 8GB의 RAM을 가정합니다.

--
.스토리지 유형입니다
--
다음 표에는 지정된 스토리지에 필요한 최소 라이센스 유형이 나와 있습니다. 

[cols="5"30"]
|===


2+| 스토리지 유형입니다 3+| 설명 


2+| 사용권 유형 | 표준 | 프리미엄 | Premium XL 


2+| 인스턴스 크기 | 작은 크기 | 소형 및 중형 | 소형, 중형, 대형 


2+| 하드웨어 RAID 컨트롤러가 있는 로컬 DAS | 8-60개 드라이브 | 8-60개 드라이브 | 8-60개 드라이브 


2+| HDD(SAS, NL-SAS, SATA) | 해당 없음 | 4-60개의 드라이브 | 4-60개의 드라이브 


2+| SSD(SAS) | 해당 없음 | 4~60개 드라이브(SSD만) | 4~60개 드라이브(SSD만) 


2+| 소프트웨어 RAID가 있는 로컬 DAS | 해당 없음 | 해당되는 | 4-14개 드라이브(NVMe만 해당) 


2+| 외부 배열 1 3+| 외부 어레이에서 호스팅되는 데이터 저장소는 FC, FCoE, iSCSI 및 NFS를 통해 연결됩니다(NFS는 KVM에서 지원되지 않음). 이러한 데이터 저장소는 높은 가용성과 복원력을 제공합니다. 
|===
외부 스토리지 프로토콜 지원은 네트워크 스토리지 연결을 반영합니다.

--
.소프트웨어
--
[cols="5"30"]
|===


2+| 소프트웨어 유형입니다 3+| 설명 


2+| 하이퍼바이저 지원(VMware) 3+| VMware vSphere 9.0 VMware vSphere 8.0GA 및 업데이트 1~3 VMware vSphere 7.0GA 및 업데이트 1~3C 


2+| 하이퍼바이저 지원(KVM)  a| 
Red Hat Enterprise Linux 64비트(KVM) 10.1, 10.0, 9.7, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.8, 8.7 및 8.6

Rocky Linux(KVM) 10.0, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7 및 8.6

*참고*: RHEL 10.1 및 10.0과 Rocky Linux 10.0 호스트의 KVM 하이퍼바이저에는 소프트웨어 RAID 워크플로우 제한 사항이 있습니다. 자세한 내용은 다음 기술 자료 문서를 참조하십시오:

* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4020["CDEPLOY-4020: ONTAP Select Deploy: RHEL 10 및 ROCKY 10을 사용하여 클러스터 HWR을 생성하는 동안 경고 메시지가 표시됩니다."^]
* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4025["CDEPLOY-4025: ONTAP Select DeployGUI: RHEL10/Rocky 10이 설치된 호스트의 클러스터 생성 페이지에서 SWR에 스토리지 풀 및 스토리지 디스크가 표시되지 않음"^]




2+| 관리 소프트웨어 3+| NetApp Active IQ Unified Manager 관리 제품군 ONTAP Select Deploy Utility SnapCenter(선택 사항) 
|===
--
====
.다음은 무엇인가요?
link:concept_lic_workflow.html["ONTAP Select 라이센스 구매에 대해 알아보십시오"]
