---
sidebar: sidebar 
permalink: concept_vpi_vcenter_integration.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, vcenter integration 
summary: Deploy 플러그인은 vCenter Server와 긴밀하게 통합되어 있습니다. 이러한 통합을 통해 Deploy 유틸리티 및 vCenter Server에서 관리하는 리소스를 쉽게 탐색할 수 있습니다. 이러한 통합의 몇 가지 예가 아래에 나와 있습니다. 
---
= 플러그인과 vCenter의 통합 구축
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Deploy 플러그인은 vCenter Server와 긴밀하게 통합되어 있습니다. 이러한 통합을 통해 Deploy 유틸리티 및 vCenter Server에서 관리하는 리소스를 쉽게 탐색할 수 있습니다. 이러한 통합의 몇 가지 예가 아래에 나와 있습니다.



== ONTAP Select 클러스터에 할당된 VMware 리소스입니다

ONTAP Select 클러스터는 하나 이상의 노드 세트로 VMware에서 실행됩니다. 각 노드는 다른 ESXi 호스트의 전용 가상 머신입니다. ONTAP Select 클러스터는 다음 VMware 리소스와 연결됩니다.

* 호스트
* ONTAP VM입니다
* 데이터 저장소
* 네트워크


특정 ONTAP Select 클러스터에서 사용되는 VMware 리소스를 확인하는 방법에는 여러 가지가 있습니다.



== 플러그인을 통해 클러스터에 대한 VMware 리소스를 봅니다

Deploy 플러그인을 통해 ONTAP Select 클러스터에 할당된 VMware 리소스를 볼 수 있습니다.

.단계
. 브라우저를 사용하여 vSphere HTML5를 통해 vCenter Server에 로그인합니다.
. 글로벌 인벤토리 목록 * 창에서 * ONTAP Select 클러스터 * 를 클릭합니다.
. 오른쪽 목록에서 원하는 클러스터를 클릭합니다.
. More Objects * 탭을 클릭하고 페이지 상단에서 원하는 리소스 범주를 선택합니다.
. 특정 VMware 리소스를 선택하여 추가 정보를 표시합니다.




== ESXi 가상 머신을 통해 ONTAP Select 클러스터를 확인합니다

VMware 가상 시스템에 액세스하여 ONTAP Select 클러스터 및 관련 클러스터 리소스를 볼 수 있습니다.

.단계
. 브라우저를 사용하여 vSphere HTML5를 통해 vCenter Server에 로그인합니다.
. 맨 위에서 * 메뉴 * 를 클릭한 다음 * VM 및 템플릿 * 을 클릭합니다.
. 왼쪽 목록에서 원하는 가상 머신을 선택합니다.
. VM에서 실행 중인 ONTAP Select 클러스터를 보려면 * More Objects * 탭을 클릭합니다.
. 클러스터와 관련된 VMware 리소스의 전체 컬렉션을 보려면 ONTAP Select 클러스터를 클릭한 다음 * More Objects * 탭을 클릭합니다.




== ESXi 호스트에서 단일 노드 클러스터를 생성합니다

vSphere 인터페이스를 통해 ESXi 하이퍼바이저 호스트를 선택하고 ONTAP Select 단일 노드 클러스터를 구축할 수 있습니다.

.단계
. 브라우저를 사용하여 vSphere HTML5를 통해 vCenter Server에 로그인합니다.
. 맨 위에서 * 메뉴 * 를 클릭한 다음 * 호스트 및 클러스터 * 를 클릭합니다.
. 왼쪽에서 원하는 하이퍼바이저 호스트를 마우스 오른쪽 버튼으로 클릭하고 * ONTAP Select * 를 선택한 다음 * New ONTAP Select * 를 클릭합니다.
. 의 단계에 따라 배포 프로세스를 완료합니다 link:task_deploy_cluster.html["ONTAP Select 클러스터 구축"].

