---
sidebar: sidebar 
permalink: concept_usecase_overview.html 
keywords: ontap select, business use case overview, deployment, storage, development and testing 
summary: ONTAP Select는 하이퍼바이저 가상화를 통해 제공되는 고유의 유연성을 기반으로 여러 가지 유형의 애플리케이션에 적합합니다. 
---
= 비즈니스 요구 및 사용 시나리오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select는 하이퍼바이저 가상화를 통해 제공되는 고유의 유연성을 기반으로 여러 가지 유형의 애플리케이션에 적합합니다.



== 구축

상위 수준에서는 하이퍼바이저 호스트 서버의 작업 부하에 대해 두 가지 방법으로 ONTAP Select를 배포할 수 있습니다.



=== 전용 구축

전용 배포 모델에서는 ONTAP Select의 단일 인스턴스가 호스트 서버에서 실행됩니다. 동일한 하이퍼바이저 호스트에서 다른 중요한 프로세싱이 실행되고 있지 않습니다.



=== 코로케이션 구축

코로케이션 구축 모델을 통해 ONTAP Select는 호스트를 다른 워크로드와 공유합니다. 특히, 일반적으로 컴퓨팅 애플리케이션을 실행하는 추가 가상 시스템이 있습니다. 이러한 컴퓨팅 워크로드는 ONTAP Select 클러스터에 로컬입니다. 이 모델은 특수 애플리케이션 및 구축 요구사항을 지원합니다. 전용 구축 모델과 마찬가지로 각 ONTAP Select 가상 시스템은 별도의 전용 하이퍼바이저 호스트에서 실행되어야 합니다.



== 스토리지

ONTAP Select는 비즈니스 요구사항에 따라 운영 스토리지 또는 2차 스토리지로 사용할 수 있습니다.



=== 운영 스토리지

경우에 따라 ONTAP Select를 기본 스토리지 플랫폼으로 구축할 수 있습니다. 이러한 구현 유형은 애플리케이션의 워크로드 특성 및 비즈니스 목표에 따라 달라지며 달라질 수 있습니다.



=== 재해 복구 및 2차 스토리지

ONTAP Select를 사용하여 기본 스토리지 기능을 강화하는 추가 스토리지를 구현할 수 있습니다. 추가 스토리지는 조직의 재해 복구 노력과 데이터 백업 계획을 지원하는 데 사용할 수 있습니다.



== 개발 및 테스트

조직 내에 다양한 응용 프로그램을 배포할 때 ONTAP Select를 전체 응용 프로그램 개발 및 테스트 프로세스의 필수 요소로 사용할 수 있습니다. 예를 들어, 테스트 입력 또는 출력 데이터를 보관하려면 임시 저장소가 필요할 수 있습니다. 이러한 유형의 구축 시간은 애플리케이션 특성 및 요구사항에 따라 달라질 수 있습니다.
