---
sidebar: sidebar 
permalink: concept_automate_ansible.html 
keywords: ansible, automation, configuration management, ontap, ontap select, na_ots_deploy, na_ots_cluster, ansible roles, ansible playbook 
summary: Ansible 역할을 사용하여 ONTAP Select 구축을 자동화합니다. 
---
= Ansible을 사용하여 ONTAP Select 구축 자동화
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ansible 역할 및 플레이북을 사용하여 ONTAP Select 구축 자동화

Ansible 역할은 표준화된 파일 구조에 있는 작업, 템플릿, 처리기 및 변수의 논리적 모음입니다. 이러한 역할을 사용하여 독립적으로 사용할 수 있는 기능을 사용하고, 재사용하고, 모듈화합니다. 실행을 위해 플레이북에 역할 및 실행하려는 호스트 목록을 포함합니다. Ansible을 설치하고, 필요한 모듈을 업데이트하고, 플레이북을 이해한 후에는 NetApp GitHub에서 ONTAP Select(OTS) 역할을 다운로드하여 ONTAP Select 클러스터 배포를 위한 자체 플레이북을 만들고 실행할 수 있습니다.



== 역할

ONTAP Select에는 두 가지 역할을 사용할 수 있습니다.



=== NA_OTS_배포

이 역할은 ONTAP Select 구축을 위한 설치 파일을 vCenter 또는 ESXi 호스트에 다운로드합니다. 그런 다음 배포 VM을 생성하고 실행합니다.

이 역할은 다음과 같은 입력 값을 사용합니다.

* vCenter 또는 ESXi 호스트 자격 증명
* 다음과 같은 정보를 포함하여 VM 생성 배포:
+
** IP 주소입니다
** 호스트 이름입니다
** 로그인
** 암호
** 데이터 저장소
** 네트워크


* OVA 파일의 로컬 경로입니다
+
역할을 포함하여 플레이북을 실행하기 전에 설치 파일을 사용할 수 있는지 확인하십시오.)




NOTE: 이러한 입력 값을 제공하는 가장 간단한 방법은 YML 형식의 전역 변수 파일을 사용하는 것입니다. 이 YML 파일을 플레이북에 전달합니다.

이 역할에는 배포 OVA 파일을 호스트로 가져와서 VM을 생성하고 실행하는 단일 작업이 있습니다. 다음 NetApp Ansible GitHub에서 이 역할을 액세스하고 다운로드할 수 있습니다. link:https://github.com/netapp-automation/na_ots_deploy["NA_OTS_배포"^]



=== NA_OTS_클러스터

이 역할은 ONTAP Select 배포 API를 사용하여 ONTAP Select 클러스터를 생성하고 배포합니다. 배포 VM이 생성되었으며 수동으로 또는 * na_OTS_deploy * 역할을 사용하여 실행 중인 것으로 가정합니다. 또한 이 역할에서는 Select 호스트가 ONTAP Select 클러스터에 필요한 네트워킹 및 스토리지로 적절히 구성되어 있다고 가정합니다.

이 역할은 vCenter 또는 ESXi 자격 증명에 대한 입력 값을 사용하고, VM 자격 증명을 구축하여 API와 ONTAP Select 클러스터 및 노드 VM을 생성하는 데 필요한 모든 관련 정보를 액세스합니다.

역할은 다음 작업을 수행합니다.

* 호스트 자격 증명 추가(vCenter 또는 ESXi
* 호스트 ID 가져오기 및 등록
* 내부 네트워크 검증(다중 노드 클러스터의 경우)
* 클러스터 생성
* 노드 구성
* 네트워크 및 스토리지 풀 구성
* 클러스터 구축


결과적으로 클러스터 VM이 가동되고 ONTAP Select 클러스터가 완전히 배포되면 역할이 완료됩니다. 다음 NetApp Ansible GitHub에서 이 역할을 액세스하고 다운로드할 수 있습니다. link:https://github.com/NetApp-Automation/na_ots_cluster["NA_OTS_클러스터"^]



== 플레이북 예

다음은 이러한 두 가지 ONTAP Select 역할을 수행하는 플레이북 예입니다. 입력 변수는 YML 파일에서 정의되며 "VAR_FILES"를 통해 전달됩니다. 각 역할의 README 파일에서 자세한 내용을 확인할 수 있습니다.

[listing]
----
—

– name: Create ONTAP Select deploy from OVA (ESXi)

vars_files:

– vars_deploy.yml                              # All Variables

– vars_deploy_pwd.yml                          # host_password & deploy_password

hosts: “{{ target_vcenter_or_esxi_host }}”     # Entry in Ansible ‘hosts’ file

gather_facts: false

connection: ‘local’

roles:

– na_ots_deploy

– name: Create ONTAP Select Cluster

vars_files:

– vars_cluster_test.yml

– vars_cluster_pwd.yml

hosts: “localhost”

gather_facts: false

roles:

– na_ots_cluster

----
위 역할을 사용하여 ONTAP Select 클러스터를 생성하고 실행한 후, ONTAP 기능을 더욱 자동화하는 데 사용할 수 있는 다양한 ONTAP Ansible 역할을 활용할 수 있습니다. 사용 가능한 ONTAP 역할에 액세스할 수 있습니다 link:https://github.com/NetApp/ansible["여기"]. 요약하면, ONTAP Select Ansible 역할과 ONTAP 역할을 함께 사용하면 엔드-투-엔드 워크플로우를 완벽하게 자동화하여 ONTAP Select을 통해 스토리지를 관리할 수 있습니다.
