---
sidebar: sidebar 
permalink: concept_lic_platforms.html 
keywords: license, licensing, platform license offerings, license offerings, standard, premium, premium xl 
summary: ONTAP Select 용량 계층 또는 용량 풀 라이센스를 3가지 플랫폼 용량 수준 중 하나로 구입할 수 있습니다. 이러한 라이센스 오퍼링은 ONTAP Select를 구축하는 호스트의 기능을 결정합니다. 
---
= 플랫폼 라이센스 제공 사항을 이해합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 용량 계층 또는 용량 풀 라이센스를 3가지 플랫폼 용량 수준 중 하나로 구입할 수 있습니다. 이러한 라이센스 오퍼링은 ONTAP Select를 구축하는 호스트의 기능을 결정합니다.



== 플랫폼 라이센스 제공 내용

특정 라이센스 오퍼링은 다음 두 가지 영역에서 하이퍼바이저 호스트의 기능을 정의하고 제한합니다.

* 인스턴스 유형(CPU, 메모리)
* 추가 기능


라이센스 서비스는 표준 XL에서 프리미엄 XL로 상향 조정되어 있습니다. 일반적으로 선택하는 라이센스 옵션은 해당 수준의 기능 및 모든 하위 수준을 부여합니다. 예를 들어, 프리미엄 레벨은 프리미엄 및 표준의 기능을 모두 제공합니다.



== 플랫폼 라이센스 제공

3가지 플랫폼 라이센스 오퍼링이 제공됩니다.



=== 표준

표준 오퍼링은 다음과 같은 기능을 제공합니다.

* 작은 인스턴스 유형만
* 하드 디스크 드라이브(HDD)만 해당
* 로컬 하드웨어 RAID 컨트롤러만 해당
* vNAS




=== 프리미엄

프리미엄 오퍼링은 다음과 같은 기능을 제공합니다.

* 소형 또는 중형 인스턴스 유형입니다
* 하드 디스크 드라이브(HDD) 또는 솔리드 스테이트 드라이브(SSD)
* 로컬 하드웨어 RAID 컨트롤러 또는 소프트웨어 RAID
* vNAS
* MetroCluster SDS




=== Premium XL

Premium XL 오퍼링은 다음과 같은 기능을 제공합니다.

* 소형, 중형 또는 대형 인스턴스 유형입니다.
* 하드 디스크 드라이브(HDD) 또는 솔리드 스테이트 드라이브(SSD)
* 로컬 하드웨어 RAID 컨트롤러 또는 소프트웨어 RAID
* vNAS
* MetroCluster SDS



NOTE: Premium XL 라이센스를 사용하는 대규모 인스턴스 유형은 VMware ESXi에서만 가능합니다.
