---
sidebar: sidebar 
permalink: concept_api_understanding_scripts.html 
keywords: rest api, deploy rest api, rest, python, python scripts, understanding 
summary: 샘플 Python 스크립트를 사용하여 여러 가지 작업을 수행할 수 있습니다. 라이브 배포 인스턴스에서 스크립트를 사용하기 전에 스크립트를 이해해야 합니다. 
---
= Python 스크립트를 이해합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
샘플 Python 스크립트를 사용하여 여러 가지 작업을 수행할 수 있습니다. 라이브 배포 인스턴스에서 스크립트를 사용하기 전에 스크립트를 이해해야 합니다.



== 공통된 설계 특성

스크립트는 다음과 같은 일반적인 특성을 사용하여 설계되었습니다.

* 클라이언트 시스템의 명령줄 인터페이스에서 실행 올바르게 구성된 모든 클라이언트 시스템에서 Python 스크립트를 실행할 수 있습니다. 자세한 내용은 시작하기 전에 _ 을(를) 참조하십시오.
* CLI 입력 매개 변수 허용 각 스크립트는 입력 매개 변수를 통해 CLI에서 제어됩니다.
* 입력 파일 읽기 각 스크립트는 용도에 따라 입력 파일을 읽습니다. 클러스터를 생성하거나 삭제할 때 JSON 구성 파일을 제공해야 합니다. 노드 라이센스를 추가할 때는 유효한 라이센스 파일을 제공해야 합니다.
* 공통 지원 모듈 사용 일반 지원 모듈_deploy_requests.py_contains 단일 클래스를 포함합니다. 각 스크립트에서 가져오고 사용합니다.




== 클러스터를 생성합니다

script cluster.py를 사용하여 ONTAP Select 클러스터를 생성할 수 있습니다. JSON 입력 파일의 CLI 매개 변수 및 콘텐츠를 기준으로 다음과 같이 스크립트를 배포 환경에 수정할 수 있습니다.

[NOTE]
====
* ONTAP Select 9.10.1부터는 KVM 하이퍼바이저에 새 클러스터를 더 이상 구축할 수 없습니다.
* ONTAP Select 9.11.1부터는 오프라인 및 삭제 기능을 제외한 모든 관리 기능을 기존 KVM 클러스터와 호스트에서 사용할 수 없습니다.


====
* 하이퍼바이저 배포 버전에 따라 ESXi 또는 KVM에 배포할 수 있습니다. ESXi에 배포할 때 vCenter에서 하이퍼바이저를 관리하거나 독립 실행형 호스트로 사용할 수 있습니다.
* 클러스터 크기 단일 노드 또는 다중 노드 클러스터를 구축할 수 있습니다.
* 평가판 또는 운영 라이센스 운영 라이센스 평가판 또는 구입한 라이센스가 있는 클러스터를 구축할 수 있습니다.


스크립트의 CLI 입력 매개 변수는 다음과 같습니다.

* 배포 서버의 호스트 이름 또는 IP 주소입니다
* admin 사용자 계정의 암호입니다
* JSON 구성 파일의 이름입니다
* 메시지 출력에 대한 자세한 정보 표시 플래그입니다




== 노드 라이센스를 추가합니다

운영 클러스터를 배포하려면 script_add_license.py_를 사용하여 각 노드에 대한 라이센스를 추가해야 합니다. 클러스터를 구축하기 전이나 후에 라이센스를 추가할 수 있습니다.

스크립트의 CLI 입력 매개 변수는 다음과 같습니다.

* 배포 서버의 호스트 이름 또는 IP 주소입니다
* admin 사용자 계정의 암호입니다
* 라이센스 파일의 이름입니다
* 라이센스를 추가할 수 있는 권한이 있는 ONTAP 사용자 이름입니다
* ONTAP 사용자의 암호입니다




== 클러스터를 삭제합니다

script_delete_cluster.py_를 사용하여 기존 ONTAP Select 클러스터를 삭제할 수 있습니다.

스크립트의 CLI 입력 매개 변수는 다음과 같습니다.

* 배포 서버의 호스트 이름 또는 IP 주소입니다
* admin 사용자 계정의 암호입니다
* JSON 구성 파일의 이름입니다

