---
sidebar: sidebar 
permalink: concept_adm_before.html 
keywords: administer, administering, web, before you begin 
summary: ONTAP Select 클러스터를 생성한 후 다양한 관리 작업을 수행하여 배포를 지원할 수 있습니다. 몇 가지 일반적인 고려 사항이 있습니다. 
---
= ONTAP Select 관리를 시작하기 전에
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 클러스터를 생성한 후 다양한 관리 작업을 수행하여 배포를 지원할 수 있습니다. 몇 가지 일반적인 고려 사항이 있습니다.

일반적으로 웹 인터페이스 배포 를 사용하여 수행할 수 있는 절차는 세 가지 범주 중 하나에 속합니다.

.ONTAP Select 클러스터 구축
단일 노드 또는 다중 노드 클러스터를 구축할 수 있습니다. 을 참조하십시오 link:task_deploy_cluster.html["ONTAP Select 클러스터 구축"] 를 참조하십시오.

.기존 ONTAP Select 클러스터에 대해 절차를 수행합니다
관리 절차는 _Security_ 및 _Clusters_ 같은 다양한 범주로 구성됩니다.

.배포 유틸리티에 대한 절차를 수행합니다
배포에는 관리자 암호 변경과 같은 몇 가지 절차가 있습니다.



== ONTAP Select 관리

ONTAP Select 지원의 일환으로 다양한 관리 절차를 사용할 수 있습니다. 또한 배포 관리 유틸리티에만 적용되는 절차가 있습니다. 이 절차의 가장 중요한 내용은 다음과 같습니다. 일반적으로 배포 웹 사용자 인터페이스를 사용합니다.


NOTE: 또한 가능합니다 link:https://docs.netapp.com/us-en/ontap-select/task_cli_signing_in.html["명령줄 인터페이스를 사용합니다"] ONTAP Select를 관리합니다.



== 추가 ONTAP 구성을 수행합니다

ONTAP Select 클러스터를 구축한 후에는 하드웨어 기반 ONTAP 시스템과 마찬가지로 클러스터를 구성 및 관리할 수 있습니다. 예를 들어, ONTAP System Manager나 ONTAP CLI를 사용하여 ONTAP Select 클러스터를 구성할 수 있습니다.

.NetApp 클라이언트 소프트웨어
지원되는 다음 NetApp 클라이언트 소프트웨어를 사용하여 ONTAP Select에 연결할 수 있습니다.

* ONTAP 시스템 관리자
* Active IQ Unified Manager
* OnCommand Insight
* OnCommand Workflow Automation
* SnapCenter
* VMware vSphere용 Virtual Storage Console을 참조하십시오


지원되는 클라이언트 소프트웨어 버전을 확인하려면 을 참조하십시오 link:https://mysupport.netapp.com/matrix/["NetApp 상호 운용성 매트릭스 툴"^]. 클라이언트 소프트웨어가 ONTAP 9를 지원하는 경우 ONTAP Select에서도 동일한 버전이 지원됩니다.


NOTE: SnapCenter와 해당 플러그인을 사용하려면 서버 기반 라이센스가 필요합니다. SnapCenter 플러그인의 스토리지 시스템 라이센스는 현재 ONTAP Select에서 지원되지 않습니다.

목록에 없는 다른 NetApp 클라이언트 소프트웨어는 ONTAP Select에서 지원하지 않습니다.

.가능한 구성 옵션
클러스터를 구성할 때 다음과 같은 몇 가지 옵션을 사용할 수 있습니다.

* 네트워킹 구성 생성
* 집계 레이아웃
* 데이터 스토리지 VM(SVM) 생성


.스토리지 용량이 포함된 라이센스를 구입했습니다
ONTAP Select 클러스터 구축의 일부로 스토리지 용량이 있는 라이센스 파일을 설치하지 않기로 결정한 경우, 구매한 라이센스로 실행 중인 클러스터의 유예 기간이 만료되기 전에 라이센스 파일을 구입하여 설치해야 합니다.

.미러링된 애그리게이트
Deploy 관리 유틸리티에서 생성된 데이터 스페어 디스크가 사용 가능한 데이터 저장소 공간(예: pool0 및 Pool1)의 각 ONTAP Select 노드에 있습니다. 다중 노드 클러스터에서 데이터에 대한 고가용성을 구현하려면 이러한 스페어를 사용하여 미러링된 애그리게이트를 만들어야 합니다.
