---
sidebar: sidebar 
permalink: concept_adm_upgrading_nodes.html 
keywords: administer, administering, web, upgrading nodes 
summary: ONTAP Select 클러스터를 구축한 후 표준 ONTAP 소프트웨어 업그레이드 절차를 사용하여 필요에 따라 각 노드의 ONTAP 이미지를 업그레이드할 수 있습니다. 
---
= ONTAP Select 노드를 업그레이드합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 클러스터를 구축한 후 필요에 따라 클러스터의 각 노드에서 ONTAP 이미지를 업그레이드할 수 있습니다.


CAUTION: 배포 관리 유틸리티를 사용하여 기존 ONTAP Select 노드의 업그레이드를 수행할 수 없습니다. Deploy 유틸리티는 새 ONTAP Select 클러스터를 생성하는 데만 사용할 수 있습니다.



== 일반 절차

높은 수준에서 기존 ONTAP Select 노드를 업그레이드하려면 다음 단계를 수행해야 합니다.

. NetApp Support 사이트에서 다운로드 페이지로 이동합니다.
+
https://mysupport.netapp.com/site/downloads["NetApp 지원 다운로드"^]

. ONTAP Select 노드 업그레이드 * 를 클릭합니다.
. 필요에 따라 모든 프롬프트에 응답하는 적절한 업그레이드 이미지를 선택하여 다운로드합니다.
+
ONTAP Select 노드를 업그레이드하기 전에 추가 정보 및 필요한 절차는 릴리즈 노트를 참조하십시오.

. ONTAP Select 업그레이드 파일과 함께 표준 ONTAP 업그레이드 절차를 사용하여 ONTAP Select 노드를 업그레이드합니다.
+
link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["ONTAP 업그레이드 개요"^]





== ONTAP Select 노드를 되돌립니다

ONTAP Select 노드를 원래 설치된 이전 버전으로 되돌릴 수 없습니다. 예를 들면 다음과 같습니다.

ONTAP Select 9.7이 처음 설치됩니다:: 노드를 버전 9.8로 업그레이드한 다음 필요한 경우 버전 9.7로 되돌릴 수 있습니다.
처음에 ONTAP Select 9.8이 설치되어 있습니다:: 이 버전은 원래 설치된 버전 이전의 버전이므로 버전 9.7로 되돌릴 수 없습니다.




== VMXNET3 네트워크 드라이버를 사용합니다

VMXNET3은 VMware ESXi의 새 클러스터 구축에 포함된 기본 네트워크 드라이버입니다. ONTAP Select 9.4 이하 버전을 실행하는 기존 ONTAP Select 노드를 업그레이드하는 경우 네트워크 드라이버가 자동으로 업그레이드되지 않습니다. VMXNET3으로 수동으로 업그레이드해야 합니다. 업그레이드에 대한 지원은 NetApp 지원에 문의하십시오.
