---
sidebar: sidebar 
permalink: concept_lic_cp_restrictions.html 
keywords: license, licensing, capacity pools, restrictions 
summary: 용량 풀 라이센스 모델을 사용할 때 적용되는 제한 사항은 다음과 같습니다. 
---
= 용량 풀 라이센스에 대한 구축 제한
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
용량 풀 라이센스 모델을 사용할 때 적용되는 제한 사항은 다음과 같습니다.

.클러스터당 일관된 라이센스 모델
단일 ONTAP Select 클러스터 내의 모든 노드는 용량 계층 또는 용량 풀과 같은 라이센스 모델을 사용해야 합니다. 단일 클러스터 내에서 노드의 라이센스 유형을 혼합할 수 없습니다.

.클러스터의 모든 노드는 동일한 License Manager 인스턴스를 사용합니다
ONTAP Select 클러스터에 용량 풀 라이센스가 있는 모든 노드는 동일한 라이센스 관리자 인스턴스를 사용해야 합니다. 각 배포 인스턴스 내에 License Manager 인스턴스가 하나이므로 이 제한은 클러스터의 모든 노드가 동일한 배포 인스턴스를 통해 관리되어야 한다는 기존 요구 사항을 다시 기술합니다.

.노드당 1개의 용량 풀
각 노드는 정확히 하나의 용량 풀에서 스토리지를 임대할 수 있습니다. 노드는 두 개 이상의 풀을 사용할 수 없습니다.

.HA Pair의 노드에 대한 동일한 풀입니다
단일 HA 쌍의 두 노드는 동일한 용량 풀의 스토리지를 임대해야 합니다. 그러나 동일한 클러스터 내의 HA 쌍이 다르면 동일한 License Manager에서 관리하는 다른 풀의 스토리지를 임대할 수 있습니다.

.스토리지 라이센스 기간
NetApp에서 스토리지 라이센스를 구입하는 경우 라이센스 기간을 선택해야 합니다. 예를 들어, 라이센스는 1년 동안 유효합니다.

.데이터 애그리게이트 임대 기간
ONTAP Select 노드가 데이터 집계를 위한 스토리지 임대를 요청하는 경우 License Manager는 용량 풀 구성에 따라 특정 기간 동안 임대를 제공합니다. 각 풀의 임대 기간은 1시간에서 7일 사이로 구성할 수 있습니다. 기본 임대 기간은 24시간입니다.

.배포에 할당된 정적 IP 주소입니다
용량 풀 라이센스가 사용되는 경우 배포 관리 유틸리티에 정적 IP 주소를 할당해야 합니다.
