---
sidebar: sidebar 
permalink: concept_nw_internal_external.html 
keywords: ontap select, internal network, external network 
summary: 내부 및 외부 ONTAP Select 네트워크의 특성 
---
= ONTAP Select 내부 및 외부 네트워크
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 내부 및 외부 네트워크의 특성



== ONTAP Select 내부 네트워크

제품의 다중 노드 버전에만 있는 내부 ONTAP Select 네트워크는 클러스터 통신, HA 인터커넥트 및 동기식 복제 서비스를 통해 ONTAP Select 클러스터를 제공하는 역할을 합니다. 이 네트워크에는 다음과 같은 포트와 인터페이스가 포함되어 있습니다.

* * e0c, e0d. * 클러스터 네트워크 LIF 호스팅
* * e0e. * RSM LIF 호스팅
* * e0f. * HA 인터커넥트 LIF 호스팅


이 네트워크의 처리량과 대기 시간은 ONTAP Select 클러스터의 성능과 복원력을 결정하는 데 매우 중요합니다. 클러스터 보안을 위해 네트워크 격리가 필요하며 시스템 인터페이스가 다른 네트워크 트래픽과 분리되도록 해야 합니다. 따라서 이 네트워크는 ONTAP Select 클러스터에서만 사용해야 합니다.


NOTE: 애플리케이션 또는 관리 트래픽과 같이 클러스터 트래픽 선택 이외의 트래픽에 내부 네트워크 선택 을 사용하는 것은 지원되지 않습니다. ONTAP 내부 VLAN에 다른 VM 또는 호스트가 있을 수 없습니다.

내부 네트워크를 통과하는 네트워크 패킷은 전용 VLAN 태그 계층 2 네트워크에 있어야 합니다. 이 작업은 다음 작업 중 하나를 완료하여 수행할 수 있습니다.

* 내부 가상 NIC(e0c~e0f)에 VLAN 태그 지정된 포트 그룹 할당(VST 모드)
* 기본 VLAN이 다른 트래픽에 사용되지 않는 업스트림 스위치에서 제공하는 네이티브 VLAN 사용(VLAN ID가 없는 포트 그룹 할당, 즉 EST 모드)


모든 경우 내부 네트워크 트래픽에 대한 VLAN 태깅이 ONTAP Select VM 외부에서 수행됩니다.


NOTE: ESX 표준 및 분산형 vSwitch만 지원됩니다. 다른 가상 스위치 또는 ESX 호스트 간의 직접 연결은 지원되지 않습니다. 내부 네트워크를 완전히 열어야 합니다. NAT 또는 방화벽은 지원되지 않습니다.

ONTAP Select 클러스터 내에서 내부 트래픽과 외부 트래픽은 포트 그룹이라고 하는 가상 계층 2 네트워크 개체를 사용하여 분리됩니다. 이러한 포트 그룹의 적절한 vSwitch 할당은 특히 클러스터, HA 상호 연결 및 미러 복제 서비스를 제공하는 내부 네트워크의 경우 매우 중요합니다. 이러한 네트워크 포트에 대한 네트워크 대역폭이 부족하면 성능이 저하되고 클러스터 노드의 안정성에도 영향을 줄 수 있습니다. 따라서 4노드, 6노드 및 8노드 클러스터에는 내부 ONTAP Select 네트워크에서 10Gb 연결을 사용해야 하며, 1Gb NIC는 지원되지 않습니다. 그러나 수신되는 데이터의 흐름을 ONTAP Select 클러스터로 제한하더라도 안정적으로 운영할 수 있는 기능에는 영향을 미치지 않으므로 외부 네트워크에는 이러한 단점을 포함할 수 있습니다.

2노드 클러스터는 4노드 클러스터에 필요한 2개의 10Gb 포트 대신 내부 트래픽에 1Gb 포트 4개 또는 단일 10Gb 포트를 사용할 수 있습니다. 서버가 10Gb NIC 카드 4개에 맞지 않는 환경에서는 내부 네트워크에 10Gb NIC 카드 2개를 사용할 수 있고 외부 ONTAP 네트워크에 1Gb NIC 2개를 사용할 수 있습니다.



=== 내부 네트워크 검증 및 문제 해결

다중 노드 클러스터의 내부 네트워크는 네트워크 연결 검사기 기능을 사용하여 검증할 수 있습니다. Network connectivity -check start 명령을 실행하는 Deploy CLI에서 이 기능을 호출할 수 있다.

다음 명령을 실행하여 테스트 출력을 확인합니다.

[listing]
----
network connectivity-check show --run-id X (X is a number)
----
이 도구는 다중 노드 선택 클러스터의 내부 네트워크 문제를 해결하는 경우에만 유용합니다. 이 툴을 사용하여 단일 노드 클러스터(vNAS 구성 포함), ONTAP Deploy to ONTAP Select 접속 구성 또는 클라이언트측 연결 문제를 해결해서는 안 됩니다.

클러스터 생성 마법사(ONTAP 배포 GUI의 일부)에는 다중 노드 클러스터를 생성하는 동안 사용할 수 있는 선택적 단계로 내부 네트워크 검사기가 포함되어 있습니다. 다중 노드 클러스터에서 내부 네트워크가 수행하는 중요한 역할을 고려할 때 이 단계를 클러스터 생성 워크플로우의 일부로 사용하면 클러스터 생성 작업의 성공률이 향상됩니다.

ONTAP Deploy 2.10부터 내부 네트워크에서 사용되는 MTU 크기를 7,500에서 9,000으로 설정할 수 있습니다. 네트워크 연결 검사기는 MTU 크기를 7,500에서 9,000까지 테스트하는 데도 사용할 수 있습니다. 기본 MTU 값은 가상 네트워크 스위치의 값으로 설정됩니다. 환경에 VXLAN과 같은 네트워크 오버레이가 있는 경우 이 기본값은 더 작은 값으로 대체되어야 합니다.



== ONTAP Select 외부 네트워크

ONTAP Select 외부 네트워크는 클러스터의 모든 아웃바운드 통신을 담당하므로 단일 노드 및 다중 노드 구성 모두에 존재합니다. 이 네트워크에는 내부 네트워크의 엄격한 처리량 요구 사항이 없지만 성능 문제가 ONTAP Select 문제로 잘못 규정될 수 있으므로 관리자는 클라이언트와 ONTAP VM 사이에 네트워크 병목 현상이 발생하지 않도록 주의해야 합니다.


NOTE: 내부 트래픽과 유사한 방식으로 외부 트래픽은 vSwitch 계층(VST) 및 외부 스위치 계층(EST)에서 태깅될 수 있습니다. 또한, 외부 트래픽은 VGT라는 프로세스에서 ONTAP Select VM 자체에 의해 태깅될 수 있습니다. 섹션을 참조하십시오 link:concept_nw_data_mgmt_separation.html["데이터 및 관리 트래픽 분리"] 를 참조하십시오.

다음 표에서는 ONTAP Select 내부 및 외부 네트워크의 주요 차이점을 보여 줍니다.

* 내부 및 외부 네트워크 빠른 참조 *

[cols="3*"]
|===
| 설명 | 내부 네트워크 | 외부 네트워크 


| 네트워크 서비스 | 클러스터 HA/IC RAID SyncMirror(RSM) | 클러스터 간 데이터 관리(SnapMirror 및 SnapVault) 


| 네트워크 격리 | 필수 요소입니다 | 선택 사항 


| 프레임 크기(MTU) | 7,500에서 9,000까지 | 1,500(기본값) 9,000(지원) 


| IP 주소 할당 | 자동 생성됩니다 | 사용자 정의 


| DHCP 지원 | 아니요 | 아니요 
|===


=== NIC 팀 구성

내부 및 외부 네트워크에 고성능 및 내결함성을 제공하는 데 필요한 대역폭 및 복원력 특성이 모두 있는지 확인하려면 물리적 네트워크 어댑터 팀 구성을 사용하는 것이 좋습니다. 단일 10Gb 링크를 통한 2노드 클러스터 구성이 지원됩니다. 그러나 NetApp에서는 ONTAP Select 클러스터의 내부 및 외부 네트워크에서 NIC 팀 구성을 사용하는 것이 좋습니다.



=== MAC 주소 생성

모든 ONTAP Select 네트워크 포트에 할당된 MAC 주소는 포함된 배포 유틸리티에 의해 자동으로 생성됩니다. 이 유틸리티는 NetApp과 관련된 플랫폼별 OUI(Unique Identifier)를 사용하여 FAS 시스템과 충돌하지 않도록 합니다. 그런 다음 이 주소의 복사본을 ONTAP Select 설치 VM(ONTAP 배포) 내의 내부 데이터베이스에 저장하여 향후 노드 배포 시 실수로 재할당되지 않도록 합니다. 어떤 시점에서도 관리자는 네트워크 포트의 할당된 MAC 주소를 수정하지 않아야 합니다.
