---
sidebar: sidebar 
permalink: concept_vpi_planning.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, planning 
summary: Deploy vCenter 플러그인을 설치 및 사용하기 전에 성공을 보장할 준비를 해야 합니다. 
---
= Deploy vCenter Plug-in 사용 계획
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Deploy vCenter 플러그인을 설치 및 사용하기 전에 성공을 보장할 준비를 해야 합니다.



== 소프트웨어 요구 사항

다음 표에 설명된 대로 몇 가지 소프트웨어 요구 사항을 고려해야 합니다.

[cols="35,65"]
|===
| 소프트웨어 | 지원되는 버전입니다 


| ONTAP Select 배포 유틸리티 | 2.11.2 이상 


| VMware vSphere를 참조하십시오 | 6.5 GA 이상 


| VMware vSphere 사용자 인터페이스 | HTML5(Flash 기반 버전은 지원되지 않음) 


| ESXi | 6.5U2 이상 
|===


== 클러스터 크기 제한

다음 표에 설명된 대로 클러스터 크기와 관련하여 몇 가지 제한 사항을 고려해야 합니다.

[cols="35,65"]
|===
| 항목 | 최대 지원 


| ONTAP Select는 클러스터를 구축합니다 | 100 


| 노드(가상 머신) | 1000입니다 


| 호스트 | 800 
|===


== vCenter 사용자 계정에 대한 RBAC 권한

플러그인을 관리하고 액세스하려면 여러 가지 vCenter 권한이 필요합니다. 이러한 권한은 다음 세 가지 범주의 작업에 해당합니다.

* 배포를 통한 플러그인 관리:
+
** 설치합니다
** 업그레이드
** 제거


* vSphere Client를 통해 플러그인에 액세스
* vSphere를 통해 플러그인에 대한 사용자 액세스 권한 검증


을 참조하십시오 link:concept_vpi_manage_before.html#preparing-the-vcenter-server-accounts["vCenter Server 계정 준비"] 를 참조하십시오.



== AutoSupport 제한 사항

Deploy vCenter 플러그인은 ploy administration utility(플러그인 URL 포함)에서 최소한의 사용 정보를 제공합니다. 그러나 AutoSupport에는 AutoSupport 뷰어를 통해 표시할 수 있는 설치된 플러그인 테이블이 포함되어 있습니다.


NOTE: Deploy 플러그인을 사용하여 vSphere 웹 클라이언트를 통해 AutoSupport 패키지를 다운로드할 수 없습니다. 기본 배포 인터페이스를 사용하여 AutoSupport 패키지를 다운로드해야 합니다.



== 추가 제한

vCenter 배포 플러그인을 설치 및 사용하기 전에 다음과 같은 몇 가지 추가 제한 사항을 고려해야 합니다.

* vCenter 플러그인의 각 인스턴스는 vCenter Server를 하나만 지원합니다.
* 연결 모드로 구성된 vCenter 서버는 지원되지 않습니다.
* vSphere의 Deploy plug-in GUI는 동일한 vCenter Server에서 관리되는 ONTAP Select 가상 머신이 있는 클러스터만 표시합니다. 독립 실행형 ESXi 및 KVM 호스트에서 실행되는 ONTAP Select 클러스터는 포함되지 않습니다.

