---
sidebar: sidebar 
permalink: concept_api_operation.html 
keywords: rest api, deploy rest api, rest, operation, basic operation 
summary: REST는 일반적인 기술과 모범 사례를 설정하지만 각 API의 세부 사항은 설계 선택에 따라 달라질 수 있습니다. API를 사용하기 전에 ONTAP Select 배포 API의 세부 정보와 운영 특성을 알고 있어야 합니다. 
---
= ONTAP Select Deploy API 기본 운영 특성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
REST는 일반적인 기술과 모범 사례를 설정하지만 각 API의 세부 사항은 설계 선택에 따라 달라질 수 있습니다. API를 사용하기 전에 ONTAP Select 배포 API의 세부 정보와 운영 특성을 알고 있어야 합니다.



== 하이퍼바이저 호스트와 ONTAP Select 노드 비교

h하이퍼바이저 host_는 ONTAP Select 가상 머신을 호스팅하는 핵심 하드웨어 플랫폼입니다. ONTAP Select 가상 머신을 하이퍼바이저 호스트에 구축하고 활성화하면 가상 머신이 _ONTAP Select node_로 간주됩니다. Deploy REST API의 버전 3에서는 호스트 및 노드 객체가 구분되고 구분됩니다. 따라서 일대다 관계가 허용되며, 이 경우 하나 이상의 ONTAP Select 노드가 동일한 하이퍼바이저 호스트에서 실행될 수 있습니다.



== 오브젝트 식별자

각 리소스 인스턴스 또는 개체는 만들 때 고유한 식별자가 할당됩니다. 이러한 식별자는 ONTAP Select 배포의 특정 인스턴스 내에서 전역적으로 고유합니다. 새 개체 인스턴스를 만드는 API 호출을 실행하면 관련 ID 값이 HTTP 응답의 "위치" 헤더에서 호출자에게 반환됩니다. 식별자를 추출하여 리소스 인스턴스를 참조할 때 후속 호출에 사용할 수 있습니다.


NOTE: 개체 식별자의 내용 및 내부 구조는 언제든지 변경할 수 있습니다. 관련 객체를 참조할 때는 필요한 경우 해당 API 호출에서만 식별자를 사용해야 합니다.



== 요청 식별자

성공한 모든 API 요청에는 고유 식별자가 할당됩니다. ID는 연결된 HTTP 응답의 "quest-id" 헤더에서 반환됩니다. 요청 식별자를 사용하여 단일 특정 API 요청 응답 트랜잭션의 활동을 종합적으로 참조할 수 있습니다. 예를 들어 요청 ID를 기반으로 트랜잭션에 대한 모든 이벤트 메시지를 검색할 수 있습니다



== 동기 및 비동기 호출

서버에서 클라이언트로부터 받은 HTTP 요청을 수행하는 방법에는 두 가지가 있습니다.

* Synchronous 서버는 요청을 즉시 수행하고 상태 코드 200, 201 또는 204로 응답합니다.
* 비동기 서버는 요청을 수락하고 상태 코드 202로 응답합니다. 서버가 클라이언트 요청을 수락하고 요청을 완료하기 위해 백그라운드 작업을 시작했음을 나타냅니다. 최종 성공 또는 실패는 즉시 사용할 수 없으며 추가 API 호출을 통해 결정되어야 합니다.




== 장기 실행 작업의 완료를 확인합니다

일반적으로 완료하는 데 시간이 오래 걸릴 수 있는 작업은 서버의 백그라운드 작업을 사용하여 비동기적으로 처리됩니다. Deploy REST API를 사용하면 모든 백그라운드 작업이 작업을 추적하고 현재 상태와 같은 정보를 제공하는 Job 객체에 의해 고정됩니다. 백그라운드 작업이 생성된 후 고유 식별자를 포함한 작업 객체가 HTTP 응답에 반환됩니다.

Job 객체를 직접 쿼리하여 연결된 API 호출의 성공 또는 실패를 확인할 수 있습니다. 자세한 내용은 작업 객체를 사용한 _ 비동기 처리를 참조하십시오.

작업 객체를 사용하는 것 외에도 요청의 성공 또는 실패를 확인할 수 있는 다른 방법이 있습니다.

* 이벤트 메시지 원래 응답과 함께 반환된 요청 ID를 사용하여 특정 API 호출과 관련된 모든 이벤트 메시지를 검색할 수 있습니다. 이벤트 메시지는 일반적으로 성공 또는 실패를 나타내는 것으로, 오류 조건을 디버깅할 때 유용할 수 있습니다.
* 자원 상태 또는 상태 일부 자원에서는 요청의 성공 또는 실패를 간접적으로 확인할 수 있도록 쿼리할 수 있는 상태 또는 상태 값을 유지합니다.




== 보안

배포 API는 다음과 같은 보안 기술을 사용합니다.

* 전송 계층 보안 배포 서버와 클라이언트 간에 네트워크를 통해 전송되는 모든 트래픽은 TLS를 통해 암호화됩니다. 암호화되지 않은 채널을 통한 HTTP 프로토콜 사용은 지원되지 않습니다. TLS 버전 1.2가 지원됩니다.
* HTTP 인증 기본 인증은 모든 API 트랜잭션에 사용됩니다. base64 문자열에 사용자 이름과 암호를 포함하는 HTTP 헤더가 모든 요청에 추가됩니다.

