---
sidebar: sidebar 
permalink: concept_vpi_manage_before.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, manage, managing 
summary: Deploy vCenter 플러그인을 설치 및 관리하려면 몇 가지 작업을 수행해야 합니다. 
---
= 시작하기 전에
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Deploy vCenter 플러그인을 설치 및 관리하려면 몇 가지 작업을 수행해야 합니다.



== 웹 사용자 인터페이스 배포 또는 CLI 사용 여부 결정

대부분의 경우 Deploy 웹 사용자 인터페이스는 vCenter 플러그인을 관리할 때 가장 편리한 옵션을 제공하며, 이 옵션은 이 가이드에 설명되어 있습니다. 그러나 배포 명령줄 인터페이스를 사용하여 플러그인을 관리할 수도 있습니다. 자세한 내용은 CLI 배포 프롬프트에서 다음 명령을 입력합니다.

* 플러그인 배포? (하위 명령에는 설치, 제거, 표시 및 업데이트가 포함됩니다.)
* 플러그인-패키지 쇼(deeploy plugin-packages show)




== 모든 관리 작업에 공통적인 준비 사항

관리 작업에 관계없이 몇 가지 단계를 수행해야 합니다. 일반적인 준비에는 다음이 포함됩니다.

* vCenter 배포 플러그인에 익숙해지기 시작 섹션을 참조하십시오.
* ONTAP Select 배포 관리 유틸리티가 설치되어 실행되고 있는지 확인합니다. 자세한 내용은 VMware의 설치 및 클러스터 구축 가이드 를 참조하십시오.
* 계정 자격 증명 취득:
+
** 관리자 계정 배포
** vCenter Server 계정


* Deploy 유틸리티에서 vCenter Server의 포트 443에 대한 네트워크 액세스를 허용합니다.


관리 작업에 따라 추가 준비가 필요할 수 있습니다.



== vCenter Server 계정 준비

Deploy 플러그인을 설치 및 사용하기 전에 필요한 권한이 있는 vCenter 계정을 생성해야 합니다. 필요한 모든 권한이 있는 단일 계정을 만들거나 각 계정을 하나의 권한으로 여러 계정을 만들 수 있습니다. 다음 예에서는 간편하게 vCenter 권한을 세 개의 개별 역할에 분산하고, 이 역할을 세 개의 해당 계정에 할당할 수 있습니다.



==== 플러그인에 대한 최종 사용자 액세스를 검증하는 중입니다

vSphere를 통해 플러그인에 대한 액세스를 검증하는 계정이 필요합니다. 계정에는 다음 vCenter 권한이 있어야 합니다. sessions.validate.session. vCenter에서 계정을 생성한 후에는 해당 계정을 Deploy 관리 유틸리티에 정의해야 합니다. Deploy 웹 사용자 인터페이스에서 Administration 탭과 Credentials를 차례로 클릭하여 vCenter Server 위치 및 자격 증명을 제공합니다.

이 계정은 다음과 같은 방법으로 사용됩니다.

* 명명된 vCenter Server는 플러그인 등록 대화 상자 창에서 설치 타겟으로 사용할 수 있게 됩니다.
* 이 계정은 구축이 플러그인을 설치한 후 vSphere 사용자 요청의 플러그 인 액세스 여부를 검증하는 데 사용됩니다.




==== 플러그인 관리

Deploy 웹 사용자 인터페이스에서 플러그인을 설치한 다음 업그레이드하거나 제거할 수 있습니다. 이러한 관리 작업 중 하나를 수행할 때마다 팝업 창에 vCenter 계정을 묻는 메시지가 표시됩니다. 각 관리 작업은 별도의 vCenter 권한을 통해 제어됩니다.

플러그인을 설치, 업그레이드 및 제거하려면 다음 권한을 할당해야 합니다.

* 연장
+
** 내선 번호를 등록합니다
** 내선 번호 업데이트
** 내선 번호 등록을 취소합니다




세 가지 권한이 모두 있는 단일 역할 및 계정을 만들거나 필요에 따라 여러 계정 간에 권한을 나눌 수 있습니다.



==== 플러그인에 액세스 중입니다

최종 사용자는 vSphere를 통해 플러그인에 액세스할 수 있습니다. 플러그인을 사용할 계정에 다음 권한을 할당해야 합니다.

* 넷엡
+
** ONTAP Select 구축
+
*** 관리자





