---
sidebar: sidebar 
permalink: concept_lic_cp_operation.html 
keywords: license, licensing, capacity pools, operation details 
summary: 용량 풀 라이센스 모델은 용량 계층 모델과 다릅니다. 각 개별 노드에 전용 스토리지 용량을 할당하는 대신 스토리지 용량을 풀에 할당하여 여러 노드 간에 공유합니다. 용량 풀 모델을 지원하기 위해 추가 구성 요소 및 프로세스가 생성되었습니다. 
---
= 운영 세부 정보
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
용량 풀 라이센스 모델은 용량 계층 모델과 다릅니다. 각 개별 노드에 전용 스토리지 용량을 할당하는 대신 스토리지 용량을 풀에 할당하여 여러 노드 간에 공유합니다. 용량 풀 모델을 지원하기 위해 추가 구성 요소 및 프로세스가 생성되었습니다.



== License Manager를 클릭합니다

License Manager는 배포 관리 유틸리티의 각 인스턴스 내에서 별도의 프로세스로 실행됩니다. LM에서 제공하는 기능 중 일부는 다음과 같습니다.

* 용량 풀 라이센스 일련 번호를 기준으로 각 노드에 대해 고유한 20자리 일련 번호를 생성합니다
* ONTAP Select 노드의 요청에 따라 공유 용량 풀에서 용량 리스를 생성합니다
* 배포 사용자 인터페이스를 통해 풀 사용 정보를 보고합니다




== 임대 특성

용량 풀 라이센스를 사용하여 노드의 모든 데이터 애그리게이트에 대해 할당된 스토리지에는 관련 임대가 있어야 합니다. 노드가 스토리지 임대를 요청하고 사용 가능한 용량이 있는 경우 License Manager가 리스로 응답합니다. 각 임차에는 다음과 같은 명시적 또는 암시적 특성이 있습니다.

* License Manager 모든 ONTAP Select 노드는 하나의 License Manager 인스턴스와 연결됩니다
* 용량 풀 모든 ONTAP Select 노드는 하나의 용량 풀에 연결됩니다
* 스토리지 할당 특정 용량 값이 리스에 할당됩니다
* 만료 날짜 및 시간 임대 기간은 사용자 구성에 따라 1시간에서 7일 사이입니다.




== 라이센스 잠금 ID입니다

License Manager의 각 인스턴스 및 해당하는 각 배포 유틸리티 인스턴스는 고유한 128비트 숫자로 식별됩니다. 이 번호는 9자리 용량 풀 라이센스 일련 번호와 결합되어 풀을 특정 License Manager 인스턴스(실제로 배포 인스턴스)에 잠급니다. NLF(NetApp 라이센스 파일)를 생성하는 과정에서 NetApp Support 사이트에서 두 값을 모두 제공해야 합니다.

다음과 같은 방법으로 웹 사용자 인터페이스를 사용하여 배포 인스턴스의 라이센스 잠금 ID를 확인할 수 있습니다.

* 시작 페이지 배포를 위해 처음 로그인할 때 이 페이지가 표시됩니다. 페이지 오른쪽 상단의 드롭다운 상자를 클릭하고 시작하기 를 선택하여 페이지를 표시할 수도 있습니다. 라이센스 추가 섹션에 LLID가 표시됩니다.
* 관리 페이지 맨 위에 있는 * 관리 * 탭을 클릭한 다음 * 시스템 * 및 * 설정 * 을 클릭합니다.




== 기본 리스 작업

ONTAP Select 노드는 데이터 애그리게이스가 생성, 확장 또는 변경될 때마다 유효한 용량 리스를 찾거나 요청해야 합니다. 여전히 유효한 이전 요청에서 얻은 임대를 사용하거나 필요한 경우 새 임대를 요청할 수 있습니다. ONTAP Select 노드에서 용량 풀 리스를 찾으려면 다음 단계를 수행합니다.

. 기존 임대가 노드에 있는 경우 다음 조건이 모두 참이면 사용됩니다.
+
** 임대가 만료되지 않았습니다
** Aggregate에 대한 스토리지 요청이 리스 용량을 초과하지 않습니다


. 기존 임대를 찾을 수 없는 경우 노드는 License Manager로부터 새 임대를 요청합니다.




== 용량 풀에 스토리지 용량을 반환합니다

필요에 따라 용량 풀에서 스토리지 용량이 할당되며, 새로운 요청이 있을 때마다 풀에서 사용 가능한 스토리지가 줄어들 수 있습니다. 스토리지 용량은 다음과 같은 몇 가지 상황에서 풀로 반환됩니다.

* 데이터 애그리게이트의 임대가 만료되며 노드에 의해 갱신되지 않습니다
* 데이터 애그리게이트는 삭제됩니다



NOTE: ONTAP Select 가상 머신을 삭제하면 활성 임대가 만료될 때까지 그대로 유지됩니다. 이 경우 용량이 풀로 반환됩니다.
