---
sidebar: sidebar 
permalink: concept_stor_eff_support.html 
keywords: ontap select, storage efficiency support 
summary: ONTAP Select는 FAS 및 AFF 어레이에 제공되는 스토리지 효율성 옵션과 유사한 스토리지 효율성 옵션을 제공합니다. 
---
= 스토리지 효율성 지원
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select는 FAS 및 AFF 어레이에 제공되는 스토리지 효율성 옵션과 유사한 스토리지 효율성 옵션을 제공합니다.

All-Flash VSAN 또는 일반 플래시 스토리지를 사용하는 vNAS(ONTAP Select Virtual NAS) 구축은 비 SSD DAS 스토리지를 사용하는 ONTAP Select에 대한 Best Practice를 따라야 합니다.

SSD 드라이브와 프리미엄 라이센스가 포함된 DAS 스토리지가 있는 경우, AFF와 같은 퍼스낼리티가 새로운 설치에서 자동으로 활성화됩니다.

AFF와 같은 퍼스낼리티를 사용하면 설치 중에 다음 인라인 SE 기능이 자동으로 활성화됩니다.

* 인라인 제로 패턴 감지
* 볼륨 인라인 중복제거
* 볼륨 백그라운드 중복제거
* 적응형 인라인 압축
* 인라인 데이터 컴팩션
* 애그리게이트 인라인 중복제거
* 집계 백그라운드 중복 제거


ONTAP Select이 기본 스토리지 효율성 정책을 모두 사용하도록 설정했는지 확인하려면 새로 생성한 볼륨에서 다음 명령을 실행합니다.

[listing]
----
<system name>::> set diag
Warning: These diagnostic commands are for use by NetApp personnel only.
Do you want to continue? {y|n}: y
twonode95IP15::*> sis config
Vserver:                                SVM1
Volume:                                 _export1_NFS_volume
Schedule                                -
Policy:                                 auto
Compression:                            true
Inline Compression:                     true
Compression Type:                       adaptive
Application IO Si                       8K
Compression Algorithm:                  lzopro
Inline Dedupe:                          true
Data Compaction:                        true
Cross Volume Inline Deduplication:      true
Cross Volume Background Deduplication:  true
----

NOTE: 9.4에서 ONTAP Select를 업그레이드할 경우 프리미엄 라이센스를 사용하여 DAS SSD 스토리지에 ONTAP Select 9.4를 설치해야 합니다. 또한 ONTAP 배포를 통해 초기 클러스터를 설치하는 동안 * 스토리지 효율성 * 사용 확인란을 선택해야 합니다. 이전 조건이 충족되지 않은 경우 AFF와 같은 퍼스낼리티 사후 ONTAP 업그레이드를 활성화하려면 부팅 인수를 수동으로 생성하고 노드를 재부팅해야 합니다. 자세한 내용은 기술 지원 부서에 문의하십시오.

다음 표에는 ONTAP Select 버전 및 미디어 유형에 따라 사용 가능한 스토리지 효율성 옵션, 기본적으로 사용 가능 또는 기본적으로 사용 안 함, 권장 사항이 요약되어 있습니다.

[cols="6"]
|===
| ONTAP Select 기능 | 9.6/9.5 프리미엄 또는 프리미엄 XL^4^(DAS SSD) | 9.4^1^/9.3^2^프리미엄(DAS SSD) | 9.6/9.5/9.4^1^/9.3^2^모든 라이센스(DAS HDD) | 9.6 모든 라이센스(vNAS) | 9.5/9.4^1^/9.3^2^프리미엄 또는 표준(vNAS)^3^ 


| 인라인 제로 감지 | 예(기본값) | 예. 볼륨별로 사용자가 사용하도록 설정합니다 | 예. 볼륨별로 사용자가 사용하도록 설정합니다 | 예. 볼륨별로 사용자가 사용하도록 설정합니다 | 지원되지 않습니다 


| 볼륨 인라인 중복제거 | 예(기본값) | 예(권장) 볼륨별로 사용자가 사용하도록 설정합니다 | 사용할 수 없습니다 | 지원되지 않습니다 | 지원되지 않습니다 


| 32K 인라인 압축(보조 압축) | 예 볼륨 단위로 사용자가 사용합니다. | 예. 볼륨별로 사용자가 사용하도록 설정합니다 | 예. 볼륨별로 사용자가 사용하도록 설정합니다 | 지원되지 않습니다 | 지원되지 않습니다 


| 8K 인라인 압축(적응형 압축) | 예(기본값) | 예(권장) 볼륨별로 사용자가 사용하도록 설정합니다 | 예 볼륨 단위로 사용자가 사용합니다 | 지원되지 않습니다 | 지원되지 않습니다 


| 백그라운드 압축 | 지원되지 않습니다 | 지원되지 않습니다 | 예 볼륨 단위로 사용자가 사용합니다 | 예. 볼륨별로 사용자가 사용하도록 설정합니다 | 지원되지 않습니다 


| 압축 스캐너 | 예 | 예. 볼륨별로 사용자가 사용하도록 설정합니다 | 예 | 예. 볼륨별로 사용자가 사용하도록 설정합니다 | 지원되지 않습니다 


| 인라인 데이터 컴팩션 | 예(기본값) | 예(권장) 볼륨별로 사용자가 사용하도록 설정합니다 | 예 볼륨 단위로 사용자가 사용합니다 | 지원되지 않습니다 | 지원되지 않습니다 


| 다짐 스캐너 | 예 | 예. 볼륨별로 사용자가 사용하도록 설정합니다 | 예 | 지원되지 않습니다 | 지원되지 않습니다 


| 애그리게이트 인라인 중복제거 | 예(기본값) | 예(권장) 공간 보장이 없음인 볼륨별로 사용자에 의해 활성화됨 | 해당 없음 | 지원되지 않습니다 | 지원되지 않습니다 


| 볼륨 백그라운드 중복제거 | 예(기본값) | 예(권장) | 예 볼륨 단위로 사용자가 사용합니다 | 예. 볼륨별로 사용자가 사용하도록 설정합니다 | 지원되지 않습니다 


| 집계 백그라운드 중복 제거 | 예(기본값) | 예(권장) 공간 보장이 없음인 볼륨별로 사용자에 의해 활성화됨 | 해당 없음 | 지원되지 않습니다 | 지원되지 않습니다 
|===
[소규모]#^1^ONTAP Select 9.4(DAS SSD)(프리미엄 라이센스 필요)을 사용하면 Aggregate 수준의 배경 교차 볼륨 스캐너를 사용하여 Aggregate의 기존 데이터를 중복 제거할 수 있습니다. 이 일회성 작업은 9.4 이전에 생성된 볼륨에 대해 수동으로 수행됩니다.#[small]#^2^ONTAP DAS SSD에서 9.3 선택(프리미엄 라이센스 필요)은 애그리게이트 레벨의 백그라운드 중복제거를 지원합니다. 그러나 이 기능은 애그리게이트 생성 후 활성화해야 합니다.#[small]#^3^ONTAP Select 9.5 vNAS는 기본적으로 스토리지 효율성 정책을 지원하지 않습니다. SIDL(Single Instance Data Logging)에 대한 자세한 내용은 vNAS 섹션을 참조하십시오.#[Small]#^4^ONTAP Select 9.6은 새 라이센스(Premium XL)와 새 VM 크기(Large)를 지원합니다. 그러나 대규모 VM은 소프트웨어 RAID를 사용하는 DAS 구성에서만 지원됩니다. 현재 릴리즈에서는 대규모 ONTAP Select VM에서 하드웨어 RAID 및 vNAS 구성이 지원되지 않습니다.#

ONTAP Select 9.5 이상으로 업그레이드한 후 'system node upgrade-revert show' 명령을 실행하여 업그레이드가 완료되었음을 나타낼 때까지 기다린 후 기존 볼륨의 스토리지 효율성 값을 확인합니다.

ONTAP Select 9.5 이상으로 업그레이드한 시스템에서 기존 aggregate 또는 새로 생성된 aggregate에 생성된 새 볼륨은 새로운 구축에 생성된 볼륨과 동일한 동작을 가집니다. ONTAP Select 코드 업그레이드를 거친 기존 볼륨은 몇 가지 변동을 통해 새로 생성된 볼륨과 동일한 스토리지 효율성 정책을 대부분 가집니다.

시나리오 1:: 업그레이드 전에 볼륨에 스토리지 효율성 정책이 활성화되어 있지 않은 경우:
+
--
* '속도 보장 = 볼륨'인 볼륨에는 인라인 데이터 컴팩션, 애그리게이트 인라인 중복제거, 애그리게이트 백그라운드 중복제거가 활성화되어 있지 않습니다. 이러한 옵션은 업그레이드 후 활성화할 수 있습니다.
* '속도 보장 = 없음'인 볼륨에는 백그라운드 압축이 활성화되어 있지 않습니다. 이 옵션은 업그레이드 후 활성화할 수 있습니다.
* 업그레이드 후 기존 볼륨의 스토리지 효율성 정책이 자동으로 설정됩니다.


--
시나리오 2:: 업그레이드 전에 볼륨에서 일부 스토리지 효율성 기능이 이미 활성화되어 있는 경우:
+
--
* '속도 보장 = 볼륨'이 있는 볼륨은 업그레이드 후 차이가 없습니다.
* '속도 보장 = 없음'인 볼륨에는 집계 백그라운드 중복제거가 활성화되어 있습니다.
* 스토리지 정책을 인라인만 지원하는 볼륨에는 정책이 자동으로 설정되어 있습니다.
* 사용자 정의 스토리지 효율성 정책이 적용된 볼륨은 '속도 보장 = 없음'이 있는 볼륨을 제외하고 정책이 변경되지 않습니다. 이러한 볼륨에는 애그리게이트 백그라운드 중복제거가 활성화되어 있습니다.


--


업그레이드 전에 활성화된 스토리지 효율성 기능은 ONTAP Select 9.5 이상으로 업그레이드한 후에 유지됩니다. 업그레이드 전에 스토리지 효율성을 설정하지 않은 경우 업그레이드 후 스토리지 효율성이 활성화되지 않습니다.
