---
sidebar: sidebar 
permalink: concept_terminology.html 
keywords: terminology, key concepts, concepts 
summary: ONTAP Select를 탐색하고 배포를 계획할 때 먼저 용어와 주요 개념을 숙지하는 것이 좋습니다. 
---
= 용어 및 주요 개념
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select를 탐색하고 배포를 계획할 때 먼저 용어와 주요 개념을 숙지하는 것이 좋습니다.

ONTAP Select 구축:: ONTAP Select 배포는 ONTAP Select 클러스터를 배포하는 데 사용하는 관리 유틸리티입니다. 배포 유틸리티는 전용 Linux 가상 시스템에서 실행됩니다. 웹 사용자 인터페이스, CLI 관리 셸 및 REST API를 통해 배포 유틸리티에 액세스할 수 있습니다.
하이퍼바이저 호스트와 ONTAP Select 노드 비교:: h하이퍼바이저 host_는 ONTAP Select 가상 머신을 호스팅하는 핵심 하드웨어 플랫폼입니다. ONTAP Select 가상 머신이 하이퍼바이저 호스트에 구축되어 활성화되면 _ONTAP Select node_로 간주됩니다.
ONTAP Select 클러스터:: 1개, 2개, 4개, 6개 또는 8개의 노드로 구성된 _ONTAP Select cluster_를 생성할 수 있습니다. 다중 노드 클러스터에는 항상 하나 이상의 HA 쌍이 포함됩니다. 예를 들어, 4노드 클러스터는 2개의 HA 쌍으로 구성됩니다. 단일 노드 클러스터는 HA 기능을 제공하지 않습니다.
하이퍼바이저 호스트 환경 준비:: Deploy 관리 유틸리티를 사용하여 ONTAP Select 클러스터를 구축하기 전에 스토리지 및 네트워킹 환경을 포함하여 ONTAP Select가 실행될 하이퍼바이저 호스트를 준비해야 합니다. 이 호스트 사전 구성은 현재 요구 사항 및 제한 사항에 따라 ONTAP Select 제품 외부에서 수행됩니다.
평가 및 운영 구축 비교:: 모든 ONTAP Select 노드는 _Evaluation license_ 또는 _METURED LICENSE_로 실행됩니다. 평가판 라이센스를 사용하면 ONTAP Select를 프로덕션 환경에 배포하기 전에 평가할 수 있습니다. 평가판 라이센스가 자동으로 생성되고 적용됩니다. 운영 환경에 클러스터를 구축하는 경우 다음을 선택하는 라이센스가 필요합니다.
+
--
* 라이센스 모델
* 스토리지 용량
* 플랫폼 라이센스 제공


--
용량 계층 라이센스 모델:: 용량 계층 라이센스 모델은 ONTAP Select 구축을 위한 스토리지 라이센스 등록 시 원래 옵션입니다. 이 모델은 NetApp AFF 및 FAS와 함께 사용되는 ONTAP 모델을 기반으로 합니다. 각 노드에 대해 별도의 라이센스가 필요합니다. 스토리지 용량은 노드에 고정되어 있으며 영구적입니다(갱신 필요 없음).
용량 풀 라이센스 모델:: 용량 풀 라이센스 모델은 Deploy 2.10을 사용하는 ONTAP Select 9.5에서 도입되었습니다. 각 스토리지 용량 풀에 대해 별도의 라이센스가 필요합니다. 용량 풀 라이센스는 License Manager 인스턴스(배포 인스턴스)에 잠기고 구매 조건에 따라 갱신해야 합니다. 조직의 모든 용량 풀에 대한 라이센스를 부여하고 사용할 수 있습니다. 그러나 용량 풀은 ONTAP Select 노드에서 공유되므로 일반적으로 용량 계층 라이센싱보다 더 적은 라이센스가 필요합니다.
License Manager를 클릭합니다:: License Manager는 용량 풀 라이센스를 지원하는 소프트웨어 구성 요소입니다. 현재 배포 관리 유틸리티의 일부입니다. LM은 관리하는 공유 풀에서 ONTAP Select 노드로 스토리지를 임대해 줍니다. License Lock ID_는 각 LM 인스턴스를 고유하게 식별하는 숫자 문자열이므로 각 배포 인스턴스입니다. 라이센스 파일을 생성하려면 용량 풀 라이센스 일련 번호와 LLID를 모두 사용해야 합니다.
플랫폼 라이센스 제공:: 라이센스를 구입할 때 ONTAP Select 가상 머신의 크기 기능을 결정하는 세 가지 라이센스 오퍼링이 제공됩니다.
+
--
* 표준
* 프리미엄
* Premium XL


--


자세한 내용은 _Plan_과 _License_의 두 섹션을 참조하십시오.

스토리지 풀과 데이터 저장소 비교:: ONTAP Select_storage pool_은 기본 물리적 스토리지를 추상화하고 숨기도록 설계된 논리적 데이터 컨테이너입니다. 스토리지 풀은 하이퍼바이저에 종속되지 않습니다. ESXi 하이퍼바이저 호스트에 구축한 경우 ONTAP Select 스토리지 풀은 VMware_datastore_와 동일합니다.
클러스터 MTU:: 클러스터 MTU는 ONTAP Select 다중 노드 클러스터와 함께 사용되는 내부 네트워크에서 사용되는 MTU 크기를 구성할 수 있는 기능입니다. Deploy 관리 유틸리티는 네트워킹 환경에 맞게 HA 쌍을 구성할 때 MTU 크기를 조정합니다. 값을 수동으로 설정할 수도 있습니다.
ONTAP Select vNAS를 선택합니다:: ONTAP Select vNAS 솔루션을 사용하면 ONTAP Select 노드에서 외부 스토리지의 VMware 데이터 저장소를 액세스할 수 있습니다. ONTAP Select vNAS를 사용하면 로컬 RAID 컨트롤러가 더 이상 필요하지 않습니다. RAID 기능은 원격 스토리지에서 제공하는 것으로 간주됩니다. ONTAP Select vNAS는 다음과 같은 방법으로 구성할 수 있습니다.
+
--
* VMware vSAN을 선택합니다
* 일반 외부 스토리지 배열


--


두 경우 모두 ONTAP Select 클러스터를 생성하거나 기존 노드의 스토리지 용량을 확장하기 전에 외부 스토리지를 구성해야 합니다.

노드 재호스팅:: ONTAP Select vNAS 솔루션(VMware vSAN 또는 일반 외부 스토리지 어레이)을 통해 사용 가능한 외부 스토리지를 사용하는 클러스터를 구축하는 경우 ONTAP Select 노드를 호스팅하는 ESXi 가상 시스템은 다음 VMware 기능을 활용하여 작업을 통해 이동할 수 있습니다.
+
--
* 마이그레이션
* 고가용성(HA)
* DRS(Distributed Resource Scheduler)
+
ONTAP Select Deploy 유틸리티는 클러스터에서 작업을 실행하는 과정에서 가상 머신의 이동을 다음과 같이 감지합니다.

* 온라인 클러스터
* 클러스터가 오프라인 상태입니다
* 스토리지 추가
+
가상 머신이 이동되면 Deploy 유틸리티는 내부 데이터베이스를 업데이트하고 새 ESXi 호스트를 구성합니다. ONTAP Select 노드에서 수행되는 모든 작업은 가상 머신 이동 및 배포 업데이트가 완료될 때까지 차단됩니다.



--
중재자 서비스:: ONTAP Select Deploy 유틸리티에는 활성 2노드 클러스터의 노드에 연결되는 중재자 서비스가 포함되어 있습니다. 이 서비스는 각 HA 쌍을 모니터링하고 장애 관리를 지원합니다.



CAUTION: 하나 이상의 활성 2노드 클러스터가 있는 경우 클러스터를 관리하는 ONTAP Select Deploy 가상 머신이 항상 실행 중이어야 합니다. 가상 머신 배포가 중단되면 중재자 서비스를 사용할 수 없으며 2노드 클러스터의 HA 기능이 손실됩니다.

MetroCluster SDS:: MetroCluster SDS는 2노드 ONTAP Select 클러스터를 구축할 때 추가 구성 옵션을 제공하는 기능입니다. 일반적인 2노드 ROBO 구축과는 달리 MetroCluster SDS 노드는 훨씬 더 먼 거리로 분리할 수 있습니다. 이러한 물리적 분리를 통해 재해 복구와 같은 추가 사용 사례를 사용할 수 있습니다. MetroCluster SDS를 사용하려면 프리미엄 라이센스 이상이 있어야 합니다. 또한, 노드 간 네트워크는 최소 지연 시간 요구사항을 지원해야 합니다.
자격 증명 저장소:: 배포 자격 증명 저장소는 계정 자격 증명을 보관하는 안전한 데이터베이스입니다. 이 기능은 새 클러스터를 생성할 때 하이퍼바이저 호스트를 등록하는 데 주로 사용됩니다. 자세한 내용은 _Plan_절을 참조하십시오.
스토리지 효율성:: ONTAP Select는 FAS 및 AFF 어레이에 제공되는 스토리지 효율성 옵션과 유사한 스토리지 효율성 옵션을 제공합니다. 개념적으로 DAS(직접 연결 스토리지) SSD를 사용하는 ONTAP Select(프리미엄 라이센스 사용)는 AFF 어레이와 비슷합니다. HDD와 모든 vNAS 구성에서 DAS를 사용하는 구성은 FAS 어레이와 비슷해야 합니다. 두 구성 간의 주된 차이점은 DAS를 사용하는 ONTAP Select는 인라인 애그리게이트 레벨 중복제거 및 애그리게이트 레벨 백그라운드 중복제거를 지원한다는 점입니다. 나머지 스토리지 효율성 옵션은 두 구성 모두에서 사용할 수 있습니다.
+
--
vNAS 기본 구성에서는 SIDL(단일 인스턴스 데이터 로깅)이라고 하는 쓰기 최적화 기능을 사용할 수 있습니다. ONTAP Select 9.6 이상 버전에서는 백그라운드 ONTAP 스토리지 효율성 기능이 SIDL을 사용하는 것으로 검증되었습니다. 자세한 내용은 _deep dive_섹션을 참조하십시오.

--
클러스터 업데이트:: 클러스터를 생성한 후에는 ONTAP 또는 하이퍼바이저 관리 툴을 사용하여 배포 유틸리티 외부에서 클러스터 또는 가상 머신 구성을 변경할 수 있습니다. 구성 변경을 일으키는 가상 시스템을 마이그레이션할 수도 있습니다. 이러한 변경 사항이 발생하면 배포 유틸리티는 자동으로 업데이트되지 않으며 클러스터 상태와 동기화되지 않을 수 있습니다. 클러스터 새로 고침 기능을 사용하여 배포 구성 데이터베이스를 업데이트할 수 있습니다. 클러스터 새로 고침은 웹 배포 사용자 인터페이스, CLI 관리 셸 및 REST API를 통해 사용할 수 있습니다.
소프트웨어 RAID:: DAS(직접 연결 스토리지)를 사용하는 경우 RAID 기능은 일반적으로 로컬 하드웨어 RAID 컨트롤러를 통해 제공됩니다. 대신 ONTAP Select 노드가 RAID 기능을 제공하는 _software RAID_를 사용하도록 노드를 구성할 수 있습니다. 소프트웨어 RAID를 사용하는 경우 하드웨어 RAID 컨트롤러가 더 이상 필요하지 않습니다.
ONTAP Select 이미지 설치:: ONTAP Select 배포 2.8부터는 배포 관리 유틸리티에 단일 버전의 ONTAP Select만 포함됩니다. 포함된 버전은 릴리스 시점에 가장 최신 버전입니다. ONTAP Select 이미지 설치 기능을 사용하면 이전 버전의 ONTAP Select를 배포 유틸리티의 인스턴스에 추가할 수 있습니다. 그러면 ONTAP Select 클러스터를 배포할 때 이 기능을 사용할 수 있습니다. 을 참조하십시오 link:task_cli_deploy_image_add.html["ONTAP Select 이미지 추가 를 참조하십시오"].



NOTE: 배포 인스턴스에 포함된 원래 버전보다 이전 버전의 ONTAP Select 이미지만 추가해야 합니다. 배포를 업데이트하지 않고 최신 버전의 ONTAP Select를 추가하는 것은 지원되지 않습니다.

배포된 ONTAP Select 클러스터 관리:: ONTAP Select 클러스터를 구축한 후 하드웨어 기반 ONTAP 클러스터처럼 클러스터를 구성할 수 있습니다. 예를 들어, System Manager 또는 표준 ONTAP 명령줄 인터페이스를 사용하여 ONTAP Select 클러스터를 구성할 수 있습니다.


.관련 정보
link:task_cli_deploy_image_add.html["배포할 ONTAP Select 이미지를 추가합니다"]
