---
sidebar: sidebar 
permalink: concept_vpi_overview.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, overview, functionality 
summary: VMware vCenter Plug-in for ONTAP Select Deploy는 VMware 환경에서 작업하는 ONTAP Select 관리자를 위해 설계되었습니다. 네이티브 배포 사용자 인터페이스 대신 사용할 수 있습니다. 
---
= vCenter 플러그인 구축 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VMware vCenter Plug-in for ONTAP Select Deploy는 VMware 환경에서 작업하는 ONTAP Select 관리자를 위해 설계되었습니다. 네이티브 배포 사용자 인터페이스 대신 사용할 수 있습니다.



== 배포와 함께 패키지로 제공됩니다

Deploy vCenter 플러그인은 Deploy 관리 유틸리티와 함께 패키지로 제공됩니다. Deploy 사용자 인터페이스를 사용하여 vCenter Server에 플러그인을 설치한 후에는 vSphere 웹 인터페이스를 통해 플러그인에 액세스할 수 있습니다.



== VMware와 통합

많은 기업에서 VMware vCenter는 가상화된 데이터 센터 및 클라우드 리소스를 관리하는 중앙 플랫폼입니다. 배포 플러그인은 vCenter와 긴밀하게 통합되므로 관리자는 ONTAP Select와 vCenter 도메인 간에 신속하게 이동하여 다양한 리소스 간의 관계를 활용할 수 있습니다.



== Deploy vCenter 플러그인을 통해 제공되는 기능입니다

Deploy vCenter 플러그인을 설치하면 * Global Inventory Lists * 창에서 vSphere를 통해 두 가지 기본 옵션을 사용할 수 있습니다.



=== ONTAP Select 클러스터

ONTAP Select 클러스터 옵션은 기본 배포 웹 사용자 인터페이스의 * 클러스터 * 탭과 거의 동일합니다. 다음 표에 설명된 기능을 제공합니다.

[cols="30,70"]
|===
| 이 작업을 수행하는 경우... | 이렇게 하면... 


| ONTAP Select 클러스터 구축 | 새 ONTAP Select 를 클릭합니다. 


| 클러스터 세부 정보를 봅니다 | 클러스터를 선택하고 요약 을 클릭한 다음 세부 정보 를 클릭합니다. 


| 클러스터 이벤트 메시지를 봅니다 | 클러스터를 선택하고 요약 을 클릭한 다음 이벤트 를 클릭합니다. 


| 클러스터를 온라인 또는 오프라인으로 이동하거나 삭제합니다 | 클러스터를 선택하고 작업 을 클릭한 다음 원하는 작업을 클릭합니다. 


| System Manager를 시작합니다 | 클러스터를 선택하고 요약, 세부 정보 를 차례로 클릭한 다음 System Manager 시작 을 클릭합니다. 


| 클러스터에서 사용하는 ESXi 호스트를 봅니다 | 클러스터를 선택하고 More Objects 를 클릭한 다음 Hosts 를 클릭합니다. 자세한 내용 및 추가 작업을 보려면 호스트를 선택하십시오. 


| 클러스터에서 사용하는 ONTAP VM을 봅니다 | 클러스터를 선택하고 기타 개체 를 클릭한 다음 ONTAP VM 을 클릭합니다. 자세한 내용 및 추가 작업을 보려면 VM을 선택하십시오. 


| 클러스터에서 사용하는 데이터 저장소를 확인합니다 | 클러스터를 선택하고 More Objects 를 클릭한 다음 Datastores 를 클릭합니다. 자세한 내용과 추가 작업을 보려면 데이터 저장소를 선택하십시오. 


| 클러스터에서 사용하는 네트워크를 봅니다 | 클러스터를 선택하고 기타 개체 를 클릭한 다음 네트워크 를 클릭합니다. 자세한 내용과 추가 작업을 보려면 네트워크를 선택하십시오. 
|===


=== ONTAP Select 구축

ONTAP Select 배포 옵션은 기본 배포 웹 사용자 인터페이스의 * 하이퍼바이저 호스트 * 및 * 관리 * 탭과 거의 동일합니다. 다음 표에 설명된 대로 페이지 맨 위에 있는 세 개의 탭을 통해 기능을 제공합니다.

[cols="15,85"]
|===
| 탭을 클릭합니다 | 설명 


| 요약 | 에서는 호스트 이름 및 IP 주소를 포함하여 배포 인스턴스의 특성을 설명합니다. 


| 호스트 | ONTAP Select 배포에 등록된 ESXi 호스트에 대한 정보를 표시합니다. 호스트를 추가하거나 제거할 수 있습니다. 


| 관리 | 배포 유틸리티를 통해 관리 작업을 수행할 수 있습니다. 이 기능은 플러그인에서 * 자격 증명 * 및 * 플러그인 * 옵션을 사용할 수 없다는 점을 제외하고 ONTAP Select 배포 기본 사용자 인터페이스와 동일합니다. 
|===


== vCenter 플러그인을 기본 배포 사용자 인터페이스와 비교합니다

vSphere를 통해 vCenter 플러그인에서 제공하는 기능은 기본 구축 사용자 인터페이스와 동일합니다. 그러나 플러그인에는 제공되지 않는 몇 가지 기능이 있으며 배포 사용자 인터페이스에서만 사용할 수 있습니다.



=== vCenter 플러그인을 관리합니다

vCenter 플러그인을 사용하여 vCenter 플러그인을 설치, 업데이트, 제거 또는 확인할 수 없습니다. 네이티브 배포 사용자 인터페이스를 통해 이러한 관리 작업을 수행해야 합니다.



=== vCenter 자격 증명을 관리합니다

vCenter 플러그인을 설치하기 전에 기본 구축 사용자 인터페이스를 사용하여 구축하는 데 필요한 vCenter 자격 증명을 추가해야 합니다.



=== ONTAP Select 클러스터는 동일한 vCenter Server에서 제어되어야 합니다

플러그인이 설치된 단일 vCenter Server에서 관리하는 ONTAP Select 클러스터만 구축하고 지원할 수 있습니다. 플러그인을 사용하여 독립 실행형 ESXi 또는 KVM 호스트에서 실행 중인 다른 vCenter Server 또는 클러스터에서 관리되는 ONTAP Select 클러스터에 액세스할 수 없습니다.
