---
sidebar: sidebar 
permalink: concept_nw_concepts_chars.html 
keywords: ontap select, networking concepts, cluster characteristics 
summary: 먼저 ONTAP Select 환경에 적용되는 일반적인 네트워킹 개념을 숙지하십시오. 그런 다음 단일 노드 및 다중 노드 클러스터에서 사용할 수 있는 특정 특성 및 옵션을 살펴봅니다. 
---
= 네트워킹: 일반 개념 및 특성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
먼저 ONTAP Select 환경에 적용되는 일반적인 네트워킹 개념을 숙지하십시오. 그런 다음 단일 노드 및 다중 노드 클러스터에서 사용할 수 있는 특정 특성 및 옵션을 살펴봅니다.



== 물리적 네트워킹

물리적 네트워크는 기본적으로 기본 계층 2 스위칭 인프라를 제공하여 ONTAP Select 클러스터 구축을 지원합니다. 물리적 네트워크와 관련된 구성에는 하이퍼바이저 호스트와 보다 광범위한 스위치 네트워크 환경이 모두 포함됩니다.



=== 호스트 NIC 옵션

각 ONTAP Select 하이퍼바이저 호스트는 2개 또는 4개의 물리적 포트로 구성되어야 합니다. 정확한 구성은 다음을 포함한 여러 요인에 따라 달라집니다.

* 클러스터에 ONTAP Select 호스트가 하나 또는 여러 개 있는지 여부
* 사용되는 하이퍼바이저 운영 체제입니다
* 가상 스위치 구성 방법
* LACP가 링크와 함께 사용되는지 여부




=== 물리적 스위치 구성

물리적 스위치 구성이 ONTAP Select 구축을 지원하는지 확인해야 합니다. 물리적 스위치는 하이퍼바이저 기반 가상 스위치와 통합되어 있습니다. 정확한 구성은 여러 요인에 따라 달라집니다. 주요 고려 사항은 다음과 같습니다.

* 내부 및 외부 네트워크를 어떻게 분리하시겠습니까?
* 데이터와 관리 네트워크를 서로 분리하시겠습니까?
* 계층 2 VLAN은 어떻게 구성됩니까?




== 논리적 네트워킹

ONTAP Select는 두 개의 서로 다른 논리 네트워크를 사용하여 유형에 따라 트래픽을 분리합니다. 특히 클러스터 내의 호스트 간에 트래픽이 흐를 수 있을 뿐 아니라 클러스터 외부의 스토리지 클라이언트 및 기타 시스템으로도 트래픽을 전송할 수 있습니다. 하이퍼바이저에서 관리하는 가상 스위치는 논리적 네트워크를 지원합니다.



=== 내부 네트워크

다중 노드 클러스터 배포를 통해 개별 ONTAP Select 노드는 격리된 "내부" 네트워크를 사용하여 통신합니다. 이 네트워크는 ONTAP Select 클러스터의 노드 외부에서 노출되거나 사용할 수 없습니다.


NOTE: 내부 네트워크는 다중 노드 클러스터와만 함께 제공됩니다.

내부 네트워크에는 다음과 같은 특성이 있습니다.

* 다음을 비롯한 ONTAP 클러스터 내 트래픽을 처리하는 데 사용됩니다.
+
** 클러스터
** 고가용성 인터커넥트(HA-IC)
** RAID 동기화 미러(RSM)


* 단일 계층 - VLAN을 기반으로 하는 2개의 네트워크
* 정적 IP 주소는 ONTAP Select에 의해 할당됩니다.
+
** IPv4만 해당
** DHCP가 사용되지 않습니다
** 링크-로컬 주소


* MTU 크기는 기본적으로 9000바이트이며 7500-9000 범위 내에서 조정할 수 있습니다(포함).




=== 외부 네트워크

외부 네트워크는 ONTAP Select 클러스터의 노드와 외부 스토리지 클라이언트 및 다른 시스템 간의 트래픽을 처리합니다. 외부 네트워크는 모든 클러스터 배포의 일부이며 다음과 같은 특징이 있습니다.

* 다음을 비롯한 ONTAP 트래픽을 처리하는 데 사용됩니다.
+
** 데이터(NFS, CIFS, iSCSI)
** 관리(클러스터 및 노드, 선택적으로 SVM)
** 인터클러스터(선택 사항)


* 선택적으로 VLAN 지원:
+
** 데이터 포트 그룹
** 관리 포트 그룹


* 관리자의 구성 선택에 따라 할당되는 IP 주소:
+
** IPv4 또는 IPv6


* MTU 크기는 기본적으로 1500바이트입니다(조정 가능).


외부 네트워크에는 모든 크기의 클러스터가 있습니다.



== 가상 시스템 네트워킹 환경

하이퍼바이저 호스트는 몇 가지 네트워킹 기능을 제공합니다.

ONTAP Select는 가상 머신을 통해 표시되는 다음과 같은 기능을 기반으로 합니다.

가상 머신 포트:: ONTAP Select에서 사용할 수 있는 포트가 여러 개 있습니다. 클러스터의 크기를 비롯한 여러 가지 요소를 기반으로 할당되어 사용됩니다.
가상 스위치:: vSwitch(VMware) 또는 Open vSwitch(KVM)와 같은 하이퍼바이저 환경 내의 가상 스위치 소프트웨어는 가상 시스템에 의해 노출되는 포트를 물리적 이더넷 NIC 포트와 결합합니다. 환경에 맞게 모든 ONTAP Select 호스트에 대해 vSwitch를 구성해야 합니다.

