---
sidebar: sidebar 
permalink: reference_plan_dep_general.html 
keywords: plan, planning, ontap select deploy, general requirements 
summary: ONTAP Select 배포 관리 유틸리티 설치 계획의 일부로 고려해야 하는 몇 가지 일반적인 요구 사항이 있습니다. 
---
= ONTAP Select은 일반 요구 사항 및 계획을 배포합니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 배포 관리 유틸리티 설치 계획의 일부로 고려해야 하는 몇 가지 일반적인 요구 사항이 있습니다.



== 배포 유틸리티를 ONTAP Select 클러스터와 페어링합니다

Deploy 유틸리티의 인스턴스를 ONTAP Select 클러스터와 페어링할 때 여러 가지 옵션이 있습니다.


NOTE: 모든 구축 시나리오에서 단일 ONTAP Select 클러스터와 클러스터의 노드는 Deploy 관리 유틸리티의 단일 인스턴스에서만 관리할 수 있습니다. Deploy 유틸리티의 두 개 이상의 다른 인스턴스는 클러스터를 관리할 수 없습니다.



===== 각 ONTAP Select 클러스터에 대한 유틸리티 인스턴스 1개

Deploy 유틸리티의 전용 인스턴스를 사용하여 각 ONTAP Select 클러스터를 구축하고 관리할 수 있습니다. 이 일대일 구성을 사용하면 각 유틸리티와 클러스터 쌍 간에 명확한 구분이 가능합니다. 이 구성은 더 작은 장애 도메인을 사용하여 높은 수준의 격리를 제공합니다.



===== 여러 ONTAP Select 클러스터에 대한 유틸리티 인스턴스 1개

배포 유틸리티의 단일 인스턴스를 사용하여 조직 내에서 여러 ONTAP Select 클러스터를 배포하고 관리할 수 있습니다. 이 일대다 구성을 사용하면 모든 처리 및 구성 데이터가 배포 유틸리티의 동일한 인스턴스에서 관리됩니다.


NOTE: Deploy 유틸리티의 한 인스턴스는 최대 400개의 ONTAP Select 노드 또는 100개의 클러스터를 관리할 수 있습니다.



== 자격 증명 저장소를 사용하여 인증합니다

ONTAP Select 배포 자격 증명 저장소는 계정 정보를 보관하는 데이터베이스입니다. Deploy는 계정 자격 증명을 사용하여 클러스터 생성 및 관리의 일부로 호스트 인증을 수행합니다. ONTAP Select 배포를 계획할 때 자격 증명 저장소가 어떻게 사용되는지 알고 있어야 합니다.


NOTE: 계정 정보는 AES 암호화 알고리즘 및 SHA-256 해싱 알고리즘을 사용하여 데이터베이스에 안전하게 저장됩니다.



===== 자격 증명의 유형입니다

지원되는 자격 증명 유형은 다음과 같습니다.

* ONTAP Select 노드를 VMware ESXi에 직접 구축할 때 하이퍼바이저 호스트를 인증하는 데 사용되는 호스트입니다
* VMware vCenter에서 호스트를 관리할 때 ESXi에 ONTAP Select 노드를 구축하는 과정에서 vCenter Server를 인증하는 데 사용되는 vCenter입니다




===== 액세스

하이퍼바이저 호스트 추가와 같은 배포를 사용하여 일반 관리 작업을 수행하는 과정에서 자격 증명 저장소에 내부적으로 액세스합니다. 웹 배포 사용자 인터페이스 및 CLI를 통해 자격 증명 저장소를 직접 관리할 수도 있습니다.
