---
sidebar: sidebar 
permalink: reference_plan_best_practices.html 
keywords: plan, planning, best practices, recommendations 
summary: ONTAP Select 배포 계획의 일부로 고려해야 하는 모범 사례가 있습니다. 
---
= 모범 사례 요약
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 배포 계획의 일부로 고려해야 하는 모범 사례가 있습니다.



== 스토리지

다음과 같은 스토리지 모범 사례를 고려해야 합니다.



=== All-Flash 또는 일반 플래시 어레이

All-Flash VSAN 또는 일반 플래시 스토리지를 사용하는 vNAS(ONTAP Select Virtual NAS) 구축은 비 SSD DAS 스토리지를 사용하는 ONTAP Select에 대한 Best Practice를 따라야 합니다.



=== 하이퍼바이저 코어 하드웨어

단일 ONTAP Select 애그리게이트의 모든 드라이브가 동일한 유형이어야 합니다. 예를 들어, HDD와 SSD 드라이브를 동일한 Aggregate에서 혼합하면 안 됩니다.



=== RAID 컨트롤러

서버 RAID 컨트롤러가 쓰기 저장 모드에서 작동하도록 구성해야 합니다. 쓰기 작업 부하 성능 문제가 나타나면 컨트롤러 설정을 확인하고 WriteThrough 또는 Writearound 가 활성화되어 있지 않은지 확인합니다.

물리적 서버에 로컬로 연결된 모든 디스크를 관리하는 단일 RAID 컨트롤러가 포함된 경우 서버 OS에 대해 별도의 LUN을 생성하고 ONTAP Select에 대해 하나 이상의 LUN을 생성하는 것이 좋습니다. 부팅 디스크가 손상된 경우 관리자는 이 모범 사례를 통해 ONTAP Select에 영향을 주지 않고 OS LUN을 다시 생성할 수 있습니다.

RAID 컨트롤러 캐시는 NVRAM 파티션을 대상으로 하는 것이 아니라 들어오는 모든 블록 변경 사항을 저장하는 데 사용됩니다. 따라서 RAID 컨트롤러를 선택할 때 사용 가능한 캐시 용량이 가장 큰 컨트롤러를 선택합니다. 캐시가 클수록 디스크 플러시를 덜 자주 수행하고 ONTAP Select VM, 하이퍼바이저 및 서버에 배치된 모든 컴퓨팅 VM의 성능을 향상시킬 수 있습니다.



=== RAID 그룹

최적의 RAID 그룹 크기는 8~12개의 드라이브입니다. RAID 그룹당 최대 드라이브 수는 24개입니다.

ONTAP Select 노드당 지원되는 최대 NVMe 드라이브 수는 14개입니다.

스페어 디스크는 선택 사항이지만 사용하는 것이 좋습니다. 또한 RAID 그룹당 하나의 스페어를 사용하는 것이 좋습니다. 하지만 모든 RAID 그룹에 대한 글로벌 스페어를 사용할 수 있습니다. 예를 들어 3개의 RAID 그룹당 2개의 스페어를 사용할 수 있습니다. 각 RAID 그룹은 8~12개의 드라이브로 구성됩니다.

ONTAP Select는 RAID 그룹 내에서 LUN 수를 늘려서 성능 이점을 제공하지 않습니다. SATA/NL-SAS 구성의 모범 사례를 따르거나 하이퍼바이저 파일 시스템 제한을 우회하기 위해서만 여러 LUN을 사용해야 합니다.



=== VMware ESXi 호스트

시스템 디스크를 호스팅하는 데이터 저장소에는 ESX 6.5 U2 이상 및 NVMe 디스크를 사용하는 것이 좋습니다. 이 구성은 NVRAM 파티션에 최고의 성능을 제공합니다.


NOTE: ESX 6.5 U2 이상에 설치할 때 ONTAP Select는 시스템 디스크가 SSD에 있는지 또는 NVMe 디스크에 있는지 여부와 관계없이 vNVME 드라이버를 사용합니다. 이렇게 하면 VM 하드웨어 수준이 13으로 설정되며 ESX 6.5 이상과 호환됩니다.

ONTAP Select 네트워크 및 외부 스토리지에 대한 전용 네트워크 포트, 대역폭 및 vSwitch 구성을 정의합니다(iSCSI 또는 NFS를 사용할 경우 VMware vSAN 및 일반 스토리지 어레이 트래픽).

용량 옵션을 구성하여 스토리지 사용률을 제한합니다(ONTAP Select는 외부 vNAS 데이터 저장소의 전체 용량을 사용할 수 없음).

가능한 경우 모든 일반 외부 스토리지 어레이가 사용 가능한 이중화 및 HA 기능을 사용하도록 합니다.



=== VMware Storage vMotion을 참조하십시오

ONTAP Select 노드와 함께 VMware Storage vMotion을 사용할지 여부를 결정할 때는 새 호스트에서 사용 가능한 용량을 고려해야 합니다. 기본 스토리지 유형, 호스트 구성 및 네트워크 기능은 원래 호스트와 동일한 워크로드를 유지할 수 있어야 합니다.



== 네트워킹

네트워킹에 대한 다음 모범 사례를 고려해야 합니다.



=== MAC 주소가 중복됩니다

여러 개의 배포 인스턴스가 중복 MAC 주소를 할당하도록 하려면 ONTAP Select 클러스터나 노드를 만들거나 관리하는 데 계층 2 네트워크당 하나의 배포 인스턴스를 사용해야 합니다.



=== EMS 메시지

ONTAP Select 2노드 클러스터에서는 스토리지 페일오버가 비활성화되었음을 나타내는 EMS 메시지를 신중하게 모니터링해야 합니다. 이러한 메시지는 중재자 서비스에 대한 연결이 끊어졌음을 나타내며 즉시 수정해야 합니다.



=== 로드 밸런싱

내부 및 외부 ONTAP Select 네트워크 모두에서 로드 밸런싱을 최적화하려면 원래 가상 포트 로드 밸런싱 정책을 기반으로 하는 경로 지정 을 사용합니다.



=== 다중 계층-2 네트워크

데이터 트래픽이 여러 계층 2 네트워크에 걸쳐 있고 VLAN 포트를 사용해야 하거나 여러 IPspace를 사용하는 경우 VGT를 사용해야 합니다.



=== 물리적 스위치 구성

ESXi 호스트에 연결된 스위치 포트에서 STP를 portfast로 설정하는 것이 좋습니다. 스위치 포트에서 STP를 portfast로 설정하지 않으면 업링크 실패를 견딜 수 있는 ONTAP Select 기능에 영향을 줄 수 있습니다. LACP를 사용하는 경우 LACP 타이머를 빠름(1초)으로 설정해야 합니다. 로드 밸런싱 정책은 포트 그룹의 IP 해시, 소스 및 대상 IP 주소, LAG의 TCP/UDP 포트 및 VLAN을 기준으로 라우팅으로 설정되어야 합니다.



== HA

고가용성을 위한 다음 Best Practice를 고려해야 합니다.



=== 백업 구축

클러스터 생성 후를 포함하여 배포 구성 데이터를 정기적으로 백업하는 것이 좋습니다. 중재 구성 데이터가 백업에 포함되기 때문에 2노드 클러스터에서는 이 점이 특히 중요합니다.

클러스터를 생성하거나 구축한 후에는 ONTAP Select 구축 구성 데이터를 백업해야 합니다.



=== 미러링된 애그리게이트

기본 애그리게이트의 RPO 0(최신) 복사본을 제공하기 위해 미러링된 애그리게이트는 존재하지만, 기본 애그리게이트에 대해 여유 공간이 부족하지 않도록 주의해야 합니다. 운영 애그리게이트에서 공간 부족 조건은 ONTAP이 스토리지 기브백의 기준선으로 사용되는 일반 스냅샷 복사본을 삭제할 수 있습니다. 이는 클라이언트 쓰기를 수용하도록 설계된 대로 작동합니다. 하지만 페일백에서 공통 스냅샷 복사본이 없기 때문에 ONTAP Select 노드가 미러링된 애그리게이트의 전체 기본을 수행해야 합니다. 이 작업은 비공유 환경에서 상당한 시간이 걸릴 수 있습니다.


NOTE: 최적의 스토리지 성능과 가용성을 위해 미러링된 애그리게이트에 대해 최소 20%의 여유 공간을 유지하는 것이 좋습니다. 미러링되지 않은 애그리게이트의 권장사항은 10%이지만, 파일 시스템이 증분 변경을 흡수하기 위해 추가 10%의 공간을 사용할 수 있습니다. 증분식으로 변경하면 ONTAP의 COW Snapshot 기반 아키텍처로 인해 미러링된 애그리게이트의 공간 활용률이 증가합니다. 이러한 모범 사례를 준수하지 않을 경우 성능에 부정적인 영향을 미칠 수 있습니다.



=== NIC 집계, 팀 구성 및 페일오버

ONTAP Select는 2노드 클러스터를 위한 단일 10Gb 링크를 지원하지만 ONTAP Select 클러스터의 내부 및 외부 네트워크에서 NIC 애그리게이션 또는 NIC 티밍을 통해 하드웨어 이중화를 제공하는 것이 NetApp의 모범 사례입니다.

NIC에 ASIC(Application-Specific Integrated Circuit)가 여러 개 있는 경우 내부 및 외부 네트워크를 위한 NIC 팀을 통해 네트워크 구조를 구축할 때 각 ASIC에서 네트워크 포트를 하나 선택합니다.

LACP 모드는 ESX와 물리적 스위치 모두에서 활성화할 것을 권장합니다. 또한 LACP 타이머는 물리적 스위치, 포트, 포트 채널 인터페이스 및 VMNIC에서 고속(1초)으로 설정해야 합니다.

LACP와 함께 분산 vSwitch를 사용하는 경우 LAG의 포트 그룹, 소스 및 대상 IP 주소, TCP/UDP 포트 및 VLAN에서 IP 해시를 기준으로 라우팅하도록 로드 밸런싱 정책을 구성하는 것이 좋습니다.



=== 2노드 확장 HA(MetroCluster SDS) 모범 사례

MetroCluster SDS를 생성하기 전에 ONTAP Deploy 연결 검사기를 사용하여 두 데이터 센터 간의 네트워크 지연 시간이 허용 범위 내에 있는지 확인하십시오.

VGT(Virtual Guest Tagging) 및 2노드 클러스터를 사용할 때는 추가적인 주의가 필요합니다. 2노드 클러스터 구성에서는 노드 관리 IP 주소를 사용하여 중재자를 조기에 연결하고 ONTAP를 완전히 사용할 수 있습니다. 따라서 노드 관리 LIF(포트 e0a)에 매핑된 포트 그룹에서 외부 스위치 태깅(EST)과 가상 스위치 태깅(VST)만 지원됩니다. 또한 관리 트래픽과 데이터 트래픽이 모두 동일한 포트 그룹을 사용하는 경우 EST 및 VST만 전체 2노드 클러스터에 지원됩니다.
