---
sidebar: sidebar 
permalink: reference_plan_dep_vmware.html 
keywords: plan, planning, ontap select deploy, vmware requirements 
summary: VMware 환경에 ONTAP Select 배포 유틸리티를 설치하기 전에 고려해야 하는 VMware 환경 관련 몇 가지 요구 사항과 제한 사항이 있습니다. 
---
= VMware 하이퍼바이저 환경
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VMware 환경에 ONTAP Select 배포 유틸리티를 설치하기 전에 고려해야 하는 VMware 환경 관련 몇 가지 요구 사항과 제한 사항이 있습니다.



== ESXi 호스트 서버 하드웨어 요구 사항

ESXi 하이퍼바이저 호스트가 충족해야 하는 최소 리소스 요구 사항은 몇 가지가 있습니다. ONTAP Select가 구축된 호스트가 다음과 같은 기본 요구 사항을 충족하는지 확인해야 합니다.

* ESXi 서버:
+
** 하드웨어 및 소프트웨어는 64비트여야 합니다
** ONTAP Select 노드에 대해 정의된 것과 동일한 지원 버전을 준수해야 합니다


* 가상 CPU 2개
* 가상 메모리(4GB)
* 스토리지(40GB)
* DHCP 활성화(고정 IP 주소를 할당할 수도 있음)




== 네트워크 연결

ONTAP Select Deploy 가상 머신 네트워크 인터페이스가 구성되어 있고 관리 IP 주소가 하나만 있는지 확인해야 합니다. DHCP를 사용하여 동적으로 IP 주소를 할당하거나 고정 IP 주소를 수동으로 구성할 수 있습니다.

구축 결정에 따라 구축 VM은 vCenter Server, ESXi 하이퍼바이저 호스트 및 관리하는 ONTAP Select 노드에 연결할 수 있어야 합니다. 필요한 트래픽을 허용하도록 방화벽을 구성해야 합니다.

Deploy는 VMware VIX API를 사용하여 vCenter 서버 및 ESXi 호스트와 통신합니다. 처음에는 TCP 포트 443에서 SSL을 통한 SOAP 연결을 설정합니다. 이 후 포트 902에서 SSL을 사용하여 연결이 열립니다. 또한 deploy는 ping 명령을 실행하여 지정한 IP 주소에 ESXi 호스트가 있는지 확인합니다.

Deploy는 다음 프로토콜을 사용하여 ONTAP Select 노드 및 클러스터 관리 IP 주소와 통신할 수 있어야 합니다.

* ping 명령(ICMP)
* SSH(포트 22)
* SSL(포트 443)




== IP 버전 4 지원

ONTAP Select 배포는 IP 버전 4(IPv4)만 지원합니다. IP 버전 6(IPv6)은 지원되지 않습니다. 이러한 제한은 다음과 같은 방법으로 ONTAP Select에 영향을 줍니다.

* 가상 시스템 배포 의 관리 LIF에 IPv4 주소를 할당해야 합니다.
* ONTAP LIF에서 IPv6을 사용하도록 구성된 ONTAP Select 노드를 구축할 수 없습니다.




== VMware vCenter 언어 제한

ONTAP Select Deploy를 사용하여 Windows 서버의 vCenter에서 ESXi에서 실행되는 클러스터를 생성하는 경우 영어 버전을 사용해야 합니다. ONTAP Select 배포는 영어 이외의 버전의 Windows에서 vCenter를 지원하지 않습니다.
