---
sidebar: sidebar 
permalink: reference_plan_ots_hardware.html 
keywords: plan, planning, vmware, hardware, hardware requirements 
summary: VMware 환경과 관련하여 고려해야 할 몇 가지 하드웨어 요구 사항 및 계획 문제가 있습니다. 
---
= ONTAP Select VMware 하이퍼바이저 및 하드웨어 고려 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VMware 환경과 관련하여 고려해야 할 몇 가지 하드웨어 요구 사항 및 계획 문제가 있습니다.



== 하이퍼바이저 요구 사항

ONTAP Select가 실행되는 하이퍼바이저와 관련된 몇 가지 요구 사항이 있습니다.


NOTE: ONTAP Select 버전에 대한 현재 릴리스 노트에서 추가로 알려진 제한 사항 또는 제한 사항이 있는지 검토해야 합니다.



=== VMware 라이센스 등록

ONTAP Select 클러스터를 구축하려면 ONTAP Select가 실행되는 하이퍼바이저 호스트에 대해 유효한 VMware vSphere 라이센스가 있어야 합니다. 배포에 적합한 라이센스를 사용해야 합니다.



=== 소프트웨어 호환성

KVM 및 ESXi 하이퍼바이저에 ONTAP Select 배포할 수 있습니다.

[role="tabbed-block"]
====
.KVM
--
ONTAP Select 다음 KVM 하이퍼바이저 버전을 지원합니다.

* Red Hat Enterprise Linux 9.6, 9.5, 9.4, 9.2, 9.1, 9.0, 8.8, 8.7 및 8.6의 KVM
* Rocky Linux 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7 및 8.6의 KVM


--
.ESXi
--
ONTAP Select 다음 ESXi 하이퍼바이저 버전을 지원합니다.

* VMware ESXi 8.0 U3
* VMware ESXi 8.0 U2
* VMware ESXi 8.0 U1(빌드 21495797)
* VMware ESXi 8.0 GA(빌드 20513097)
* VMware ESXi 7.0 GA(빌드 15843807 이상)에는 7.0 U3C, U2 및 U1이 포함됩니다.



NOTE: VMware가 동일한 버전을 계속 지원하는 한 NetApp은 ESXi의 지정된 버전에서 ONTAP Select를 지원합니다.


NOTE: ESXi 6.5 GA 및 ESXi 6.7 GA가 공급 중지 상태에 도달했습니다. 이러한 버전이 포함된 ONTAP Select 클러스터가 있는 경우 에 따라 지원되는 버전으로 업그레이드해야 합니다 https://mysupport.netapp.com/matrix["상호 운용성 매트릭스 툴(IMT)"^].

--
====


=== VMware vCenter 및 독립 실행형 ESXi 호스트

vCenter Server에서 ESXi 하이퍼바이저 호스트를 관리하는 경우 vCenter 자격 증명을 사용하여 호스트를 Deploy 관리 유틸리티에 등록해야 합니다. ESXi 자격 증명을 사용하여 호스트를 독립 실행형 호스트로 등록할 수 없습니다.



== 핵심 하드웨어 요구 사항

ONTAP Select를 구축하는 물리적 하이퍼바이저 호스트는 몇 가지 하드웨어 요구 사항을 충족해야 합니다. 최소 하드웨어 요구 사항을 충족하는 경우 하이퍼바이저 호스트용 플랫폼을 선택할 수 있습니다. 지원되는 하드웨어 플랫폼은 Cisco, Dell, HP, Fujitsu, Lenovo, 슈퍼마이크로.


NOTE: ONTAP Select 9.9.1부터 인텔 제온 Sandy Bridge 이상을 기반으로 하는 CPU 모델만 지원됩니다.

자세한 내용은 을 https://mysupport.netapp.com/matrix["상호 운용성 매트릭스 도구, window=_blank"] 참조하십시오.



=== 기본 하드웨어 요구 사항

노드 인스턴스 유형 또는 라이센스 제공에 관계없이 모든 플랫폼에 적용되는 몇 가지 일반적인 하드웨어 요구 사항이 있습니다.

.프로세서
지원되는 마이크로프로세서에는 서버용 Intel Xeon 프로세서가 포함됩니다. link:https://www.intel.com/content/www/us/en/products/processors/xeon/view-all.html?Processor+Type=1003["인텔 제온 프로세서, window=_blank"] 자세한 내용은.


NOTE: AMD(Advanced Micro Devices) 프로세서는 ONTAP Select에서 지원되지 않습니다.

.이더넷 구성
클러스터 크기에 따라 지원되는 여러 이더넷 구성이 있습니다.

[cols="2,3,3"]
|===
| 클러스터 크기 | 최소 요구 사항 | 권장 요구 사항 


| 단일 노드 클러스터 | 1GbE 2개 | 10GbE 2개 


| 2노드 클러스터 또는 MetroCluster SDS | 1GbE 4개 또는 10GbE 1개 | 10GbE 2개 


| 4/6/8 노드 클러스터 | 10GbE 2개 | 4 x 10GbE 또는 2 x 25/40GbE 
|===


=== 인스턴스 유형에 따른 추가 하드웨어 요구 사항

노드 인스턴스 유형에 따라 몇 가지 추가 하드웨어 요구 사항이 있습니다.

을 참조하십시오 link:concept_lic_platforms.html["플랫폼 라이센스 제공 사항을 이해합니다"] 를 참조하십시오.

[cols="a1,a2,a2,a2"]
|===
| 노드 크기 | CPU 코어 | 메모리 | 필수 플랫폼 라이선스 제공 


| 작은 크기 | 6개 이상의 물리적 코어, 그중 4개는 ONTAP Select 용으로 예약됨 | 24GB 이상, ONTAP Select 용으로 16GB 예약됨 | 스탠다드, 프리미엄 또는 프리미엄 XL 


| 중간 | 10개 이상의 물리적 코어, 그중 8개는 ONTAP Select 용으로 예약됨 | 72GB 이상, ONTAP Select 용으로 64GB 예약됨 | 프리미엄 또는 프리미엄 XL 


| 대형 | 18개 이상의 물리적 코어, 그중 16개는 ONTAP Select 용으로 예약됨 | 136GB 이상, ONTAP Select 용으로 128GB 예약됨 | Premium XL 
|===

NOTE: 플랫폼 라이센스에 따라 추가 디스크 요구 사항이 있습니다. 을 참조하십시오 link:reference_plan_ots_storage.html["스토리지 및 RAID"] 를 참조하십시오.
