---
sidebar: sidebar 
permalink: reference_plan_ots_two_node.html 
keywords: plan, planning, two nodes, two node clusters 
summary: HA로 2노드 클러스터를 구축하려면 다른 클러스터 노드 구성과 동일한 계획 및 구성이 필요합니다. 하지만 2노드 클러스터를 생성할 때는 여러 가지 차이점을 알고 있어야 합니다. 
---
= HA가 포함된 ONTAP Select 2노드 클러스터
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
HA로 2노드 클러스터를 구축하려면 다른 클러스터 노드 구성과 동일한 계획 및 구성이 필요합니다. 하지만 2노드 클러스터를 생성할 때는 여러 가지 차이점을 알고 있어야 합니다.

.대상 환경
2노드 클러스터는 하나의 HA 쌍으로 구성되며, 원격 사무소 및 지사 구축을 위해 특별히 설계되었습니다.


NOTE: 주로 원격 및 지사 환경에 맞게 설계되었지만, 필요한 경우 데이터 센터에 2노드 클러스터를 구축할 수도 있습니다.

.라이센싱
VMware vSphere 라이센스를 사용하여 2노드 클러스터를 구축할 수 있습니다. 그러나 VMware ROBO Standard 및 Advanced 라이센스는 원격 및 지사 구축에 적합합니다.

.중재자 서비스
클러스터가 두 개의 노드로 구성된 경우 노드에서 장애가 발생하거나 통신이 끊긴 경우 필요한 쿼럼을 달성할 수 없습니다. 이러한 유형의 브레인 분할 상황을 해결하기 위해 ONTAP Select 배포 유틸리티의 모든 인스턴스에는 중재자 서비스가 포함되어 있습니다. 이 서비스는 액티브 2노드 클러스터의 각 노드에 연결하여 HA 쌍을 모니터링하고 장애 관리를 지원합니다. 중재자 서비스는 각 2노드 클러스터와 연결된 전용 iSCSI 대상에서 HA 상태 정보를 유지합니다.


CAUTION: 하나 이상의 활성 2노드 클러스터가 있는 경우 클러스터를 관리하는 ONTAP Select Deploy 가상 머신이 항상 실행 중이어야 합니다. 가상 머신 배포가 중단되거나 실패하면 중재자 서비스를 사용할 수 없으며 2노드 클러스터의 HA 기능이 손실됩니다.

.클러스터의 위치 및 중재자 서비스
일반적으로 2노드 클러스터는 원격 사무소 또는 지사에 배포되므로 기업 데이터 센터와 관리 지원을 제공하는 배포 유틸리티에서 원격으로 클러스터를 구축할 수 있습니다. 이 구성을 사용하면 배포 유틸리티와 클러스터 간의 관리 트래픽이 WAN을 통해 흐릅니다. 제한 사항 및 제한 사항에 대한 자세한 내용은 릴리즈 노트를 참조하십시오.

.배포 구성 데이터를 백업합니다
클러스터 생성 후를 포함하여 배포 구성 데이터를 정기적으로 백업하는 것이 좋습니다. 이는 백업에 포함된 중재 구성 데이터 때문에 2노드 클러스터에서 특히 중요합니다.

.배포에 할당된 정적 IP 주소입니다
배포 관리 유틸리티에 정적 IP 주소를 할당해야 합니다. 이 요구사항은 하나 이상의 ONTAP Select 2노드 클러스터를 관리하는 모든 배포 인스턴스에 적용됩니다.
