---
sidebar: sidebar 
permalink: reference_plan_ots_storage.html 
keywords: plan, planning, storage, software raid, hardware raid, raid, nvme 
summary: ONTAP Select 호스트 스토리지와 관련하여 고려해야 할 몇 가지 계획 문제가 있습니다. 
---
= ONTAP Select 스토리지 및 RAID 고려 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 호스트 스토리지와 관련하여 고려해야 할 몇 가지 계획 문제가 있습니다.


NOTE: 외부 스토리지 지원 정보는 에 설명되어 있습니다 link:reference_plan_ots_vnas.html["ONTAP Select vNAS 요구 사항"].



== 하드웨어 RAID 컨트롤러 요구 사항

ONTAP Select를 구축하는 하이퍼바이저 호스트의 RAID 컨트롤러는 몇 가지 요구 사항을 충족해야 합니다.


NOTE: ONTAP Select가 실행되는 호스트는 하드웨어 RAID 컨트롤러 또는 ONTAP Select와 함께 제공되는 소프트웨어 RAID 기능을 사용할 때 로컬 물리적 드라이브가 필요합니다. ONTAP Select vNAS 솔루션을 사용하여 외부 스토리지에 액세스하는 경우 로컬 RAID 컨트롤러 및 소프트웨어 RAID 기능은 사용되지 않습니다.

RAID 컨트롤러에 대한 최소 요구 사항은 다음과 같습니다.

* 12GBps 처리량
* 512MB 내부 배터리 백업 또는 플래시(SuperCAP) 캐시
* Write Back 모드로 구성됨:
+
** 장애 복구 모드를 "Write Through"로 활성화(지원되는 경우)
** "항상 미리 읽기" 정책 활성화(지원되는 경우)


* RAID 컨트롤러 뒤의 모든 로컬 디스크는 단일 RAID 그룹으로 구성해야 합니다. 필요한 경우 여러 RAID 컨트롤러를 사용할 수 있습니다.
+
** 데이터 무결성을 유지하기 위해 기본적으로 사용되는 RAID 그룹의 로컬 드라이브 캐시를 해제합니다.


* LUN 구성은 다음 지침에 따라 수행해야 합니다.
+
** RAID 그룹 크기가 최대 LUN 크기인 64TB를 초과하는 경우 RAID 그룹 내에서 사용 가능한 모든 스토리지를 사용하는 동일한 크기의 LUN을 여러 개 구성해야 합니다.
** RAID 그룹 크기가 최대 LUN 크기인 64TB보다 작은 경우 RAID 그룹 내에서 사용 가능한 모든 스토리지를 사용하는 하나의 LUN을 구성해야 합니다.






== 소프트웨어 RAID 요구 사항

하이퍼바이저에 ONTAP Select 클러스터를 구축할 때 로컬 하드웨어 RAID 컨트롤러 대신 ONTAP Select이 제공하는 소프트웨어 RAID 기능을 활용할 수 있습니다. 소프트웨어 RAID를 사용하여 클러스터를 구축하기 전에 알아 두어야 할 몇 가지 요구 사항과 제한 사항이 있습니다.



=== 일반 요구 사항

소프트웨어 RAID 배포 환경은 다음과 같은 핵심 요구 사항을 충족해야 합니다.

* VMware ESXi 8.0 GA(빌드 20513097) 이상
* ONTAP Select 프리미엄 라이센스 이상
* 로컬 SSD 드라이브만 지원합니다
* 루트 및 데이터 애그리게이트에서 시스템 디스크 분리
* 호스트에 하드웨어 RAID 컨트롤러가 없습니다



NOTE: 하드웨어 RAID 컨트롤러가 있는 경우 를 참조하십시오 link:concept_stor_concepts_chars.html["심층 분석 스토리지"] 섹션을 참조하십시오.



=== ESXi 관련 요구 사항

* VMware ESXi 8.0 GA(빌드 20513097) 이상
* VMware VMotion, HA 및 DRS는 지원되지 않습니다
* ONTAP Select 9.4 이하 버전에서 업그레이드된 노드에서는 소프트웨어 RAID를 사용할 수 없습니다. 이 경우 소프트웨어 RAID 배포를 위한 새 노드를 만들어야 합니다.




=== KVM 관련 요구 사항

또한 특정 소프트웨어 패키지 구성 요구 사항이 있습니다. 를 참조하십시오 link:https://docs.netapp.com/us-en/ontap-select/kvm-host-configuration-and-preparation-checklist.html#prepare-linux-server["리눅스 서버 준비"] 자세한 내용은 다음 단계를 참조하세요.

KVM에 대한 미디어 기대치:: 사용되는 SSD 플래시 저장 장치는 다음과 같은 추가 요구 사항을 충족해야 합니다.
+
--
* SSD 장치는 다음 방법을 통해 Linux 호스트에 정확하고 지속적으로 보고해야 합니다.
+
** #cat/sys/block//queue/rotation. #cat/sys/block/<device>
+
이러한 명령에 대해 보고된 값은 '0'이어야 합니다.



* 장치가 HBA에 연결되어 있거나 경우에 따라 JBOD 모드에서 작동하도록 구성된 RAID 컨트롤러에 연결되어 있어야 합니다. RAID 컨트롤러를 사용하는 경우 장치 기능은 RAID 기능을 겹치지 않고 호스트를 통과해야 합니다. JBOD 모드에서 RAID 컨트롤러를 사용할 경우 RAID 설명서를 검토하거나 공급업체에 문의하여 장치가 회전 속도를 '0'으로 보고하는지 확인해야 합니다.
* 두 가지 스토리지 구성 요소가 있습니다.
+
** 가상 머신 스토리지
+
ONTAP Select 가상 머신을 호스팅하는 데 사용되는 시스템 데이터가 포함된 LVM 풀(스토리지 풀)입니다. LVM 풀은 내구성이 높은 플래시 디바이스를 통해 지원되어야 하며 SAS, SATA 또는 NVMe일 수 있습니다. 성능 향상을 위해 NVMe 장치를 사용하는 것이 좋습니다.

** 데이터 디스크
+
데이터 관리에 사용되는 SAS 또는 SATA SSD 드라이브 세트입니다. SSD 장치는 엔터프라이즈급 내구성을 갖추어야 합니다. NVMe 인터페이스는 지원되지 않습니다.



* 모든 장치는 512BPS로 포맷해야 합니다.


--




=== ONTAP Select 노드 구성

루트 및 데이터 애그리게이트에서 시스템 디스크를 분리하려면 각 ONTAP Select 노드 및 하이퍼바이저 호스트를 다음과 같이 구성해야 합니다.

* 시스템 스토리지 풀 생성 ONTAP Select 시스템 데이터에 대한 스토리지 풀을 생성해야 합니다. ONTAP Select 노드 구성의 일부로 스토리지 풀을 연결해야 합니다.
* 필요한 물리 디스크 연결 하이퍼바이저 호스트에는 필요한 SSD 디스크가 연결되어 있어야 하며 ONTAP Select 가상 머신에서 사용할 수 있어야 합니다. 이러한 드라이브에는 루트 및 데이터 애그리게이트가 포함됩니다. ONTAP Select 노드 구성의 일부로 스토리지 디스크를 연결해야 합니다.




== 스토리지 용량 제한

ONTAP Select 배포를 계획할 때 스토리지 할당 및 사용과 관련된 제한 사항을 숙지해야 합니다.

가장 중요한 스토리지 제한은 아래에 나와 있습니다. 또한 보다 자세한 내용은 를 검토해야 link:https://mysupport.netapp.com/matrix/["상호 운용성 매트릭스 툴"^]합니다.


TIP: ONTAP Select는 스토리지 할당 및 사용과 관련된 몇 가지 제한 사항을 적용합니다. ONTAP Select 클러스터를 구축하거나 라이센스를 구입하기 전에 먼저 이러한 제한 사항을 숙지해야 합니다. 를 참조하십시오 link:https://docs.netapp.com/us-en/ontap-select/concept_lic_evaluation.html["라이센스"] 섹션을 참조하십시오.



=== 물리적 스토리지 용량을 계산합니다

ONTAP Select 스토리지 용량은 ONTAP Select 가상 머신에 연결된 가상 데이터 및 루트 디스크의 총 허용 크기에 해당합니다. 용량을 할당할 때는 이 점을 고려해야 합니다.



=== 단일 노드 클러스터의 최소 스토리지 용량

단일 노드 클러스터의 노드에 할당된 스토리지 풀의 최소 크기는 다음과 같습니다.

* 평가: 500GB
* 운영: 1.0TB


운영 구축을 위한 최소 할당은 사용자 데이터에 대해 1TB를, 다양한 ONTAP Select 내부 프로세스에 사용되는 약 266GB로 구성되며, 이는 필요한 오버헤드로 간주됩니다.



=== 다중 노드 클러스터의 최소 스토리지 용량

다중 노드 클러스터의 각 노드에 할당된 스토리지 풀의 최소 크기는 다음과 같습니다.

* 평가: 1.9TB
* 운영: 2.0TB


운영 구축을 위한 최소 할당량은 사용자 데이터에 대해 2TB로 구성되며, 다양한 ONTAP Select 내부 프로세스에 사용되는 약 266GB는 필수 오버헤드로 간주됩니다.

[NOTE]
====
HA 쌍의 각 노드는 동일한 스토리지 용량을 가져야 합니다.

HA 쌍의 스토리지 용량을 예측할 때는 모든 애그리게이트(루트 및 데이터)가 미러링된다는 것을 고려해야 합니다. 그 결과 애그리게이트의 각 플렉스는 동일한 양의 스토리지를 사용합니다.

예를 들어, 2TB 애그리게이트를 생성할 경우 라이센스가 부여된 총 스토리지 용량의 2TB를 2개의 plex 인스턴스(Plex 0의 경우 2TB, Plex 1의 경우 2TB) 또는 4TB에 할당합니다.

====


=== 스토리지 용량 및 여러 스토리지 풀

로컬 직접 연결 스토리지, VMware vSAN 또는 외부 스토리지 어레이를 사용할 때 최대 400TB의 스토리지를 사용하도록 각 ONTAP Select 노드를 구성할 수 있습니다. 그러나 직접 연결 스토리지 또는 외부 스토리지 시스템을 사용할 경우 단일 스토리지 풀의 최대 크기는 64TB입니다. 따라서 이러한 상황에서 64TB 이상의 스토리지를 사용하려는 경우 다음과 같이 여러 스토리지 풀을 할당해야 합니다.

* 클러스터 생성 프로세스 중에 초기 스토리지 풀을 할당합니다
* 하나 이상의 추가 스토리지 풀을 할당하여 노드 스토리지를 늘립니다



NOTE: 각 스토리지 풀에서 2% 버퍼가 사용되지 않고 용량 라이센스가 필요하지 않습니다. 용량 한도를 지정하지 않는 한 ONTAP Select에서는 이 스토리지를 사용하지 않습니다. 용량 한도를 지정하면 지정된 양이 2% 버퍼 영역에 포함되지 않는 한 해당 스토리지 양이 사용됩니다. 스토리지 풀의 모든 공간을 할당하려고 할 때 가끔 발생하는 오류를 방지하기 위해 버퍼가 필요합니다.



=== 스토리지 용량 및 VMware vSAN

VMware vSAN을 사용할 경우 데이터 저장소가 64TB보다 클 수 있습니다. 그러나 ONTAP Select 클러스터를 생성할 때는 처음에 최대 64TB까지 할당할 수 있습니다. 클러스터를 생성한 후 기존 vSAN 데이터 저장소에서 추가 스토리지를 할당할 수 있습니다. ONTAP Select에서 사용할 수 있는 vSAN 데이터스토어 용량은 VM 스토리지 정책 집합을 기반으로 합니다.



=== 모범 사례

하이퍼바이저 코어 하드웨어와 관련하여 다음 권장 사항을 고려해야 합니다.

* 단일 ONTAP Select 애그리게이트의 모든 드라이브는 유형이 같아야 합니다. 예를 들어, HDD와 SSD 드라이브를 동일한 Aggregate에서 혼합하면 안 됩니다.




== 플랫폼 라이센스에 따른 추가 디스크 드라이브 요구 사항

선택한 드라이브는 플랫폼 라이센스 제공에 따라 제한됩니다.


NOTE: 디스크 드라이브 요구 사항은 소프트웨어 RAID와 로컬 RAID 컨트롤러 및 드라이브를 사용할 때 적용됩니다. 이러한 요구 사항은 ONTAP Select vNAS 솔루션을 통해 액세스하는 외부 스토리지에는 적용되지 않습니다.

.표준
* 8 ~ 60개의 내장 HDD(NL-SAS, SATA, 10K SAS)


.프리미엄
* 8 ~ 60개의 내장 HDD(NL-SAS, SATA, 10K SAS)
* 4~60개의 내부 SSD


.Premium XL
* 8 ~ 60개의 내장 HDD(NL-SAS, SATA, 10K SAS)
* 4~60개의 내부 SSD
* 4~14개의 내부 NVMe



NOTE: 로컬 DAS 드라이브를 사용하는 소프트웨어 RAID는 프리미엄 라이센스(SSD 전용) 및 프리미엄 XL 라이센스(SSD 또는 NVMe)로 지원됩니다.



== 소프트웨어 RAID가 장착된 NVMe 드라이브

소프트웨어 RAID에서 NVMe SSD 드라이브를 사용하도록 구성할 수 있습니다. 환경은 다음 요구 사항을 충족해야 합니다.

* 지원되는 Deploy 관리 유틸리티를 사용한 ONTAP Select
* Premium XL 플랫폼 라이센스 제공 또는 90일 평가판 라이센스
* VMware ESXi 버전 8.0 이상
* 사양 1.0 이상을 준수하는 NVMe 장치


NVMe 드라이브를 사용하기 전에 수동으로 구성해야 합니다. 을 참조하십시오 link:task_chk_nvme_configure.html["호스트에서 NVMe 드라이브를 사용하도록 구성합니다"] 를 참조하십시오.
