---
sidebar: sidebar 
permalink: reference_plan_dep_vmware.html 
keywords: plan, planning, ontap select deploy, vmware requirements 
summary: VMware 환경에 ONTAP Select 배포 유틸리티를 설치하기 전에 고려해야 하는 VMware 환경 관련 몇 가지 요구 사항과 제한 사항이 있습니다. 
---
= 하이퍼바이저 호스트 고려 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
하이퍼바이저 호스트와 관련하여 고려해야 할 몇 가지 계획 문제가 있습니다.


CAUTION: NetApp 지원 부서의 지시가 없는 한 ONTAP Select 가상 시스템의 구성을 직접 수정해서는 안 됩니다. 가상 시스템은 배포 관리 유틸리티를 통해서만 구성 및 수정해야 합니다. NetApp의 지원 없이 구축 유틸리티 외부에서 ONTAP Select 가상 머신을 변경하면 가상 머신에 오류가 발생하고 사용할 수 없게 될 수 있습니다.



== 하이퍼바이저와 독립적입니다

ONTAP Select와 ONTAP Select Deploy 관리 유틸리티는 모두 하이퍼바이저와 독립적입니다.

다음 하이퍼바이저는 ONTAP Select와 ONTAP Select 배포 관리 둘 다에서 지원됩니다.

* VMware ESXi
* 커널 기반 가상 머신(KVM)



NOTE: 지원되는 플랫폼에 대한 자세한 내용은 하이퍼바이저별 계획 정보 및 릴리스 노트를 참조하십시오.

.ONTAP Select 노드용 하이퍼바이저 및 관리 유틸리티
Deploy 관리 유틸리티와 ONTAP Select 노드 모두 가상 머신으로 실행됩니다. 배포 유틸리티에 대해 선택하는 하이퍼바이저는 ONTAP Select 노드에 대해 선택하는 하이퍼바이저와 독립적입니다. 두 가지를 페어링할 때 완벽한 유연성이 있습니다.

* VMware ESXi에서 실행되는 Deploy 유틸리티를 사용하면 VMware ESXi 또는 KVM에서 ONTAP Select 클러스터를 생성하고 관리할 수 있습니다
* KVM에서 실행되는 배포 유틸리티를 통해 VMware ESXi 또는 KVM에서 ONTAP Select 클러스터를 생성하고 관리할 수 있습니다


.호스트당 하나 이상의 ONTAP Select 노드 인스턴스
각 ONTAP Select 노드는 전용 가상 머신으로 실행됩니다. 동일한 하이퍼바이저 호스트에서 여러 노드를 생성할 수 있으며 다음과 같은 제한이 있습니다.

* 단일 ONTAP Select 클러스터의 여러 노드를 동일한 호스트에서 실행할 수 없습니다. 특정 호스트의 모든 노드는 서로 다른 ONTAP Select 클러스터에 있는 노드여야 합니다.
* 외부 저장소를 사용해야 합니다.
* 소프트웨어 RAID를 사용하는 경우 호스트에 하나의 ONTAP Select 노드만 배포할 수 있습니다.


.클러스터 내의 노드에 대한 하이퍼바이저 정합성 보장
ONTAP Select 클러스터 내의 모든 호스트는 하이퍼바이저 소프트웨어의 동일한 버전과 릴리즈에서 실행되어야 합니다.

.각 호스트의 물리적 포트 수입니다
물리적 포트 1개, 2개 또는 4개를 사용하도록 각 호스트를 구성해야 합니다. 네트워크 포트를 구성할 때 유연성이 있지만 가능하면 다음 권장 사항을 따라야 합니다.

* 단일 노드 클러스터의 호스트에는 2개의 물리적 포트가 있어야 합니다.
* 다중 노드 클러스터의 각 호스트에는 4개의 물리적 포트가 있어야 합니다


.ONTAP Select를 ONTAP 하드웨어 기반 클러스터와 통합합니다
ONTAP Select 노드를 ONTAP 하드웨어 기반 클러스터에 직접 추가할 수는 없습니다. 하지만 선택적으로 ONTAP Select 클러스터와 하드웨어 기반 ONTAP 클러스터 간에 클러스터 피어링 관계를 설정할 수 있습니다.



== VMware 하이퍼바이저 환경

VMware 환경에 ONTAP Select 배포 유틸리티를 설치하기 전에 고려해야 하는 VMware 환경 관련 몇 가지 요구 사항과 제한 사항이 있습니다.

.ESXi 호스트 서버 하드웨어 요구 사항
ESXi 하이퍼바이저 호스트가 충족해야 하는 최소 리소스 요구 사항은 몇 가지가 있습니다. ONTAP Select가 구축된 호스트가 다음과 같은 기본 요구 사항을 충족하는지 확인해야 합니다.

* ESXi 서버:
+
** 하드웨어 및 소프트웨어는 64비트여야 합니다
** ONTAP Select 노드에 대해 정의된 것과 동일한 지원 버전을 준수해야 합니다


* 가상 CPU 2개
* 가상 메모리(4GB)
* 스토리지(40GB)
* DHCP 활성화(고정 IP 주소를 할당할 수도 있음)


.네트워크 연결
ONTAP Select Deploy 가상 머신 네트워크 인터페이스가 구성되어 있고 관리 IP 주소가 하나만 있는지 확인해야 합니다. DHCP를 사용하여 동적으로 IP 주소를 할당하거나 고정 IP 주소를 수동으로 구성할 수 있습니다.

구축 결정에 따라 구축 VM은 vCenter Server, ESXi 하이퍼바이저 호스트 및 관리하는 ONTAP Select 노드에 연결할 수 있어야 합니다. 필요한 트래픽을 허용하도록 방화벽을 구성해야 합니다.

Deploy는 VMware VIX API를 사용하여 vCenter 서버 및 ESXi 호스트와 통신합니다. 처음에는 TCP 포트 443에서 SSL을 통한 SOAP 연결을 설정합니다. 이 후 포트 902에서 SSL을 사용하여 연결이 열립니다. 또한 deploy는 ping 명령을 실행하여 지정한 IP 주소에 ESXi 호스트가 있는지 확인합니다.

Deploy는 다음 프로토콜을 사용하여 ONTAP Select 노드 및 클러스터 관리 IP 주소와 통신할 수 있어야 합니다.

* ping 명령(ICMP)
* SSH(포트 22)
* SSL(포트 443)


.IP 버전 4 지원
ONTAP Select 배포는 IP 버전 4(IPv4)만 지원합니다. IP 버전 6(IPv6)은 지원되지 않습니다. 이러한 제한은 다음과 같은 방법으로 ONTAP Select에 영향을 줍니다.

* 가상 시스템 배포 의 관리 LIF에 IPv4 주소를 할당해야 합니다.
* ONTAP LIF에서 IPv6을 사용하도록 구성된 ONTAP Select 노드를 구축할 수 없습니다.

