---
sidebar: sidebar 
permalink: reference_plan_ots_vnas.html 
keywords: plan, planning, vnas 
summary: ONTAP Select vNAS 사용과 관련하여 고려해야 할 몇 가지 계획 문제가 있습니다. 
---
= ONTAP Select vNAS 요구 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select vNAS는 ONTAP Select 가상 머신이 실행되는 하이퍼바이저 호스트 외부에 ONTAP Select 데이터 저장소를 제공할 수 있는 솔루션입니다. 이러한 원격 데이터 저장소는 VMware vSAN 또는 일반 외부 스토리지 시스템을 통해 액세스할 수 있습니다.



== 기본 요구 사항 및 제한 사항

ONTAP Select vNAS 솔루션은 모든 크기의 ONTAP Select 클러스터와 함께 사용할 수 있습니다.

하드웨어, 소프트웨어 및 기능 요구 사항을 비롯한 모든 관련 스토리지 구성 요소는 에 설명된 요구 사항을 준수해야 합니다
link:https://mysupport.netapp.com/matrix/["NetApp 상호 운용성 매트릭스 툴"^]. 또한 ONTAP Select는 iSCSI, NAS(NFSv3), 파이버 채널 및 FCoE(Fibre Channel over Ethernet)를 비롯하여 VMware 스토리지/SAN 호환성 설명서에 설명된 모든 외부 스토리지 어레이를 지원합니다. 외부 스토리지 지원은 ONTAP Select에서 지원하는 ESXi 버전에 의해 제한됩니다.

ONTAP Select vNAS를 사용하여 클러스터를 구축할 때 지원되는 VMware 기능은 다음과 같습니다.

* 마이그레이션
* 고가용성(HA)
* DRS(Distributed Resource Scheduler)



NOTE: 이러한 VMware 기능은 단일 노드 및 다중 노드 ONTAP Select 클러스터에서 지원됩니다. 다중 노드 클러스터를 구축할 때는 동일한 클러스터에 있는 두 개 이상의 노드가 동일한 하이퍼바이저 호스트에서 실행되지 않도록 해야 합니다.

다음 VMware 기능은 지원되지 않습니다.

* 내결함성(ft)
* 가상 데이터 저장소(VVOL)




== 구성 요구 사항

외부 스토리지(iSCSI, Fibre Channel, Fibre Channel over Ethernet)에서 VMFS 데이터 저장소를 사용하려는 경우 스토리지를 사용하도록 ONTAP Select를 구성하기 전에 VMFS 스토리지 풀을 생성해야 합니다. NFS 데이터 저장소를 사용하는 경우 별도의 VMFS 데이터 저장소를 생성할 필요가 없습니다. 모든 vSAN 데이터스토어는 동일한 ESXi 클러스터 내에서 정의되어야 합니다.


CAUTION: 호스트를 구성하거나 스토리지 추가 작업을 수행할 때 VMware vSAN 또는 외부 스토리지 배열의 모든 데이터 저장소에 대한 용량 제한을 제공해야 합니다. 지정하는 용량은 외부 스토리지의 허용되는 저장소 제한 범위 내에 있어야 합니다. 디스크 생성 작업 중에 용량 제한을 제공하지 않거나 외부 스토리지에 공간이 부족한 경우 오류가 발생합니다.



== 모범 사례

사용 가능한 VMware 설명서를 참조하여 ESXi 호스트에 대해 식별된 적절한 Best Practice를 준수하십시오. 추가 사항:

* ONTAP Select 네트워크 및 외부 스토리지에 대한 전용 네트워크 포트, 대역폭 및 vSwitch 구성 정의(iSCSI 또는 NFS 사용 시 VMware vSAN 및 일반 스토리지 어레이 트래픽)
* 용량 옵션을 구성하여 스토리지 사용률을 제한합니다(ONTAP Select는 외부 vNAS 데이터 저장소의 전체 용량을 사용할 수 없음).
* 가능한 경우 모든 일반 외부 스토리지 어레이가 사용 가능한 이중화 및 HA 기능을 사용하도록 합니다

