---
sidebar: sidebar 
permalink: reference_plan_dep_general.html 
keywords: plan, planning, ontap select deploy, general requirements 
summary: ONTAP Select 배포 관리 유틸리티 설치 계획의 일부로 고려해야 하는 몇 가지 일반적인 요구 사항이 있습니다. 
---
= ONTAP Select은 일반 요구 사항 및 계획을 배포합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 배포 관리 유틸리티 설치 계획의 일부로 고려해야 하는 몇 가지 일반적인 요구 사항이 있습니다.



== 배포 유틸리티를 ONTAP Select 클러스터와 페어링합니다

Deploy 유틸리티의 인스턴스를 ONTAP Select 클러스터와 페어링할 때 여러 가지 옵션이 있습니다.


NOTE: 모든 구축 시나리오에서 단일 ONTAP Select 클러스터와 클러스터의 노드는 Deploy 관리 유틸리티의 단일 인스턴스에서만 관리할 수 있습니다. Deploy 유틸리티의 두 개 이상의 다른 인스턴스는 클러스터를 관리할 수 없습니다.

.각 ONTAP Select 클러스터에 대한 유틸리티 인스턴스 1개
Deploy 유틸리티의 전용 인스턴스를 사용하여 각 ONTAP Select 클러스터를 구축하고 관리할 수 있습니다. 이 일대일 구성을 사용하면 각 유틸리티와 클러스터 쌍 간에 명확한 구분이 가능합니다. 이 구성은 더 작은 장애 도메인을 사용하여 높은 수준의 격리를 제공합니다.

.여러 ONTAP Select 클러스터에 대한 유틸리티 인스턴스 1개
배포 유틸리티의 단일 인스턴스를 사용하여 조직 내에서 여러 ONTAP Select 클러스터를 배포하고 관리할 수 있습니다. 이 일대다 구성을 사용하면 모든 처리 및 구성 데이터가 배포 유틸리티의 동일한 인스턴스에서 관리됩니다.


NOTE: Deploy 유틸리티의 한 인스턴스는 최대 400개의 ONTAP Select 노드 또는 100개의 클러스터를 관리할 수 있습니다.



== KVM 환경과 관련된 요구 사항

KVM 하이퍼바이저 환경에 배포 관리 유틸리티를 설치하기 전에 기본 요구 사항을 검토하고 배포 준비를 해야 합니다.

.배포 요구 사항 및 제한 사항
ONTAP Select Deploy 유틸리티를 KVM 환경에 설치할 때 고려해야 할 몇 가지 요구 사항 및 제한 사항이 있습니다.

.Linux KVM 호스트 서버 하드웨어 요구 사항
Linux KVM 하이퍼바이저 호스트가 충족해야 하는 최소 리소스 요구 사항은 몇 가지가 있습니다. ONTAP Select를 구축하는 호스트가 다음 기본 요구사항을 충족하는지 확인합니다.

* Linux 서버:
+
** 하드웨어와 소프트웨어는 64비트여야 합니다
** 서버는 ONTAP Select 노드에 대해 정의된 것과 동일한 지원 버전을 준수해야 합니다


* 가상 CPU 2개
* 가상 메모리(4GB)
* 스토리지(40GB)
* "DHCP(Dynamic Host Configuration Protocol)가 활성화되었습니다(고정 IP 주소를 할당할 수도 있음).


.네트워크 연결
Deploy Virtual Machine 네트워크 인터페이스가 구성되어 있고 관리하는 ONTAP Select 호스트에 연결할 수 있는지 확인합니다.

.IP 버전 4 지원
ONTAP Select 배포는 IP 버전 4(IPv4)만 지원합니다. IP 버전 6(IPv6)은 지원되지 않습니다. 이러한 제한은 다음과 같은 방법으로 ONTAP Select에 영향을 줍니다.

* 구축된 VM의 관리 LIF에 IPv4 주소를 할당해야 합니다.
* ONTAP LIF에서 IPv6을 사용하도록 구성된 ONTAP Select 노드를 구축할 수 없습니다.




== 필수 구성 정보입니다

배포 계획의 일환으로 ONTAP Select 배포 관리 유틸리티를 설치하기 전에 필요한 구성 정보를 확인해야 합니다.

.배포 VM의 이름입니다
VM에 사용할 이름입니다.

.Linux KVM 호스트의 이름입니다
Deploy 유틸리티가 설치된 Linux KVM 호스트

.스토리지 풀의 이름입니다
VM 파일이 있는 스토리지 풀입니다(약 40GB 필요).

.VM을 위한 네트워크
배포 VM이 연결된 네트워크입니다.



== 네트워크 구성 정보(옵션

배포 VM은 기본적으로 DHCP를 사용하여 구성됩니다. 그러나 필요한 경우 VM에 대한 네트워크 인터페이스를 수동으로 구성할 수 있습니다.

.호스트 이름입니다
호스트의 이름입니다.

.호스트 IP 주소입니다
정적 IPv4 주소입니다.

.서브넷 마스크
서브네트워크 마스크는 VM이 속한 네트워크를 기반으로 합니다.

.게이트웨이
기본 게이트웨이 또는 라우터

.1차 DNS 서버
기본 도메인 이름 서버입니다.

.보조 DNS 서버
보조 도메인 이름 서버입니다.

.도메인 검색
사용할 검색 도메인입니다.



== 자격 증명 저장소를 사용하여 인증합니다

ONTAP Select Deploy 자격 증명 저장소는 계정 정보를 보관하는 데이터베이스 저장소입니다. Deploy는 계정 자격 증명을 사용하여 클러스터 생성 및 관리의 일부로 호스트 인증을 수행합니다. ONTAP Select 배포를 계획할 때 자격 증명 저장소가 어떻게 사용되는지 알고 있어야 합니다.


NOTE: 계정 정보는 AES 암호화 알고리즘 및 SHA-256 해싱 알고리즘을 사용하여 데이터베이스에 안전하게 저장됩니다.

.자격 증명의 유형입니다
지원되는 자격 증명 유형은 다음과 같습니다.

* ONTAP Select 노드를 VMware ESXi에 직접 구축할 때 하이퍼바이저 호스트를 인증하는 데 사용되는 호스트입니다
* VMware vCenter에서 호스트를 관리할 때 ESXi에 ONTAP Select 노드를 구축하는 과정에서 vCenter Server를 인증하는 데 사용되는 vCenter입니다


.액세스
하이퍼바이저 호스트 추가와 같은 배포를 사용하여 일반 관리 작업을 수행하는 과정에서 자격 증명 저장소에 내부적으로 액세스합니다. 웹 배포 사용자 인터페이스 및 CLI를 통해 자격 증명 저장소를 직접 관리할 수도 있습니다.
