---
sidebar: sidebar 
permalink: reference_plan_ots_networking.html 
keywords: plan, planning, networking, network, drivers, vmxnet3, cluster mtu, firewall 
summary: ONTAP Select를 구축하기 전에 하이퍼바이저 네트워크를 올바르게 구성해야 합니다. 
---
= 네트워킹 고려 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select를 구축하기 전에 하이퍼바이저 네트워크를 올바르게 구성해야 합니다.



== 가상 스위치 옵션

각 ONTAP Select 호스트에서 외부 네트워크 및 내부 네트워크를 지원하도록 가상 스위치를 구성해야 합니다(다중 노드 클러스터만 해당). 다중 노드 클러스터를 구축할 때는 내부 클러스터 네트워크에서 네트워크 연결을 테스트해야 합니다.


NOTE: 하이퍼바이저 호스트에서 vSwitch를 구성하는 방법과 고속 인터페이스 기능에 대한 자세한 내용은 을 참조하십시오 link:concept_nw_concepts_chars.html["딥 다이브 네트워킹"] 섹션을 참조하십시오.



== VMXNET3으로 업그레이드

Deploy 2.10을 사용하는 ONTAP Select 9.5부터 VMXNET3은 VMware ESXi의 새 클러스터 구축에 포함된 기본 네트워크 드라이버입니다. 기존 ONTAP Select 노드를 버전 9.5 이상으로 업그레이드하면 드라이버가 자동으로 업그레이드되지 않습니다.


NOTE: 지금은 VMXNET3으로 업그레이드할 필요가 없습니다. 그러나 드라이버를 업그레이드하도록 선택한 경우에는 수동으로 업그레이드를 수행해야 합니다. 이 경우 NetApp 지원 팀에 지원을 요청하십시오.



== 클러스터 MTU

별도의 내부 네트워크를 사용하여 다중 노드 클러스터의 ONTAP Select 노드를 연결합니다. 일반적으로 이 네트워크의 MTU 크기는 9000입니다. 그러나 이 MTU 크기가 ONTAP Select 노드를 연결하는 네트워크에 비해 너무 큰 경우가 있습니다. 더 작은 프레임을 수용하기 위해 내부 네트워크에서 ONTAP Select가 사용하는 MTU 크기는 7500-9000 바이트 범위에 포함될 수 있습니다.

MTU 크기는 클러스터 생성 페이지의 클러스터 세부 정보 섹션에 표시됩니다. 값은 다음과 같이 배포 관리 유틸리티에 의해 결정됩니다.

. 초기 기본값은 9000입니다.
. HA 쌍에 대한 호스트 및 네트워크를 추가하면 네트워크에 있는 vSwitch의 구성에 따라 필요에 따라 MTU 값이 줄어듭니다.
. 모든 HA 쌍을 추가하고 클러스터를 생성할 준비가 완료되면 클러스터의 마지막 클러스터 MTU 값이 설정됩니다.



NOTE: 필요한 경우 네트워크 설계에 따라 클러스터 MTU 값을 수동으로 설정할 수 있습니다.



== 표준 vSwitch가 있는 NIC 호스트 2개

2개의 NIC 구성에서 ONTAP Select 성능을 향상시키려면 2개의 포트 그룹을 사용하여 내부 및 외부 네트워크 트래픽을 격리해야 합니다. 이 권장 사항은 다음과 같은 특정 구성에 적용됩니다.

* ONTAP Select 다중 노드 클러스터
* NIC 2개(NIC1 및 NIC2)
* 표준 vSwitch


이 환경에서는 다음과 같이 두 개의 포트 그룹을 사용하여 트래픽을 구성해야 합니다.

.포트 그룹 1
* 내부 네트워크(클러스터, RSM, HA-IC 트래픽)
* NIC1이 활성 상태입니다
* 대기 모드에서 NIC2


.포트 그룹 2
* 외부 네트워크(데이터 및 관리 트래픽)
* NIC1이 대기 모드에 있습니다
* NIC2가 활성 상태입니다


를 참조하십시오 link:concept_nw_concepts_chars.html["딥 다이브 네트워킹"] 두 개의 NIC 배포에 대한 자세한 내용은 섹션을 참조하십시오.



== 표준 vSwitch가 있는 4개의 NIC 호스트

4개 NIC 구성에서 ONTAP Select 성능을 향상시키려면 4개 포트 그룹을 사용하여 내부 및 외부 네트워크 트래픽을 격리해야 합니다. 이 권장 사항은 다음과 같은 특정 구성에 적용됩니다.

* ONTAP Select 다중 노드 클러스터
* NIC 4개(NIC1, NIC2, NIC3 및 NIC4)
* 표준 vSwitch


이 환경에서는 다음과 같이 4개의 포트 그룹을 사용하여 트래픽을 구성해야 합니다.

.포트 그룹 1
* 내부 네트워크(클러스터, RSM 트래픽)
* NIC1이 활성 상태입니다
* 대기 모드에서 NIC2, NIC3, NIC4


.포트 그룹 2
* 내부 네트워크(클러스터, HA-IC 트래픽)
* NIC3이 활성 상태입니다
* 대기 모드에서 NIC1, NIC2, NIC4


.포트 그룹 3
* 외부 네트워크(데이터 및 관리 트래픽)
* NIC2가 활성 상태입니다
* 대기 모드에서 NIC1, NIC3, NIC4


.포트 그룹 4
* 외부 네트워크(데이터 트래픽)
* NIC4가 활성 상태입니다
* 대기 모드에서 NIC1, NIC2, NIC3


를 참조하십시오 link:concept_nw_concepts_chars.html["딥 다이브 네트워킹"] 섹션을 참조하십시오.



== 네트워크 트래픽 요구 사항

ONTAP Select 배포 환경의 여러 참가자 간에 네트워크 트래픽이 흐르도록 방화벽이 올바르게 구성되어 있는지 확인해야 합니다.

ONTAP Select 배포의 일부로 네트워크 트래픽을 교환하는 여러 참가자 또는 엔터티가 있습니다. 이러한 정보는 네트워크 트래픽 요구 사항에 대한 요약 설명에서 소개되고 사용됩니다.

* ONTAP Select 배포 관리 유틸리티를 배포합니다
* vSphere/ESXi 클러스터 구축에서 호스트를 관리하는 방법에 따라 vSphere 서버 또는 ESXi 호스트 중 하나입니다
* 하이퍼바이저 서버 ESXi 하이퍼바이저 호스트
* OTS 노드 ONTAP Select 노드
* OTS 클러스터 ONTAP Select 클러스터
* Admin WS 로컬 관리 워크스테이션


다음 표에서는 ONTAP Select 배포를 위한 네트워크 트래픽 요구 사항에 대해 설명합니다.

[cols="20,45,35"]
|===
| 프로토콜/포트 | 방향 | 설명 


| TLS(443) | vCenter Server(관리되는) 또는 ESXi(관리되지 않는)에 구축 | VMware VIX API입니다 


| 902 | vCenter Server(관리되는) 또는 ESXi(관리되지 않는)에 구축 | VMware VIX API입니다 


| ICMP | 하이퍼바이저 서버에 구축 | Ping을 클릭합니다 


| ICMP | 각 OTS 노드에 배포합니다 | Ping을 클릭합니다 


| SSH(22) | 각 OTS 노드에 대한 관리 WS | 관리 


| TLS(443) | OTS 노드 및 클러스터에 배포합니다 | ONTAP에 액세스합니다 


| TLS(443) | 배포할 각 OTS 노드 | 배포 액세스 


| iSCSI(3260) | 배포할 각 OTS 노드 | 중재자/메일박스 디스크 
|===