---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: ONTAP Select은 대부분의 ONTAP 기능을 완벽하게 지원합니다. 대부분의 ONTAP 기능은 클러스터를 구축할 때 각 노드에 대해 자동으로 라이센스가 부여됩니다. 그러나 일부 기능에는 별도의 라이센스가 필요합니다. 
---
= ONTAP 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select은 대부분의 ONTAP 기능을 완벽하게 지원합니다. 대부분의 ONTAP 기능은 클러스터를 구축할 때 각 노드에 대해 자동으로 라이센스가 부여됩니다. 그러나 일부 기능에는 별도의 라이센스가 필요합니다.


NOTE: 하드웨어별 종속 관계가 있는 ONTAP 기능은 일반적으로 ONTAP Select에서 지원되지 않습니다.



== ONTAP 기능은 기본적으로 자동으로 활성화됩니다

다음 기능은 ONTAP Select에 포함되어 있으며 기본적으로 라이센스가 부여됩니다.

* NVMe over TCP
* NFS 를 참조하십시오
* CIFS를 선택합니다
* iSCSI
* SnapMirror를 참조하십시오
* SnapVault
* 플랙스클론
* SnapRestore
* 중복제거 및 압축
* ONTAP 멀티 테넌시 기능
* ONTAP S3
* NetApp 볼륨 암호화(제한 없는 국가만 해당)




== ONTAP 기능은 별도로 라이센스가 부여됩니다

다음을 포함하여 기본적으로 활성화되지 않은 모든 ONTAP 기능에 대해 별도의 라이센스를 취득해야 합니다.

* SnapLock Enterprise(ONTAP Select에 대해서는 SnapLock 규정 준수가 지원되지 않음)
* FabricPool
* 데이터 가용성 서비스
* FlexCache(무료)
* SyncMirror(무료)
* MetroCluster SDS(ONTAP Select 프리미엄 라이센스 오퍼링)



NOTE: StorageGRID Webscale을 사용할 경우 FabricPool 라이센스가 필요하지 않습니다.

.관련 정보
* link:concept_ots_overview.html#comparing-ontap-select-and-ontap-9["ONTAP Select와 ONTAP 비교 9"]

