---
sidebar: sidebar 
permalink: sizing-capacity-pool-license.html 
keywords: license, licensing, Capacity Tiers, usable, space 
summary: Capacity Tiers 라이센스는 각 노드에서 관리하는 기본 디스크 용량을 기준으로 하며, 노드, HA 쌍 또는 클러스터의 사용 가능한 용량을 기준으로 하지 않습니다. 각 Capacity Tiers 라이센스는 지정된 용량에 대해 개별 노드 일련 번호에 할당되며, 관련 지원 계약이 필요합니다. 
---
= ONTAP Select의 용량 풀 라이센스 크기 결정
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
용량 풀 라이선스의 허가 용량은 최소 2TB부터 시작하여 TB 단위로 제공됩니다. 허가 용량은 사용 가능한 공간에 오버헤드 계수를 곱하여 계산합니다. 오버헤드 계수는 사용 가능한 공간에서 차감되는 ONTAP Select 소프트웨어 오버헤드 용량을 추정한 값이며, NVMe, SSD, HDD 또는 가상 드라이브의 ONTAP Select 용량을 결정하는 데 적용됩니다. 오버헤드 계수는 단일 노드 클러스터와 다중 노드(HA 쌍 기반) 클러스터 간에 차이가 있습니다.

* 단일 노드 클러스터의 오버헤드 계수는 1.13입니다.
* 다중 노드 클러스터의 오버헤드 계수는 2.67입니다


배포에 필요한 용량을 충분히 확보하려면 사용 가능한 공간을 기준으로 라이선스 용량을 계산해야 합니다. 예를 들어, HA 쌍에 20TB의 사용 가능한 용량(노드당 10TB)이 필요한 경우:

* HA 쌍을 사용하면 이중화를 위해 두 노드 간에 데이터가 복제되므로, HA 쌍에서 사용 가능한 데이터 20TB를 확보하려면 노드 중 하나가 오프라인 상태가 될 경우를 대비하여 노드당 20TB가 필요합니다.
* 2.67이라는 계수는 각 노드의 용량을 두 배로 늘리고 ONTAP Select가 작동하는 데 필요한 오버헤드 용량(0.67)을 추가합니다.
* 노드당 라이선스 용량은 27TB(10 x 2.67 = 26.7)입니다. HA 쌍의 경우, 20TB의 사용 가능한 용량을 확보하려면 27TB 라이선스 두 개가 필요합니다.


[cols="25,30,45"]
|===
| 설명 | 단일 노드 | HA 쌍 또는 HA 쌍과 단일 노드의 혼합 


| 사용 가능한 공간 | 20 TB | 단일 노드 클러스터당 10TB, HA 쌍의 경우 20TB 


| 라이센스 공간 | 23TB(20 x 1.13 = 22.6, 다음 전체 TB로 반올림) | 54TB(20 x 2.67 = 53.4, 다음 전체 TB로 반올림) 


| 노드당 최대 사용 가능 공간 *참고*: 노드 또는 HA 쌍당 최대 관리 공간은 400TB입니다. | 353TB(400 / 1.13)  a| 
클러스터 내 단일 노드당:

149TB(400 / 2.67)

클러스터의 HA 쌍당:

298TB(2 x 149)

|===
.다음 단계
link:task_lic_acquire_cp.html["ONTAP Select용 Capacity Pools 라이센스 획득"]
