---
sidebar: sidebar 
permalink: task_install_deploy.html 
keywords: install, installing, ontap select deploy, deploy administration utility, deploy utility 
summary: ONTAP Select 배포 관리 유틸리티를 설치하고 유틸리티를 사용하여 ONTAP Select 클러스터를 생성해야 합니다. 
---
= ONTAP Select Deploy를 설치합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 배포 관리 유틸리티를 설치하고 유틸리티를 사용하여 ONTAP Select 클러스터를 생성해야 합니다.



== 가상 머신 이미지를 다운로드합니다

NetApp Support 사이트에서 ONTAP Select 패키지를 다운로드할 수 있습니다.

.시작하기 전에
https://mysupport.netapp.com/site/user/registration["등록된 NetApp 지원 사이트 계정이 있습니다"^]..

.이 작업에 대해
ONTAP Select Deploy 관리 유틸리티는 OVF(Open Virtualization Format) 표준을 기반으로 하는 VM(가상 머신)으로 패키징됩니다. 단일 압축 파일에는 접미사가 있습니다 `ova`. VM은 ONTAP Select 노드의 배포 서버 및 설치 이미지를 제공합니다.

.단계
. 에 액세스합니다 link:https://mysupport.netapp.com/site/["NetApp Support 사이트"^] 웹 브라우저를 사용하여 로그인합니다.
. 메뉴에서 * 다운로드 * 를 선택한 다음 드롭다운 메뉴에서 * 다운로드 * 를 선택합니다.
. 다운로드 페이지의 모든 제품 A-Z에서 문자 * O * 를 선택합니다.
. 아래로 스크롤하여 * ONTAP Select * 를 선택합니다.
. 원하는 패키지 릴리스를 선택합니다.
. 최종 사용자 사용권 계약(EULA)을 검토하고 * Accept & Continue * 를 선택합니다.
. 적절한 패키지를 선택하여 다운로드하고 필요에 따라 모든 프롬프트에 응답합니다.




== ONTAP Select 배포 OVA 서명을 확인합니다

설치 패키지를 설치하기 전에 ONTAP Select OVA(Open Virtualization Appliance) 서명을 확인해야 합니다.

.시작하기 전에
시스템이 다음 요구 사항을 충족하는지 확인합니다.

* 기본 검증용 OpenSSL 버전 1.0.2에서 3.0
* OCSP(Online Certificate Status Protocol) 확인을 위한 공용 인터넷 액세스


.단계
. NetApp Support 사이트의 제품 다운로드 페이지에서 다음 파일을 다운로드하십시오.
+
[cols="2*"]
|===
| 파일 | 설명 


| `ONTAP-Select-Deploy-Production.pub` | 서명을 확인하는 데 사용되는 공개 키입니다. 


| `csc-prod-chain-ONTAP-Select-Deploy.pem` | 공공 CA(인증 기관) 신뢰 체인으로, 


| `csc-prod-ONTAP-Select-Deploy.pem` | 키를 생성하는 데 사용되는 인증서입니다. 


| `ONTAPdeploy.ova` | ONTAP Select용 제품 설치 실행 파일 


| `ONTAPdeploy.ova.sig` | SHA-256 알고리즘이 해시된 후 를 사용하여 RSA(Remote Support Agent)에 의해 서명됩니다 `csc-prod` 설치 프로그램의 키 및 서명 
|===
. 를 확인합니다 `ONTAPdeploy.ova.sig` 파일에서 연결된 인증서 및 유효성 검사 명령을 사용하고 있습니다.
. 다음 명령을 사용하여 서명을 확인합니다.
+
[listing]
----
openssl dgst  -sha256 -verify ONTAP-Select-Deploy-Production.pub -signature ONTAPdeploy.ova.sig  ONTAPdeploy.ova
----




== 가상 머신을 구축합니다

OVF VM 이미지를 사용하여 ONTAP Select Deploy VM을 설치하고 시작해야 합니다. 설치 프로세스의 일부로 DHCP 또는 고정 IP 구성을 사용하도록 네트워크 인터페이스를 구성합니다.

.시작하기 전에
ESXi 하이퍼바이저의 경우 ONTAP Select Deploy VM:

* VMware Client Integration Plugin을 설치하거나 필요에 따라 유사한 구성을 수행하여 브라우저에서 OVF 기능을 설정합니다
* 배포 VM에 IP 주소를 동적으로 할당하려는 경우 VMware 환경에서 DHCP를 사용하도록 설정합니다


ESXi 및 KVM 하이퍼바이저의 경우 VM 이름, 외부 네트워크, 호스트 이름 등 VM을 생성할 때 사용할 구성 정보가 있어야 합니다. 정적 네트워크 구성을 정의할 때 다음과 같은 추가 정보가 필요합니다.

* 배포 VM의 IP 주소입니다
* 넷마스크
* 게이트웨이(라우터)의 IP 주소
* Primary DNS 서버의 IP 주소입니다
* 두 번째 DNS 서버의 IP 주소입니다
* DNS 검색 도메인


.이 작업에 대해
vSphere를 사용하는 경우 Deploy OVF template Wizard에는 네트워크 구성을 포함한 모든 구축 구성 정보를 제공하는 양식이 포함되어 있습니다. 그러나 이 양식을 사용하지 않도록 선택한 경우에는 배포 VM의 콘솔을 사용하여 네트워크를 구성할 수 있습니다.

.단계
수행할 단계는 ESXi 하이퍼바이저를 사용하는지 KVM 하이퍼바이저를 사용하는지에 따라 다릅니다.

[role="tabbed-block"]
====
.ESXi
--
. vSphere Client에 액세스하고 로그인합니다.
. 계층에서 적절한 위치로 이동하고 * Deploy OVF Template * 을 선택합니다.
. OVA 파일을 선택하고 환경에 적합한 옵션을 선택하여 OVF 템플릿 배포 마법사를 완료합니다.
+
관리자 계정의 암호를 정의해야 합니다. 배포 유틸리티에 로그인할 때 이 암호를 제공해야 합니다.

. VM이 배포되면 새 VM을 선택합니다. 배포 마법사에 입력한 내용에 따라 전원이 켜져 있지 않으면 수동으로 전원을 켭니다.
. 필요한 경우 VM 콘솔을 사용하여 배포 네트워크를 구성할 수 있습니다.
+
.. Console * 탭을 클릭하여 ESXi 호스트 설정 셸에 액세스하고 전원 켜기 프로세스를 모니터링합니다.
.. 다음 메시지가 표시될 때까지 기다립니다.
+
호스트 이름:

.. 호스트 이름을 입력하고 * Enter * 를 누릅니다.
.. 다음 메시지가 표시될 때까지 기다립니다.
+
admin 사용자의 암호를 입력합니다.

.. 암호를 입력하고 * Enter * 를 누릅니다.
.. 다음 메시지가 표시될 때까지 기다립니다.
+
DHCP를 사용하여 네트워킹 정보를 설정하시겠습니까? [n]:

.. 정적 IP 구성을 정의하려면 * n * 을 입력하고, DHCP를 사용하려면 * y * 를 입력하고 * Enter * 를 선택합니다.
.. 정적 구성을 선택하는 경우 필요에 따라 모든 네트워크 구성 정보를 제공합니다.




--
.KVM
--
. Linux 서버에서 CLI에 로그인합니다.
+
[listing]
----
ssh root@<ip_address>
----
. 새 디렉토리를 생성하고 원시 VM 이미지를 추출합니다.
+
[listing]
----
mkdir /home/select_deploy25
cd /home/select_deploy25
mv /root/<file_name> .
tar -xzvf <file_name>
----
. 배포 관리 유틸리티를 실행하는 KVM VM을 생성하고 시작합니다.
+
[listing]
----
virt-install --name=select-deploy --vcpus=2 --ram=4096 --os-variant=debian10 --controller=scsi,model=virtio-scsi --disk path=/home/deploy/ONTAPdeploy.raw,device=disk,bus=scsi,format=raw --network "type=bridge,source=ontap-br,model=virtio,virtualport_type=openvswitch" --console=pty --import --noautoconsole
----
. 필요한 경우 VM 콘솔을 사용하여 배포 네트워크를 구성할 수 있습니다.
+
.. VM 콘솔에 연결합니다.
+
[listing]
----
virsh console <vm_name>
----
.. 다음 메시지가 표시될 때까지 기다립니다.
+
[listing]
----
Host name :
----
.. 호스트 이름을 입력하고 * Enter * 를 선택합니다.
.. 다음 메시지가 표시될 때까지 기다립니다.
+
[listing]
----
Use DHCP to set networking information? [n]:
----
.. 정적 IP 구성을 정의하려면 * n * 을 입력하고, DHCP를 사용하려면 * y * 를 입력하고 * Enter * 를 선택합니다.
.. 정적 구성을 선택하는 경우 필요에 따라 모든 네트워크 구성 정보를 제공합니다.




--
====


== 배포 웹 인터페이스에 로그인합니다

웹 사용자 인터페이스에 로그인하여 배포 유틸리티를 사용할 수 있는지 확인하고 초기 구성을 수행해야 합니다.

.단계
. IP 주소 또는 도메인 이름을 사용하여 브라우저에서 배포 유틸리티를 가리킵니다.
+
'\https://<ip_address>/`

. 관리자(admin) 계정 이름 및 암호를 제공하고 로그인합니다.
. Welcome to*(ONTAP Select* 시작) 팝업 창이 표시되면 필수 구성 요소를 검토하고 *OK*를 선택하여 계속합니다.
. 처음 로그인하는 경우 vCenter에서 사용할 수 있는 마법사를 사용하여 Deploy를 설치하지 않은 경우 메시지가 표시되면 다음 구성 정보를 제공합니다.
+
** 관리자 계정의 새 암호(필수)
** AutoSupport(선택 사항)
** 계정 자격 증명이 있는 vCenter Server(선택 사항)




.관련 정보
* link:task_cli_signing_in.html["SSH를 사용하여 배포하려면 로그인하십시오"]
* link:deploy-evaluation-ontap-select-ovf-template.html["ONTAP Select 클러스터의 90일 평가 인스턴스를 구축합니다"]

