---
sidebar: sidebar 
permalink: task_install_deploy.html 
keywords: install, installing, ontap select deploy, deploy administration utility, deploy utility 
summary: ONTAP Select 배포 관리 유틸리티를 설치하고 유틸리티를 사용하여 ONTAP Select 클러스터를 생성해야 합니다. 
---
= ONTAP Select 배포 설치 중
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 배포 관리 유틸리티를 설치하고 유틸리티를 사용하여 ONTAP Select 클러스터를 생성해야 합니다.



== 가상 머신 이미지를 다운로드하는 중입니다

NetApp Support 사이트에서 ONTAP Select 패키지를 다운로드할 수 있습니다.

ONTAP Select Deploy 관리 유틸리티는 OVF(Open Virtualization Format) 표준을 기반으로 가상 머신으로 패키징됩니다. 압축된 파일 하나에는 난자(ova)라는 접미사가 붙어 있습니다.

.단계
. 웹 브라우저를 사용하여 NetApp 지원 사이트에 액세스하고 * 빠른 링크 * 를 클릭합니다.
. 상위 작업 * 에서 * 소프트웨어 다운로드 * 를 클릭하고 로그인합니다.
. 제품 찾기 * 를 클릭합니다.
. 아래로 스크롤하여 * ONTAP Select * 를 클릭합니다.
. 원하는 패키지 릴리스를 선택합니다.
. 최종 사용자 사용권 계약(EULA)을 검토하고 * 동의 및 계속 * 을 클릭합니다.
. 적절한 패키지를 선택하여 다운로드하고 필요에 따라 모든 프롬프트에 응답합니다.




== 가상 머신 구축

OVF 가상 머신 이미지를 사용하여 ONTAP Select Deploy 가상 머신을 설치하고 시작해야 합니다. 설치 프로세스의 일부로 DHCP 또는 고정 IP 구성을 사용하도록 네트워크 인터페이스를 구성해야 합니다.

ONTAP Select Deploy 가상 머신을 구축할 준비를 해야 합니다.

* VMware Client Integration Plugin을 설치하거나 필요에 따라 유사한 구성을 수행하여 브라우저에서 OVF 기능을 설정합니다
* 구축 가상 머신에 IP 주소를 동적으로 할당할 경우 VMware 환경에서 DHCP를 활성화했습니다


가상 머신 이름, 외부 네트워크 및 호스트 이름을 포함하여 가상 머신을 생성할 때 사용할 구성 정보가 있어야 합니다. 정적 네트워크 구성을 정의할 때 다음과 같은 추가 정보가 필요합니다.

* 구축 가상 머신의 IP 주소입니다
* 넷마스크
* 게이트웨이(라우터)의 IP 주소
* Primary DNS 서버의 IP 주소입니다
* 두 번째 DNS 서버의 IP 주소입니다
* DNS 검색 도메인


vSphere를 사용하는 경우 Deploy OVF template Wizard에는 네트워크 구성을 포함한 모든 구축 구성 정보를 제공하는 양식이 포함되어 있습니다. 그러나 이 양식을 사용하지 않도록 선택한 경우 가상 시스템 배포 콘솔을 사용하여 네트워크를 구성할 수 있습니다.

.단계
. vSphere Client에 액세스하고 로그인합니다.
. 계층에서 적절한 위치로 이동하고 * Deploy OVF Template * 을 선택합니다.
. OVA 파일을 선택하고 환경에 적합한 옵션을 선택하여 OVF 템플릿 배포 마법사를 완료합니다.
+
관리자 계정의 암호를 정의해야 합니다. 배포 유틸리티에 로그인할 때 이 암호를 제공해야 합니다.

. 가상 머신이 구축된 후 새 가상 머신을 선택하고 구축 마법사에 입력한 내용에 따라 아직 전원이 켜져 있지 않은 경우 전원을 켭니다.
. 필요한 경우 가상 머신 콘솔을 사용하여 배포 네트워크를 구성할 수 있습니다.
+
.. Console * 탭을 클릭하여 ESXi 호스트 설정 셸에 액세스하고 전원 켜기 프로세스를 모니터링합니다.
.. 다음 메시지가 표시될 때까지 기다립니다.
+
호스트 이름:

.. 호스트 이름을 입력하고 * Enter * 를 누릅니다.
.. 다음 메시지가 표시될 때까지 기다립니다.
+
admin 사용자의 암호를 입력합니다.

.. 암호를 입력하고 * Enter * 를 누릅니다.
.. 다음 메시지가 표시될 때까지 기다립니다.
+
DHCP를 사용하여 네트워킹 정보를 설정하시겠습니까? [n]:

.. 정적 IP 구성을 정의하려면 * n * 을 입력하고 DHCP를 사용하려면 y 를 입력한 다음 * Enter * 를 누릅니다.
.. 정적 구성을 선택하는 경우 필요에 따라 모든 네트워크 구성 정보를 제공합니다.






== 배포 웹 인터페이스에 로그인합니다

웹 사용자 인터페이스에 로그인하여 배포 유틸리티를 사용할 수 있는지 확인하고 초기 구성을 수행해야 합니다.

.단계
. IP 주소 또는 도메인 이름을 사용하여 브라우저에서 배포 유틸리티를 가리킵니다.
+
'\https://<ip_address>/`

. 관리자(admin) 계정 이름 및 암호를 제공하고 로그인합니다.
. ONTAP Select * 시작 * 팝업 창이 표시되면 필수 구성 요소를 검토하고 계속하려면 * 확인 * 을 클릭합니다.
. 처음 로그인하는 경우 vCenter에서 사용할 수 있는 마법사를 사용하여 배포를 설치하지 않은 경우 메시지가 표시되면 다음 구성 정보를 제공합니다.
+
** 관리자 계정의 새 암호(필수)
** AutoSupport(선택 사항)
** 계정 자격 증명이 있는 vCenter Server(선택 사항)




link:task_cli_signing_in.html["SSH를 사용하여 배포하려면 로그인합니다"]
