---
sidebar: sidebar 
permalink: task_cli_migrate_deploy.html 
keywords: administer, administering, cli, deploy, deploy instance, migrate 
summary: 명령줄 인터페이스를 사용하여 배포 관리 유틸리티의 기존 인스턴스를 새 가상 시스템으로 마이그레이션할 수 있습니다. 
---
= 배포 인스턴스를 새 가상 머신으로 마이그레이션합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
명령줄 인터페이스를 사용하여 배포 관리 유틸리티의 기존 인스턴스를 새 가상 시스템으로 마이그레이션할 수 있습니다.

이 절차는 원래 가상 머신의 구성 데이터를 사용하는 새 가상 머신을 생성하는 과정을 기반으로 합니다. 새 가상 머신과 원래 가상 머신은 Deploy 유틸리티의 버전과 릴리즈가 같아야 합니다. 배포 유틸리티의 다른 버전 및 릴리스로 마이그레이션할 수 없습니다.



== 배포 구성 데이터를 백업합니다

가상 머신 마이그레이션의 일부로 구축 구성 데이터의 백업을 생성해야 합니다. ONTAP Select 클러스터를 구축한 후 백업도 생성해야 합니다. 데이터는 로컬 워크스테이션에 다운로드할 수 있는 암호화된 단일 파일에 저장됩니다.

.시작하기 전에
구축이 백업 작업 중에 다른 작업을 수행하지 않는지 확인합니다.

.이 작업에 대해
생성한 백업 파일은 가상 머신의 모든 구성 데이터를 캡처합니다. 이 데이터는 ONTAP Select 클러스터를 포함한 구축 환경의 여러 측면을 설명합니다.

.단계
. 관리자 계정으로 SSH를 사용하여 배포 유틸리티 CLI에 로그인합니다.
. 배포 서버의 내부 디렉토리에 저장되는 배포 구성 데이터의 백업을 생성합니다.
+
백업 생성 배포

. 메시지가 표시되면 백업 암호를 입력합니다.
+
백업 파일은 암호를 기반으로 암호화됩니다.

. 시스템에서 사용 가능한 백업을 표시합니다.
+
백업 전개 - 세부 정보

. Created * 필드의 날짜를 기준으로 백업 파일을 선택하고 * Download URL * 값을 기록합니다.
+
URL을 통해 백업 파일에 액세스할 수 있습니다.

. Curl과 같은 웹 브라우저나 유틸리티를 사용하여 URL을 사용하여 로컬 워크스테이션에 백업 파일을 다운로드합니다.




== 구축 가상 머신의 새 인스턴스를 설치합니다

원래 가상 머신의 구성 데이터로 업데이트할 수 있는 가상 머신 구축 의 새 인스턴스를 생성해야 합니다.

.시작하기 전에
ONTAP Select 환경에서 가상 시스템을 다운로드하고 구축하는 데 사용되는 절차에 대해 잘 알고 있어야 합니다.

.이 작업에 대해
이 작업은 높은 수준에서 설명됩니다.

.단계
. 구축 가상 머신의 새 인스턴스를 생성합니다.
+
.. 가상 머신 이미지를 다운로드합니다.
.. 가상 머신을 구축하고 네트워크 인터페이스를 구성합니다.
.. SSH를 사용하여 배포 유틸리티에 액세스합니다.




.관련 정보
link:task_install_deploy.html["ONTAP Select Deploy를 설치합니다"]



== 구축 구성 데이터를 새 가상 머신에 복구합니다

원래 배포 유틸리티 가상 머신에서 새 가상 머신으로 구성 데이터를 복구해야 합니다. 데이터가 로컬 워크스테이션에서 업로드해야 하는 단일 파일에 있습니다.

.시작하기 전에
이전 백업의 구성 데이터가 있어야 합니다. 데이터는 단일 파일에 포함되어 있으며 로컬 워크스테이션에서 사용할 수 있어야 합니다.

.단계
. 로컬 워크스테이션의 명령 셸에서 SFTP 유틸리티를 사용하여 배포 가상 머신에 백업 파일을 업로드합니다.
+
예

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put deploy_backup_20190601162151.tar.gz
exit
....
. 관리자 계정으로 SSH를 사용하여 배포 유틸리티 CLI에 로그인합니다.
. 구성 데이터를 복원합니다.
+
백업 복원 경로 경로 경로 이름 파일 이름 "을(를) 배포합니다

+
예

+
deeploy backup restore-path/home/admin-filename deploy_backup_20180601162151.tar.gz


