---
sidebar: sidebar 
permalink: task_vpi_adm_network.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, administer, administering, network, networking 
summary: 탐색 및 표시할 수 있는 네트워크의 몇 가지 측면이 있습니다. 
---
= 네트워크 연결을 확인합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
탐색 및 표시할 수 있는 네트워크의 몇 가지 측면이 있습니다.



== 네트워크 연결을 확인합니다

내부 클러스터 네트워크의 두 개 이상의 ONTAP Select 노드 간에 네트워크 연결을 테스트할 수 있습니다. 일반적으로 다중 노드 클러스터를 구축하여 작업에 실패할 수 있는 문제를 감지하기 전에 이 테스트를 실행해야 합니다. 클러스터를 구축하고 온라인 상태로 생성한 후 연결 테스트를 실행할 수도 있습니다.

.이 작업에 대해
테스트를 시작할 때마다 백그라운드에서 새 프로세스가 생성되고 고유한 실행 식별자가 할당됩니다. 한 번에 하나의 시리즈만 활성화할 수 있습니다.

이 테스트는 항상 기본 무중단 테스트를 수행하는 빠른 모드로 실행됩니다. 네트워크 MTU 크기 및 vSwitch 테스트와 함께 Ping 테스트가 수행됩니다.

.단계
. 글로벌 인벤토리 목록 * 창에서 * ONTAP Select 배포 * 를 클릭합니다.
. Administration * 탭을 클릭합니다.
. 네트워크 * 옵션을 확장하고 * 연결 검사기 * 를 클릭합니다.
. Run New * 를 클릭하여 테스트를 시작합니다.
. 또는 * Filtering * 을 클릭하고 필터를 만들어 표시되는 테스트 세부 정보를 제한할 수도 있습니다.




== 중재자 서비스의 상태를 봅니다

각 ONTAP Select 2노드 클러스터는 노드 공유 HA 기능을 관리하는 데 도움이 되는 중재자 서비스에 의해 모니터링됩니다. 배포 관리 유틸리티에 정의된 각 2노드 클러스터의 중재자 서비스 상태를 볼 수 있습니다.

.이 작업에 대해
다음을 포함하여 각 중재자의 구성을 볼 수 있습니다.

* 현재 상태
* ONTAP Select 노드 2개
* HA 제어 정보가 저장된 iSCSI Target


.단계
. 글로벌 인벤토리 목록 * 창에서 * ONTAP Select 배포 * 를 클릭합니다.
. Administration * 탭을 클릭합니다.
. 중재자 * 옵션을 확장하고 * 상태 * 를 클릭합니다.
. 선택적으로 * Filtering * 을 클릭하고 중재자 서비스에서 모니터링하는 2노드 클러스터의 보기를 사용자 지정할 필터를 만듭니다.

