---
sidebar: sidebar 
permalink: task_vpi_deploy_cluster.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, deploy cluster, deploying cluster, create cluster, creating cluster 
summary: vSphere 웹 사용자 인터페이스를 통해 vCenter 구축 플러그인을 사용하여 ONTAP Select 클러스터를 구축할 수 있습니다. 
---
= ONTAP Select 클러스터 구축
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
vSphere 웹 사용자 인터페이스를 통해 vCenter 구축 플러그인을 사용하여 ONTAP Select 클러스터를 구축할 수 있습니다.



== 시작하기 전에

ONTAP Select 클러스터를 구축하기 전에 vCenter 배포 플러그인을 사용할 준비를 해야 합니다.



=== 모든 규모의 클러스터를 위한 공통 준비

클러스터 크기에 관계없이 여러 단계를 수행해야 합니다.

* vCenter 배포 플러그인에 익숙해지려면 _Getting started_ 섹션을 참조하십시오.
* ONTAP Select 배포 관리 유틸리티가 설치되어 실행 중인지 확인합니다.
* Deploy vCenter 플러그인을 설치합니다.
* ONTAP Select 클러스터를 실행할 하이퍼바이저 호스트 또는 호스트를 준비합니다.
* 클러스터의 노드에 필요한 스토리지 라이센스 파일을 가져옵니다.
* 다음 계정에 대한 자격 증명을 획득합니다.
+
** 관리자 계정 배포
** 플러그인을 액세스할 수 있는 vCenter 계정입니다


* 필요한 경우 Windows 인증서 관리자에 배포 SSL 인증서를 "신뢰할 수 있는 루트 인증 기관"으로 설치합니다.
* Deploy 유틸리티가 vCenter Server의 포트 443에 대한 네트워크 액세스 권한을 가지고 있는지 확인합니다.




=== 다중 노드 클러스터를 위한 추가 준비

다중 노드 클러스터를 구축하기 전에 네트워크 검사기 배포에 대해 잘 알고 있어야 합니다.



== 하이퍼바이저 호스트 추가

클러스터를 구축하기 전에 ONTAP Select 노드가 실행될 배포 유틸리티에 하이퍼바이저 호스트를 추가할 수 있습니다. 필요한 경우 클러스터 생성 대화 상자의 일부로 호스트를 추가할 수 있습니다.

ONTAP Select 클러스터 구축 준비 를 검토해야 합니다.

클러스터 크기에 따라 호스트를 하나 이상 추가할 수 있습니다.

.단계
. 브라우저를 사용하여 vSphere HTML5를 통해 vCenter Server에 로그인합니다.
. 도구 모음에서 * 메뉴 * 를 클릭한 다음 * 글로벌 재고 목록 * 을 클릭합니다.
. 왼쪽 창에서 * ONTAP Select Deploy * 를 클릭한 다음 * Hosts * 탭을 클릭합니다.
. 오른쪽에 있는 * 추가 * 를 클릭합니다.
. 호스트의 호스트 이름 또는 IP 주소를 입력한 다음 * 추가 * 또는 * 추가 및 종료 * 를 클릭합니다.




== 단일 노드 클러스터 생성

vSphere 웹 클라이언트를 통해 VMware vCenter 플러그인을 사용하여 단일 노드로 구성된 ONTAP Select 클러스터를 구축할 수 있습니다.

ONTAP Select 클러스터 구축 준비 및 하이퍼바이저 호스트 추가 를 검토해야 합니다. 클러스터를 생성하기 전에 ONTAP Select 노드가 실행될 호스트를 추가하거나 단일 노드 클러스터를 생성할 수 있습니다.

.단계
. 브라우저를 사용하여 vSphere HTML5를 통해 vCenter Server에 로그인합니다.
. 상단의 * Menu * 를 클릭한 다음 * Global Inventory Lists * 를 클릭합니다.
. 왼쪽 창에서 * ONTAP Select 클러스터 * 를 클릭한 다음 * 새 ONTAP Select * 를 클릭합니다.
+
이전에 SSL 인증서를 수락하지 않은 경우 경고 메시지에서 IP 링크를 클릭하고 인증서를 수락합니다. 그런 다음 vCenter 페이지로 돌아가서 경고 메시지의 링크를 클릭하여 페이지를 다시 로드합니다.

. New ONTAP Select * 페이지에서 클러스터 세부 정보를 입력하고 * Done * 을 클릭합니다.
. 노드 설정 * 섹션에서 구성을 제공하고 라이센스를 선택합니다.
+
필요한 경우 기본 노드 이름을 변경하고 새 라이센스를 업로드할 수 있습니다.

. 하이퍼바이저 및 네트워크 * 섹션에서 인스턴스 유형, 호스트 및 네트워크를 선택합니다.
+
필요한 경우 호스트를 추가할 수 있습니다. 노드의 라이센스는 인스턴스 유형을 충족하거나 초과해야 합니다.

. 스토리지 * 섹션에서 스토리지 용량과 스토리지 풀을 선택합니다.
+
프리미엄 라이센스를 사용할 때 소프트웨어 RAID를 선택적으로 활성화할 수 있습니다.

. Done * 을 클릭하고 클러스터의 구성을 검토합니다.
+
필요에 따라 각 섹션에서 편집 을 클릭하여 설정을 변경할 수 있습니다.

. 다음 * 을 클릭합니다.
. ONTAP 관리자 암호를 입력하고 * 클러스터 생성 * 을 클릭하여 클러스터 생성 프로세스를 시작한 다음 확인 팝업 창에서 * 확인 * 을 클릭합니다.
+
클러스터를 생성하는 데 최대 30분이 걸릴 수 있습니다.

. 페이지를 새로 고치고 새 클러스터를 선택한 다음 * 요약 * 및 * 세부 정보 * 를 클릭하여 다단계 클러스터 생성 프로세스를 모니터링합니다.
+

TIP: 클러스터 생성 작업이 시작되었지만 완료되지 않은 경우 정의한 ONTAP 관리 암호가 등록되지 않습니다. 이 경우 admin 계정으로 암호 changeme123 을 사용하여 ONTAP Select 클러스터의 관리 인터페이스에 액세스할 수 있습니다.



.작업을 마친 후
* ONTAP Select AutoSupport 기능이 활성화되었는지 확인합니다.
* ONTAP Select 배포 구성 데이터를 백업합니다.




== 다중 노드 클러스터 생성

vSphere 웹 클라이언트를 통해 VMware vCenter 플러그인을 사용하여 여러 노드로 구성된 ONTAP Select 클러스터를 구축할 수 있습니다.

ONTAP Select 클러스터 구축 준비 및 하이퍼바이저 호스트 추가 를 검토해야 합니다. 클러스터를 생성하기 전에 또는 다중 노드 클러스터를 생성하기 위한 일부로 ONTAP Select 노드가 실행될 호스트를 추가할 수 있습니다.

ONTAP Select 다중 노드 클러스터는 짝수 개의 노드로 구성됩니다. 노드는 항상 HA 쌍으로 연결됩니다.

.단계
. 브라우저를 사용하여 vSphere HTML5를 통해 vCenter Server에 로그인합니다.
. 상단의 * Menu * 를 클릭한 다음 * Global Inventory Lists * 를 클릭합니다.
. 왼쪽 창에서 * ONTAP Select 클러스터 * 를 클릭한 다음 * 새 ONTAP Select * 를 클릭합니다
+
이전에 SSL 인증서를 수락하지 않은 경우 경고 메시지에서 IP 링크를 클릭하고 인증서를 수락합니다. 그런 다음 vCenter 페이지로 돌아가서 경고 메시지의 링크를 클릭하여 페이지를 다시 로드합니다.

. New ONTAP Select * 페이지에서 클러스터 세부 정보를 입력하고 * Done * 을 클릭합니다.
+
클러스터 MTU 크기를 설정할 이유가 없는 경우 기본값을 적용하고 필요에 따라 Deploy make any Adjustments를 허용해야 합니다.

. 노드 설정 * 섹션에서 구성을 제공하고 HA 쌍의 두 노드에 대한 라이센스를 선택합니다.
+
필요한 경우 기본 노드 이름을 변경하고 새 라이센스를 업로드할 수 있습니다.

. 하이퍼바이저 및 네트워크 * 섹션에서 각 노드의 인스턴스 유형, 호스트 및 네트워크를 선택합니다.
+
필요한 경우 호스트를 추가할 수 있습니다. 3개의 네트워크를 선택해야 합니다. 내부 네트워크는 관리 또는 데이터 네트워크와 같을 수 없습니다. 노드의 라이센스는 인스턴스 유형을 충족하거나 초과해야 합니다.

. 스토리지 * 섹션에서 스토리지 용량과 스토리지 풀을 선택합니다.
+
프리미엄 라이센스를 사용할 때 소프트웨어 RAID를 선택적으로 활성화할 수 있습니다.

. 클러스터에 4개 이상의 노드가 있는 경우 첫 번째 HA 쌍에 사용된 것과 같은 단계를 수행하여 추가 HA 쌍에서 노드를 구성해야 합니다.
. Done * 을 클릭하고 클러스터의 구성을 검토합니다.
+
필요에 따라 각 섹션에서 * 편집 * 을 클릭하여 구성을 변경할 수 있습니다.

. 필요에 따라 네트워크 연결 검사기를 실행하여 내부 클러스터 네트워크의 노드 간 연결을 테스트합니다.
. 다음 * 을 클릭합니다.
. ONTAP 관리자 암호를 입력하고 * 클러스터 생성 * 을 클릭하여 클러스터 생성 프로세스를 시작한 다음 확인 팝업 창에서 * 확인 * 을 클릭합니다.
+
클러스터를 생성하는 데 최대 30분이 걸릴 수 있습니다.

. 페이지를 새로 고치고 새 클러스터를 선택한 다음 * 요약 * 및 * 세부 정보 * 를 클릭하여 다단계 클러스터 생성 프로세스를 모니터링합니다.
+

TIP: 클러스터 생성 작업이 시작되었지만 완료되지 않은 경우 정의한 ONTAP 관리 암호가 등록되지 않습니다. 이 경우 admin 계정으로 암호 changeme123 을 사용하여 ONTAP Select 클러스터의 관리 인터페이스에 액세스할 수 있습니다.



.작업을 마친 후
* ONTAP Select AutoSupport 기능이 활성화되었는지 확인합니다.
* ONTAP Select 배포 구성 데이터를 백업합니다.

