---
sidebar: sidebar 
permalink: task_vpi_adm_support.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, administer, administering, diagnostics, support 
summary: ONTAP Select 관리의 일부로 수행할 수 있는 몇 가지 관련 진단 및 지원 작업이 있습니다. 
---
= 진단 및 지원
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 관리의 일부로 수행할 수 있는 몇 가지 관련 진단 및 지원 작업이 있습니다.



== 시스템 설정을 표시합니다

vCenter 플러그인을 통해 배포 관리 유틸리티의 기본 설정을 볼 수 있습니다.

.단계
. 글로벌 인벤토리 목록 * 창에서 * ONTAP Select 배포 * 를 클릭합니다.
. Administration * 탭을 클릭합니다.
. 시스템* 옵션을 확장하고 * 설정 * 을 클릭합니다.
. 필요에 따라 시스템 구성을 업데이트하고 * Save * (저장 *)를 클릭합니다.




== 이벤트 메시지 표시

배포 관리 유틸리티에는 시스템 작업에 대한 정보를 제공하는 이벤트 로깅 기능이 포함되어 있습니다. 배포 플러그인을 통해 이벤트 로그의 내용을 보고 문제를 디버깅하거나 지원 부서의 지시가 있을 때 확인할 수 있습니다.

.이 작업에 대해
다음과 같은 여러 특성을 기반으로 이벤트 메시지 목록을 필터링할 수 있습니다.

* 범주
* 유형
* 레벨
* 인스턴스


.단계
. 글로벌 인벤토리 목록 * 창에서 * ONTAP Select 배포 * 를 클릭합니다.
. Administration * 탭을 클릭합니다.
. 이벤트 * 옵션을 확장하고 * 배포 * 를 클릭합니다.
. 필요한 경우 필터링 을 클릭하고 필터를 만들어 표시되는 이벤트 메시지를 제한합니다.




== AutoSupport 활성화 중

AutoSupport는 ONTAP Select 지원을 위해 NetApp에서 사용하는 주요 문제 해결 툴입니다. 필요에 따라 AutoSupport 기능을 활성화 또는 비활성화할 수 있습니다.

.이 작업에 대해
새 클러스터를 구축한 후에는 AutoSupport가 활성화되어 있는지 확인해야 합니다. 필요한 경우에만 AutoSupport를 비활성화해야 합니다. AutoSupport를 사용하지 않도록 설정하면 데이터가 수집되지만 NetApp에 전송되지 않습니다.

.단계
. 글로벌 인벤토리 목록 * 창에서 * ONTAP Select 배포 * 를 클릭합니다.
. Administration * 탭을 클릭합니다.
. AutoSupport * 옵션을 확장하고 * 구성 * 을 클릭합니다
. 필요에 따라 AutoSupport를 활성화 또는 비활성화합니다.




== AutoSupport 패키지를 생성하는 중입니다

Deploy vCenter 플러그인에는 AutoSupport 패키지를 생성할 수 있는 기능이 포함되어 있습니다. 문제를 디버깅하거나 지원 부서의 지시가 있을 때 패키지를 생성해야 합니다.

.이 작업에 대해
다음 AutoSupport 패키지를 생성할 수 있습니다.

* ONTAP Select 배포 유틸리티에서 만든 로그 파일을 배포합니다
* 문제 해결 하이퍼바이저 호스트 및 ONTAP Select 노드에 대한 문제 해결 및 디버깅 정보
* 하이퍼바이저 호스트 및 ONTAP Select 노드에 대한 성능 정보입니다


.단계
. 글로벌 인벤토리 목록 * 창에서 * ONTAP Select 배포 * 를 클릭합니다.
. Administration * 탭을 클릭합니다.
. AutoSupport * 옵션을 확장하고 * Generate * 를 클릭합니다.
. 유형을 선택하고 패키지에 대한 설명을 입력하거나 케이스 번호를 입력한 다음 * AutoSupport * 생성 을 클릭합니다.
. 왼쪽 창의 * AutoSupport * 에서 * History * 를 클릭하고 패키지를 찾습니다.
+
필요에 따라 * Refresh * (새로 고침 *)를 클릭할 수 있습니다.



.작업을 마친 후
기본 배포 유틸리티 사용자 인터페이스를 사용하여 AutoSupport 패키지를 워크스테이션에 다운로드할 수 있습니다. vCenter 배포 플러그인을 사용하여 패키지를 다운로드할 수 없습니다.
