---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: 배포 관리 유틸리티의 인스턴스에 ONTAP Select 이미지를 추가할 수 있습니다. 이미지를 설치한 후 ONTAP Select 클러스터를 배포할 때 사용할 수 있습니다. 
---
= 배포할 ONTAP Select 이미지 추가
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
배포 관리 유틸리티의 인스턴스에 ONTAP Select 이미지를 추가할 수 있습니다. 이미지를 설치한 후 ONTAP Select 클러스터를 배포할 때 사용할 수 있습니다.



== 시작하기 전에

상위 수준에서는 배포 인스턴스에 ONTAP Select 이미지를 추가하는 데 사용되는 프로세스는 다음 4단계로 구성됩니다.

. 설치 이미지를 다운로드하는 중입니다
. 구축 가상 머신에 설치 이미지를 업로드합니다
. 설치 이미지 추가
. 사용 가능한 설치 이미지를 표시합니다


배포할 새 ONTAP Select 이미지를 추가하기 전에 먼저 불필요한 이미지를 제거해야 합니다.


NOTE: 배포 유틸리티의 인스턴스에 포함된 원래 버전보다 이전 버전의 ONTAP Select 이미지만 추가해야 합니다. ONTAP Select의 이후 버전을 NetApp에서 사용할 수 있게 되면서 추가하는 것은 지원되는 구성이 아닙니다.



== 설치 이미지를 다운로드하는 중입니다

Deploy 유틸리티의 인스턴스에 ONTAP Select 이미지를 추가하는 프로세스를 시작하려면 NetApp Support 사이트에서 설치 이미지를 다운로드해야 합니다. ONTAP Select 설치 이미지는 압축된 단일 파일로 포맷됩니다.

.단계
. 웹 브라우저를 사용하여 NetApp Support 사이트에 액세스하여 * Support Quick Links * 를 클릭합니다.
. 상위 작업 * 에서 * 소프트웨어 다운로드 * 를 클릭하고 사이트에 로그인합니다.
. 제품 찾기 * 를 클릭합니다.
. 아래로 스크롤하여 * ONTAP Select * 를 클릭합니다.
. Other Available Select Software * 에서 * Deploy Upgrade, Node Upgrade, Image Install * 을 클릭합니다.
. 원하는 업그레이드 패키지 릴리스를 선택합니다.
. 최종 사용자 사용권 계약(EULA)을 검토하고 * 동의 및 계속 * 을 클릭합니다.
. 해당 패키지를 선택하여 다운로드하고 사용자 환경에 필요한 모든 프롬프트에 응답합니다.




== 배포할 설치 이미지를 업로드하는 중입니다

ONTAP Select 설치 이미지를 획득한 후 해당 파일을 배포 가상 머신에 업로드해야 합니다.

로컬 워크스테이션에서 설치 이미지 파일을 사용할 수 있어야 합니다. 배포 관리자 사용자 계정에 대한 암호도 있어야 합니다.

이 작업은 배포 가상 머신에 파일을 업로드하는 한 가지 방법을 설명합니다. 사용자 환경에 더 적합한 다른 옵션이 있을 수 있습니다.

.단계
. 로컬 워크스테이션의 명령 셸에서 이미지 파일을 Deploy virtual machine에 업로드합니다.
+
예

+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
예

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


노드 설치 파일은 admin 사용자의 홈 디렉토리에 저장됩니다.



== 설치 이미지 추가

새 클러스터를 구축할 때 사용할 수 있도록 ONTAP Select 설치 이미지를 Deploy images 디렉토리에 추가할 수 있습니다.

설치 이미지 파일이 배포 유틸리티 가상 머신에 있는 디렉토리를 알아야 합니다. 파일이 관리자의 홈 디렉토리에 있는 것으로 가정합니다.

.단계
. admin (admin) 계정으로 SSH를 사용하여 배포 유틸리티 CLI에 로그인합니다.
. Bash 쉘을 시작합니다.
+
'지옥배시'

. 이미지 디렉토리에 설치 이미지 파일을 배치합니다.
+
예: tar-XF image_v_93_install_ESX.tgz-C/opt/NetApp/images/





== 사용 가능한 설치 이미지를 표시합니다

새 클러스터를 구축할 때 사용 가능한 ONTAP Select 이미지를 표시할 수 있습니다.

.단계
. deploy utility virtual machine에서 온라인 설명서 웹 페이지에 액세스하고 administrator(admin) 계정을 사용하여 로그인합니다.
+
'\http://<FQDN|IP_ADDRESS>/api/ui`

+
배포 가상 머신의 도메인 이름 또는 IP 주소를 사용합니다.

. 페이지 하단으로 이동하여 * deploy * 를 클릭한 다음 * get/images * 를 클릭합니다.
. 사용 가능한 ONTAP Select 이미지를 표시하려면 * 시험 사용! * 을 클릭합니다.
. 원하는 영상을 사용할 수 있는지 확인합니다.

