---
sidebar: sidebar 
permalink: task_lic_acquire_cp.html 
keywords: license, licensing, acquire, Capacity Pools 
summary: ONTAP Select 노드에서 사용하는 각 Capacity Pool에 대한 라이센스 파일을 얻어야 합니다. 라이센스 파일은 풀에 대한 스토리지 용량과 만료일을 정의합니다. NetApp에서 할당한 고유 라이센스 일련 번호와 배포 인스턴스와 연결된 라이센스 잠금 ID를 조합하여 License Manager에 잠깁니다. 
---
= ONTAP Select 용량 풀 라이센스를 취득합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 노드에서 사용하는 각 Capacity Pool에 대한 라이센스 파일을 얻어야 합니다. 라이센스 파일은 풀에 대한 스토리지 용량과 만료일을 정의합니다. NetApp에서 할당한 고유 라이센스 일련 번호와 배포 인스턴스와 연결된 라이센스 잠금 ID를 조합하여 License Manager에 잠깁니다.

.시작하기 전에
* Capacity Pool에 NetApp에서 할당한 9자리 라이센스 일련 번호가 있어야 합니다.
* 구매 주문서 발송일로부터 최소 24시간이 지난 후에 라이센스 파일을 받으실 수 있습니다.
* link:sizing-capacity-pool-license.html["Capacity Pools 라이센스 규모 산정 시 고려 사항"]를 검토했습니다.


.이 작업에 대해
ONTAP Select 노드에서 사용하는 각 용량 풀에 대해 이 작업을 수행해야 합니다.

.단계
. link:https://mysupport.netapp.com/site/["NetApp Support 사이트"^]에 로그인하십시오.
. *Systems* > *Software Licenses*를 선택합니다.
. Capacity Pool의 라이센스 일련 번호를 입력하고 *Go!*를 선택합니다.
. 라이센스 세부 정보 페이지에서 * 제품 세부 정보 * 열로 이동합니다.
. 해당 행에서 *NetApp 라이센스 파일 가져오기*를 선택합니다.
. ONTAP Select Deploy 인스턴스의 라이센스 잠금 ID를 입력하고 *제출*을 선택하십시오.
. 적절한 전달 방법을 선택하고 *제출*을 선택합니다.
. 배송 확인 창에서 *확인*을 선택합니다.


.작업을 마친 후
ONTAP Select 노드가 용량 풀을 사용하려면 먼저 Deploy 관리 유틸리티에 라이센스 파일을 업로드해야 합니다.
