---
sidebar: sidebar 
permalink: task_cli_deploy_recover_two_node.html 
keywords: administer, administering, cli, two node cluster, recover, recovering 
summary: ONTAP Select Deploy 유틸리티가 실패하거나 어떤 이유로 사용할 수 없는 경우 ONTAP Select 노드와 클러스터를 관리할 수 없습니다. 또한 배포에 포함된 중재자 서비스를 사용할 수 없기 때문에 모든 2노드 클러스터에서 HA 기능이 손실됩니다. 복구할 수 없는 장애가 발생하면 deploy 유틸리티 인스턴스를 복구하여 관리 및 HA 기능을 복원해야 합니다. 
---
= 2노드 클러스터의 ONTAP Select Deploy 유틸리티를 복구합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select Deploy 유틸리티가 실패하거나 어떤 이유로 사용할 수 없는 경우 ONTAP Select 노드와 클러스터를 관리할 수 없습니다. 또한 배포에 포함된 중재자 서비스를 사용할 수 없기 때문에 모든 2노드 클러스터에서 HA 기능이 손실됩니다. 복구할 수 없는 장애가 발생하면 deploy 유틸리티 인스턴스를 복구하여 관리 및 HA 기능을 복원해야 합니다.



== Deploy 유틸리티 복구 준비

Deploy 유틸리티 인스턴스를 복구하려면 먼저 준비를 해야 합니다. 이렇게 하면 복구가 성공합니다.  여러 행정 절차에 익숙해야 하며, 필요한 정보를 가지고 있어야 합니다.

.단계
. 하이퍼바이저 환경에서 ONTAP Select Deploy 유틸리티의 새 인스턴스를 설치할 수 있는지 확인하세요.
+
link:task_install_deploy.html["ONTAP Select Deploy 유틸리티 설치에 대해 알아보세요"]

. ONTAP Select 클러스터에 로그인하여 ONTAP 클러스터 셸(CLI)에 액세스할 수 있는지 확인하세요.
. ONTAP Select 2노드 클러스터가 포함된 실패한 배포 유틸리티 인스턴스의 구성 데이터 백업이 있는지 확인하세요. 클러스터가 포함되지 않은 백업이 있을 수도 있습니다.
. 사용된 복구 절차에 따라 배포 구성 데이터의 백업을 복원할 수 있는지 확인하세요.
+
link:task_cli_migrate_deploy.html#step-3-restore-the-deploy-configuration-data-to-the-new-virtual-machine["새 가상 머신에 배포 구성 데이터를 복원하는 방법에 대해 알아보세요."]

. 실패한 원래 Deploy 유틸리티 가상 머신의 IP 주소가 있습니다.
. 용량 풀 또는 용량 계층 라이선싱이 사용되는지 확인합니다. 용량 풀 라이선싱을 사용하는 경우, 배포 인스턴스를 복구하거나 복원한 후 각 용량 풀 라이선스를 다시 설치해야 합니다.
. ONTAP Select Deploy 유틸리티 인스턴스를 복구할 때 사용할 절차를 결정합니다. 이 결정은 ONTAP Select 2노드 클러스터가 포함된 원래 실패한 Deploy 유틸리티의 구성 데이터 백업본이 있는지 여부에 따라 달라집니다.
+
[cols="35,65"]
|===
| 2노드 클러스터를 포함하는 구축 백업이 있습니까? | 복구 절차를 사용하세요... 


| 예 | <<restore-deploy-backup,구성 백업을 사용하여 배포 유틸리티 인스턴스를 복원합니다>> 


| 아니요 | <<restore-and-recover-deploy,배포 유틸리티 인스턴스를 재구성하고 복구합니다>> 
|===




== 구성 백업을 사용하여 배포 유틸리티 인스턴스를 복원합니다

2노드 클러스터를 포함하는 실패한 배포 유틸리티 인스턴스 백업이 있는 경우 구성 데이터를 새 배포 가상 시스템 인스턴스로 복원할 수 있습니다. 그런 다음 ONTAP Select 클러스터에서 두 노드의 추가 구성을 수행하여 복구를 완료해야 합니다.

.시작하기 전에
2노드 클러스터가 포함된 원래 배포 실패 가상 머신에서 구성 데이터를 백업합니다. 2노드 클러스터의 ONTAP CLI에 로그인하고 두 노드의 ONTAP 이름을 알고 있어야 합니다.

.이 작업에 대해
복원하는 구성 백업에는 2노드 클러스터가 포함되어 있으므로 중재자인 iSCSI 타겟과 사서함이 새 배포 유틸리티 가상 시스템에서 다시 생성됩니다.

.단계
. ONTAP Select 배포 유틸리티의 새 인스턴스를 준비합니다.
+
.. 새 배포 유틸리티 가상 시스템을 설치합니다.
.. 이전 백업에서 새 가상 머신으로 구축 구성을 복구합니다.
+
설치 및 복원 절차에 대한 자세한 내용은 관련 작업을 참조하십시오.



. ONTAP Select 2노드 클러스터의 ONTAP 명령줄 인터페이스에 로그인합니다.
. 고급 권한 모드 시작:
+
[source, cli]
----
set adv
----
. 새로운 Deploy 가상 머신의 IP 주소가 원래 Deploy 가상 머신과 다른 경우, 이전 중재자 iSCSI 대상을 제거하고 새 대상을 추가합니다.
+
[source, cli]
----
storage iscsi-initiator remove-target -node * -target-type mailbox
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node2_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
"<ip_address>" 매개변수는 새 배포 가상 시스템의 IP 주소입니다.

+
이러한 명령을 사용하면 ONTAP Select 노드에서 새 Deploy 유틸리티 가상 머신의 메일박스 디스크를 검색할 수 있습니다.

. 중재 디스크의 이름을 확인합니다.
+
[source, cli]
----
disk show -container-type mediator
----
. 메일박스 디스크를 두 노드에 할당합니다.
+
[source, cli]
----
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
----
. 스토리지 페일오버가 설정되었는지 확인합니다.
+
[source, cli]
----
storage failover show
----


.작업을 마친 후
용량 풀 라이선스를 사용하는 경우 각 용량 풀 라이선스를 다시 설치하세요.  보다link:task_adm_licenses.html#reinstall-a-capacity-pool-license["Capacity Pool 라이센스를 다시 설치합니다"] 자세한 내용은 다음을 참조하세요.



== 배포 유틸리티 인스턴스를 재구성하고 복구합니다

2노드 클러스터가 포함된 실패한 Deploy 유틸리티 인스턴스의 백업이 없는 경우 새 Deploy 가상 머신에서 중재자 iSCSI 대상과 사서함을 구성합니다.  그런 다음 ONTAP Select 클러스터의 두 노드에 대한 추가 구성을 수행하여 복구를 완료합니다.

.시작하기 전에
새로운 Deploy 유틸리티 인스턴스에 대한 중재자 대상의 이름이 있는지 확인하세요. 2노드 클러스터의 ONTAP CLI에 로그인하고 두 노드의 ONTAP 이름을 알고 있어야 합니다.

.이 작업에 대해
2노드 클러스터가 포함되어 있지 않더라도 필요에 따라 구성 백업을 새 구축 가상 머신에 복구할 수 있습니다. 2노드 클러스터는 복구를 통해 다시 생성되지 않으므로 배포에 있는 ONTAP Select 온라인 설명서 웹 페이지를 통해 중재 iSCSI 대상과 사서함을 새 배포 유틸리티 인스턴스에 수동으로 추가해야 합니다. 2노드 클러스터에 로그인하여 2노드 클러스터의 ONTAP 이름을 알아야 합니다.


NOTE: 복구 절차의 목표는 정상 HA 테이크오버 및 반환 작업을 수행할 수 있는 정상 상태로 2노드 클러스터를 복원하는 것입니다.

.단계
. ONTAP Select 배포 유틸리티의 새 인스턴스를 준비합니다.
+
.. 새 배포 유틸리티 가상 시스템을 설치합니다.
.. 필요에 따라 이전 백업에서 새 가상 머신으로 구축 구성을 복구합니다.
+
이전 백업을 복원하면 새 배포 인스턴스에 2노드 클러스터가 포함되지 않습니다. 설치 및 복원 절차에 대한 자세한 내용은 관련 정보 섹션을 참조하십시오.



. ONTAP Select 2노드 클러스터의 ONTAP 명령줄 인터페이스에 로그인합니다.
. 고급 특별 권한 모드 시작:
+
[source, cli]
----
set adv
----
. 중재자 iSCSI 대상 이름 가져오기:
+
[source, cli]
----
storage iscsi-initiator show -target-type mailbox
----
. 새 배포 유틸리티 가상 컴퓨터에서 온라인 설명서 웹 페이지에 액세스하고 관리자 계정을 사용하여 로그인합니다.
+
'\http://<ip_address>/api/ui`

+
구축 가상 머신의 IP 주소를 사용해야 합니다.

. *중재자*를 선택한 다음 *GET /중재자*를 선택하세요.
. *사용해 보세요!*를 선택하면 Deploy에서 관리하는 중재자 목록이 표시됩니다.
+
원하는 중재자 인스턴스의 ID를 확인합니다.

. *중재자*를 선택한 다음 *게시*를 선택합니다.
. 중재자_ID의 값을 제공하십시오
. *모델*을 선택하세요 `iscsi_target` 그리고 이름 값을 완성하세요.
+
iqn_name 매개 변수의 대상 이름을 사용합니다.

. *시험해 보세요!*를 선택하여 중재자 iSCSI 대상을 만듭니다.
+
요청이 성공하면 HTTP 상태 코드 200을 받게 됩니다.

. 새 배포 가상 시스템의 IP 주소가 원본 배포 가상 시스템과 다른 경우 ONTAP CLI를 사용하여 이전의 중재 iSCSI 대상을 제거하고 새 대상을 추가해야 합니다.
+
[source, cli]
----
storage iscsi-initiator remove-target -node * -target-type mailbox
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node2_name> -label mediator-target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
"<ip_address>" 매개변수는 새 배포 가상 시스템의 IP 주소입니다.

+
이러한 명령을 사용하면 ONTAP Select 노드에서 새 Deploy 유틸리티 가상 머신의 메일박스 디스크를 검색할 수 있습니다.

. 중재 디스크의 이름을 확인합니다.
+
[source, cli]
----
disk show -container-type mediator
----
. 메일박스 디스크를 두 노드에 할당합니다.
+
[source, cli]
----
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
----
. 스토리지 페일오버가 설정되었는지 확인합니다.
+
[source, cli]
----
storage failover show
----


.작업을 마친 후
용량 풀 라이선스를 사용하는 경우 각 용량 풀 라이선스를 다시 설치하세요.  보다link:task_adm_licenses.html#reinstall-a-capacity-pool-license["Capacity Pool 라이센스를 다시 설치합니다"] 자세한 내용은 다음을 참조하세요.
