---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: 배포 관리 유틸리티의 인스턴스에 ONTAP Select 이미지를 추가할 수 있습니다. 이미지를 설치한 후 ONTAP Select 클러스터를 배포할 때 사용할 수 있습니다. 
---
= 배포할 ONTAP Select 이미지를 추가합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
배포 관리 유틸리티의 인스턴스에 ONTAP Select 이미지를 추가할 수 있습니다. 이미지를 설치한 후 ONTAP Select 클러스터를 배포할 때 사용할 수 있습니다.

.시작하기 전에
배포할 새 ONTAP Select 이미지를 추가하기 전에 먼저 불필요한 이미지를 제거해야 합니다.


NOTE: 배포 유틸리티의 인스턴스에 포함된 원래 버전보다 이전 버전의 ONTAP Select 이미지만 추가해야 합니다. ONTAP Select의 이후 버전을 NetApp에서 사용할 수 있게 되면서 추가하는 것은 지원되는 구성이 아닙니다.



== 1단계: 설치 이미지 다운로드

Deploy 유틸리티의 인스턴스에 ONTAP Select 이미지를 추가하는 프로세스를 시작하려면 NetApp Support 사이트에서 설치 이미지를 다운로드해야 합니다. ONTAP Select 설치 이미지는 압축된 단일 파일로 포맷됩니다.

.단계
. 웹 브라우저를 사용하여 NetApp 지원 사이트에 접속하고 *지원 빠른 링크*를 선택하세요.
. *주요 작업*에서 *소프트웨어 다운로드*를 선택하고 사이트에 로그인하세요.
. *제품 찾기*를 선택하세요.
. 아래로 스크롤하여 * ONTAP Select*를 클릭합니다.
. *다른 사용 가능한 소프트웨어 선택*에서 *배포 업그레이드, 노드 업그레이드, 이미지 설치*를 선택합니다.
. 원하는 업그레이드 패키지 릴리스를 선택합니다.
. 최종 사용자 사용권 계약(EULA)을 검토하고 * Accept & Continue * 를 선택합니다.
. 해당 패키지를 선택하여 다운로드하고 사용자 환경에 필요한 모든 프롬프트에 응답합니다.




== 2단계: Deploy에 설치 이미지 업로드

ONTAP Select 설치 이미지를 획득한 후 해당 파일을 배포 가상 머신에 업로드해야 합니다.

.시작하기 전에
로컬 워크스테이션에서 설치 이미지 파일을 사용할 수 있어야 합니다. 배포 관리자 사용자 계정에 대한 암호도 있어야 합니다.

.이 작업에 대해
이 작업은 배포 가상 머신에 파일을 업로드하는 한 가지 방법을 설명합니다. 사용자 환경에 더 적합한 다른 옵션이 있을 수 있습니다.

.단계
. 로컬 워크스테이션의 명령 셸에서 다음 예시와 같이 이미지 파일을 가상 머신 배포에 업로드합니다.
+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.결과
노드 설치 파일은 admin 사용자의 홈 디렉토리에 저장됩니다.



== 3단계: 설치 이미지 추가

새 클러스터를 배포할 때 사용할 수 있도록 ONTAP Select 설치 이미지를 배포 이미지 디렉토리에 추가합니다.

.시작하기 전에
설치 이미지 파일이 배포 유틸리티 가상 머신에 있는 디렉토리를 알아야 합니다. 파일이 관리자의 홈 디렉토리에 있는 것으로 가정합니다.

.단계
. admin (admin) 계정으로 SSH를 사용하여 배포 유틸리티 CLI에 로그인합니다.
. Bash 쉘을 시작합니다.
+
[source, cli]
----
shell bash
----
. 다음 예와 같이 설치 이미지 파일을 이미지 디렉토리에 넣습니다.
+
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== 4단계: 사용 가능한 설치 이미지 표시

새 클러스터를 배포할 때 사용할 수 있는 ONTAP Select 이미지를 표시합니다.

.단계
. deploy utility virtual machine에서 온라인 설명서 웹 페이지에 액세스하고 administrator(admin) 계정을 사용하여 로그인합니다.
+
'\http://<FQDN|IP_ADDRESS>/api/ui`

+
배포 가상 머신의 도메인 이름 또는 IP 주소를 사용합니다.

. 페이지 하단으로 이동하여 *배포*를 선택한 다음 *GET /images*를 선택합니다.
. *시도해 보세요!*를 선택하면 사용 가능한 ONTAP Select 이미지가 표시됩니다.
. 원하는 영상을 사용할 수 있는지 확인합니다.

